namespace Hero_Designer
{

    [global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
    public partial class frmColourSettings : global::System.Windows.Forms.Form
    {

        [global::System.Diagnostics.DebuggerNonUserCode]
        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }


        [global::System.Diagnostics.DebuggerStepThrough]
        private void InitializeComponent()
        {
            global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmColourSettings));
            this.rtPreview = new global::System.Windows.Forms.RichTextBox();
            this.csInv = new global::System.Windows.Forms.Label();
            this.Label3 = new global::System.Windows.Forms.Label();
            this.btnCancel = new global::System.Windows.Forms.Button();
            this.btnOK = new global::System.Windows.Forms.Button();
            this.csAlert = new global::System.Windows.Forms.Label();
            this.Label9 = new global::System.Windows.Forms.Label();
            this.csEnh = new global::System.Windows.Forms.Label();
            this.Label7 = new global::System.Windows.Forms.Label();
            this.Label5 = new global::System.Windows.Forms.Label();
            this.csFade = new global::System.Windows.Forms.Label();
            this.Label4 = new global::System.Windows.Forms.Label();
            this.csInvInv = new global::System.Windows.Forms.Label();
            this.csText = new global::System.Windows.Forms.Label();
            this.csVillain = new global::System.Windows.Forms.Label();
            this.csHero = new global::System.Windows.Forms.Label();
            this.Label21 = new global::System.Windows.Forms.Label();
            this.Label22 = new global::System.Windows.Forms.Label();
            this.Label20 = new global::System.Windows.Forms.Label();
            this.Label19 = new global::System.Windows.Forms.Label();
            this.cPicker = new global::System.Windows.Forms.ColorDialog();
            this.Label1 = new global::System.Windows.Forms.Label();
            this.csSpecial = new global::System.Windows.Forms.Label();
            this.Label6 = new global::System.Windows.Forms.Label();
            this.csValue = new global::System.Windows.Forms.Label();
            this.Label10 = new global::System.Windows.Forms.Label();
            this.btnReset = new global::System.Windows.Forms.Button();
            this.Label2 = new global::System.Windows.Forms.Label();
            this.Listlabel1 = new global::midsControls.ListLabelV2();
            base.SuspendLayout();
            global::System.Drawing.Point point = new global::System.Drawing.Point(218, 49);
            this.rtPreview.Location = point;
            this.rtPreview.Name = "rtPreview";
            global::System.Drawing.Size size = new global::System.Drawing.Size(197, 195);
            this.rtPreview.Size = size;
            this.rtPreview.TabIndex = 0;
            this.rtPreview.Text = "";
            this.csInv.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csInv.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 109);
            this.csInv.Location = point;
            this.csInv.Name = "csInv";
            size = new global::System.Drawing.Size(52, 16);
            this.csInv.Size = size;
            this.csInv.TabIndex = 51;
            point = new global::System.Drawing.Point(12, 109);
            this.Label3.Location = point;
            this.Label3.Name = "Label3";
            size = new global::System.Drawing.Size(118, 16);
            this.Label3.Size = size;
            this.Label3.TabIndex = 50;
            this.Label3.Text = "Inventions:";
            this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
            point = new global::System.Drawing.Point(192, 371);
            this.btnCancel.Location = point;
            this.btnCancel.Name = "btnCancel";
            size = new global::System.Drawing.Size(75, 23);
            this.btnCancel.Size = size;
            this.btnCancel.TabIndex = 49;
            this.btnCancel.Text = "Cancel";
            this.btnOK.DialogResult = global::System.Windows.Forms.DialogResult.OK;
            point = new global::System.Drawing.Point(276, 371);
            this.btnOK.Location = point;
            this.btnOK.Name = "btnOK";
            size = new global::System.Drawing.Size(75, 23);
            this.btnOK.Size = size;
            this.btnOK.TabIndex = 48;
            this.btnOK.Text = "OK";
            this.csAlert.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csAlert.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 189);
            this.csAlert.Location = point;
            this.csAlert.Name = "csAlert";
            size = new global::System.Drawing.Size(52, 16);
            this.csAlert.Size = size;
            this.csAlert.TabIndex = 47;
            point = new global::System.Drawing.Point(12, 189);
            this.Label9.Location = point;
            this.Label9.Name = "Label9";
            size = new global::System.Drawing.Size(118, 16);
            this.Label9.Size = size;
            this.Label9.TabIndex = 46;
            this.Label9.Text = "Alert:";
            this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.csEnh.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csEnh.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 169);
            this.csEnh.Location = point;
            this.csEnh.Name = "csEnh";
            size = new global::System.Drawing.Size(52, 16);
            this.csEnh.Size = size;
            this.csEnh.TabIndex = 45;
            point = new global::System.Drawing.Point(12, 169);
            this.Label7.Location = point;
            this.Label7.Name = "Label7";
            size = new global::System.Drawing.Size(118, 16);
            this.Label7.Size = size;
            this.Label7.TabIndex = 44;
            this.Label7.Text = "Enhancements:";
            this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(17, 16);
            this.Label5.Location = point;
            this.Label5.Name = "Label5";
            size = new global::System.Drawing.Size(192, 16);
            this.Label5.Size = size;
            this.Label5.TabIndex = 43;
            this.Label5.Text = "Click on a color box to modify it.";
            this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.csFade.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csFade.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 149);
            this.csFade.Location = point;
            this.csFade.Name = "csFade";
            size = new global::System.Drawing.Size(52, 16);
            this.csFade.Size = size;
            this.csFade.TabIndex = 42;
            point = new global::System.Drawing.Point(12, 149);
            this.Label4.Location = point;
            this.Label4.Name = "Label4";
            size = new global::System.Drawing.Size(118, 16);
            this.Label4.Size = size;
            this.Label4.TabIndex = 41;
            this.Label4.Text = "Faded:";
            this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.csInvInv.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csInvInv.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 129);
            this.csInvInv.Location = point;
            this.csInvInv.Name = "csInvInv";
            size = new global::System.Drawing.Size(52, 16);
            this.csInvInv.Size = size;
            this.csInvInv.TabIndex = 40;
            this.csText.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csText.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 89);
            this.csText.Location = point;
            this.csText.Name = "csText";
            size = new global::System.Drawing.Size(52, 16);
            this.csText.Size = size;
            this.csText.TabIndex = 39;
            this.csVillain.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csVillain.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 69);
            this.csVillain.Location = point;
            this.csVillain.Name = "csVillain";
            size = new global::System.Drawing.Size(52, 16);
            this.csVillain.Size = size;
            this.csVillain.TabIndex = 38;
            this.csHero.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csHero.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 49);
            this.csHero.Location = point;
            this.csHero.Name = "csHero";
            size = new global::System.Drawing.Size(52, 16);
            this.csHero.Size = size;
            this.csHero.TabIndex = 37;
            point = new global::System.Drawing.Point(12, 129);
            this.Label21.Location = point;
            this.Label21.Name = "Label21";
            size = new global::System.Drawing.Size(118, 16);
            this.Label21.Size = size;
            this.Label21.TabIndex = 36;
            this.Label21.Text = "Inventions (On White)";
            this.Label21.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(12, 89);
            this.Label22.Location = point;
            this.Label22.Name = "Label22";
            size = new global::System.Drawing.Size(118, 16);
            this.Label22.Size = size;
            this.Label22.TabIndex = 35;
            this.Label22.Text = "Text:";
            this.Label22.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(12, 69);
            this.Label20.Location = point;
            this.Label20.Name = "Label20";
            size = new global::System.Drawing.Size(118, 16);
            this.Label20.Size = size;
            this.Label20.TabIndex = 34;
            this.Label20.Text = "Villain Background:";
            this.Label20.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(12, 49);
            this.Label19.Location = point;
            this.Label19.Name = "Label19";
            size = new global::System.Drawing.Size(118, 16);
            this.Label19.Size = size;
            this.Label19.TabIndex = 33;
            this.Label19.Text = "Hero Background:";
            this.Label19.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.cPicker.FullOpen = true;
            point = new global::System.Drawing.Point(215, 30);
            this.Label1.Location = point;
            this.Label1.Name = "Label1";
            size = new global::System.Drawing.Size(88, 16);
            this.Label1.Size = size;
            this.Label1.TabIndex = 52;
            this.Label1.Text = "Preview:";
            this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            this.csSpecial.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csSpecial.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 229);
            this.csSpecial.Location = point;
            this.csSpecial.Name = "csSpecial";
            size = new global::System.Drawing.Size(52, 16);
            this.csSpecial.Size = size;
            this.csSpecial.TabIndex = 56;
            point = new global::System.Drawing.Point(12, 228);
            this.Label6.Location = point;
            this.Label6.Name = "Label6";
            size = new global::System.Drawing.Size(118, 16);
            this.Label6.Size = size;
            this.Label6.TabIndex = 55;
            this.Label6.Text = "Special Case Value:";
            this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.csValue.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csValue.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(134, 209);
            this.csValue.Location = point;
            this.csValue.Name = "csValue";
            size = new global::System.Drawing.Size(52, 16);
            this.csValue.Size = size;
            this.csValue.TabIndex = 54;
            point = new global::System.Drawing.Point(12, 208);
            this.Label10.Location = point;
            this.Label10.Name = "Label10";
            size = new global::System.Drawing.Size(118, 16);
            this.Label10.Size = size;
            this.Label10.TabIndex = 53;
            this.Label10.Text = "Value Name:";
            this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(85, 371);
            this.btnReset.Location = point;
            this.btnReset.Name = "btnReset";
            size = new global::System.Drawing.Size(98, 23);
            this.btnReset.Size = size;
            this.btnReset.TabIndex = 57;
            this.btnReset.Text = "Set to Defaults";
            point = new global::System.Drawing.Point(20, 265);
            this.Label2.Location = point;
            this.Label2.Name = "Label2";
            size = new global::System.Drawing.Size(189, 91);
            this.Label2.Size = size;
            this.Label2.TabIndex = 59;
            this.Label2.Text = "Click an item in the list to the right to modify the colors used in power lists";
            this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.Listlabel1.AutoSize = true;
            this.Listlabel1.Expandable = false;
            this.Listlabel1.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Pixel);
            this.Listlabel1.HighVis = true;
            this.Listlabel1.HoverColor = global::System.Drawing.Color.WhiteSmoke;
            point = new global::System.Drawing.Point(218, 265);
            this.Listlabel1.Location = point;
            this.Listlabel1.MaxHeight = 600;
            this.Listlabel1.Name = "Listlabel1";
            this.Listlabel1.PaddingX = 2;
            this.Listlabel1.PaddingY = 2;
            this.Listlabel1.Scrollable = true;
            this.Listlabel1.ScrollBarColor = global::System.Drawing.Color.Red;
            this.Listlabel1.ScrollBarWidth = 11;
            this.Listlabel1.ScrollButtonColor = global::System.Drawing.Color.FromArgb(192, 0, 0);
            size = new global::System.Drawing.Size(197, 91);
            this.Listlabel1.Size = size;
            size = new global::System.Drawing.Size(197, 91);
            this.Listlabel1.SizeNormal = size;
            this.Listlabel1.SuspendRedraw = false;
            this.Listlabel1.TabIndex = 111;
            base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.None;
            size = new global::System.Drawing.Size(436, 406);
            base.ClientSize = size;
            base.Controls.Add(this.Listlabel1);
            base.Controls.Add(this.Label2);
            base.Controls.Add(this.btnReset);
            base.Controls.Add(this.csSpecial);
            base.Controls.Add(this.Label6);
            base.Controls.Add(this.csValue);
            base.Controls.Add(this.Label10);
            base.Controls.Add(this.Label1);
            base.Controls.Add(this.csInv);
            base.Controls.Add(this.Label3);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.csAlert);
            base.Controls.Add(this.Label9);
            base.Controls.Add(this.csEnh);
            base.Controls.Add(this.Label7);
            base.Controls.Add(this.Label5);
            base.Controls.Add(this.csFade);
            base.Controls.Add(this.Label4);
            base.Controls.Add(this.csInvInv);
            base.Controls.Add(this.csText);
            base.Controls.Add(this.csVillain);
            base.Controls.Add(this.csHero);
            base.Controls.Add(this.Label21);
            base.Controls.Add(this.Label22);
            base.Controls.Add(this.Label20);
            base.Controls.Add(this.Label19);
            base.Controls.Add(this.rtPreview);
            this.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
            base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmColourSettings";
            base.ShowInTaskbar = false;
            base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Colors";
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        private global::System.ComponentModel.IContainer components;
    }
}
