namespace Hero_Designer
{

    public partial class frmCalcOpt : global::System.Windows.Forms.Form
    {

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }


        [global::System.Diagnostics.DebuggerStepThrough]
        private void InitializeComponent()
        {
            this.components = new global::System.ComponentModel.Container();
            global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmCalcOpt));
            this.btnOK = new global::System.Windows.Forms.Button();
            this.btnCancel = new global::System.Windows.Forms.Button();
            this.TabControl1 = new global::System.Windows.Forms.TabControl();
            this.TabPage3 = new global::System.Windows.Forms.TabPage();
            this.chkShowAlphaPopup = new global::System.Windows.Forms.CheckBox();
            this.chkNoTips = new global::System.Windows.Forms.CheckBox();
            this.chkMiddle = new global::System.Windows.Forms.CheckBox();
            this.GroupBox17 = new global::System.Windows.Forms.GroupBox();
            this.chkColorInherent = new global::System.Windows.Forms.CheckBox();
            this.chkHighVis = new global::System.Windows.Forms.CheckBox();
            this.Label36 = new global::System.Windows.Forms.Label();
            this.chkStatBold = new global::System.Windows.Forms.CheckBox();
            this.chkTextBold = new global::System.Windows.Forms.CheckBox();
            this.btnFontColour = new global::System.Windows.Forms.Button();
            this.Label22 = new global::System.Windows.Forms.Label();
            this.chkVillainColour = new global::System.Windows.Forms.CheckBox();
            this.Label21 = new global::System.Windows.Forms.Label();
            this.udStatSize = new global::System.Windows.Forms.NumericUpDown();
            this.udRTFSize = new global::System.Windows.Forms.NumericUpDown();
            this.chkIOPrintLevels = new global::System.Windows.Forms.CheckBox();
            this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
            this.rbGraphSimple = new global::System.Windows.Forms.RadioButton();
            this.rbGraphStacked = new global::System.Windows.Forms.RadioButton();
            this.rbGraphTwoLine = new global::System.Windows.Forms.RadioButton();
            this.GroupBox14 = new global::System.Windows.Forms.GroupBox();
            this.chkIOLevel = new global::System.Windows.Forms.CheckBox();
            this.btnIOReset = new global::System.Windows.Forms.Button();
            this.Label40 = new global::System.Windows.Forms.Label();
            this.udIOLevel = new global::System.Windows.Forms.NumericUpDown();
            this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
            this.chkRelSignOnly = new global::System.Windows.Forms.CheckBox();
            this.Label3 = new global::System.Windows.Forms.Label();
            this.optTO = new global::System.Windows.Forms.RadioButton();
            this.optDO = new global::System.Windows.Forms.RadioButton();
            this.optSO = new global::System.Windows.Forms.RadioButton();
            this.optEnh = new global::System.Windows.Forms.Label();
            this.cbEnhLevel = new global::System.Windows.Forms.ComboBox();
            this.Label4 = new global::System.Windows.Forms.Label();
            this.TabPage2 = new global::System.Windows.Forms.TabPage();
            this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
            this.clbSuppression = new global::System.Windows.Forms.CheckedListBox();
            this.Label8 = new global::System.Windows.Forms.Label();
            this.chkUseArcanaTime = new global::System.Windows.Forms.CheckBox();
            this.GroupBox15 = new global::System.Windows.Forms.GroupBox();
            this.Label20 = new global::System.Windows.Forms.Label();
            this.chkSetBonus = new global::System.Windows.Forms.CheckBox();
            this.chkIOEffects = new global::System.Windows.Forms.CheckBox();
            this.GroupBox8 = new global::System.Windows.Forms.GroupBox();
            this.rbChanceIgnore = new global::System.Windows.Forms.RadioButton();
            this.rbChanceAverage = new global::System.Windows.Forms.RadioButton();
            this.rbChanceMax = new global::System.Windows.Forms.RadioButton();
            this.Label9 = new global::System.Windows.Forms.Label();
            this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
            this.Label7 = new global::System.Windows.Forms.Label();
            this.rbPvP = new global::System.Windows.Forms.RadioButton();
            this.rbPvE = new global::System.Windows.Forms.RadioButton();
            this.TabPage6 = new global::System.Windows.Forms.TabPage();
            this.Label6 = new global::System.Windows.Forms.Label();
            this.GroupBox13 = new global::System.Windows.Forms.GroupBox();
            this.udForceLevel = new global::System.Windows.Forms.NumericUpDown();
            this.Label38 = new global::System.Windows.Forms.Label();
            this.GroupBox10 = new global::System.Windows.Forms.GroupBox();
            this.btnBaseReset = new global::System.Windows.Forms.Button();
            this.Label14 = new global::System.Windows.Forms.Label();
            this.udBaseToHit = new global::System.Windows.Forms.NumericUpDown();
            this.Label13 = new global::System.Windows.Forms.Label();
            this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
            this.Label12 = new global::System.Windows.Forms.Label();
            this.udExLow = new global::System.Windows.Forms.NumericUpDown();
            this.Label11 = new global::System.Windows.Forms.Label();
            this.Label5 = new global::System.Windows.Forms.Label();
            this.udExHigh = new global::System.Windows.Forms.NumericUpDown();
            this.TabPage4 = new global::System.Windows.Forms.TabPage();
            this.GroupBox12 = new global::System.Windows.Forms.GroupBox();
            this.fcReset = new global::System.Windows.Forms.Button();
            this.fcSet = new global::System.Windows.Forms.Button();
            this.fcNotes = new global::System.Windows.Forms.TextBox();
            this.fcDelete = new global::System.Windows.Forms.Button();
            this.fcAdd = new global::System.Windows.Forms.Button();
            this.fcName = new global::System.Windows.Forms.TextBox();
            this.fcWSTab = new global::System.Windows.Forms.RadioButton();
            this.fcWSSpace = new global::System.Windows.Forms.RadioButton();
            this.fcUnderlineOff = new global::System.Windows.Forms.TextBox();
            this.fcUnderlineOn = new global::System.Windows.Forms.TextBox();
            this.Label32 = new global::System.Windows.Forms.Label();
            this.fcItalicOff = new global::System.Windows.Forms.TextBox();
            this.fcItalicOn = new global::System.Windows.Forms.TextBox();
            this.Label31 = new global::System.Windows.Forms.Label();
            this.fcBoldOff = new global::System.Windows.Forms.TextBox();
            this.fcBoldOn = new global::System.Windows.Forms.TextBox();
            this.Label30 = new global::System.Windows.Forms.Label();
            this.fcTextOff = new global::System.Windows.Forms.TextBox();
            this.fcTextOn = new global::System.Windows.Forms.TextBox();
            this.Label29 = new global::System.Windows.Forms.Label();
            this.Label28 = new global::System.Windows.Forms.Label();
            this.Label27 = new global::System.Windows.Forms.Label();
            this.fcColorOff = new global::System.Windows.Forms.TextBox();
            this.fcColorOn = new global::System.Windows.Forms.TextBox();
            this.Label26 = new global::System.Windows.Forms.Label();
            this.fcList = new global::System.Windows.Forms.ListBox();
            this.Label25 = new global::System.Windows.Forms.Label();
            this.Label24 = new global::System.Windows.Forms.Label();
            this.Label33 = new global::System.Windows.Forms.Label();
            this.GroupBox11 = new global::System.Windows.Forms.GroupBox();
            this.csReset = new global::System.Windows.Forms.Button();
            this.csBtnEdit = new global::System.Windows.Forms.Button();
            this.csDelete = new global::System.Windows.Forms.Button();
            this.csAdd = new global::System.Windows.Forms.Button();
            this.csList = new global::System.Windows.Forms.ListBox();
            this.TabPage5 = new global::System.Windows.Forms.TabPage();
            this.btnSaveFolderReset = new global::System.Windows.Forms.Button();
            this.lblSaveFolder = new global::System.Windows.Forms.Label();
            this.btnSaveFolder = new global::System.Windows.Forms.Button();
            this.chkLoadLastFile = new global::System.Windows.Forms.CheckBox();
            this.Label1 = new global::System.Windows.Forms.Label();
            this.GroupBox16 = new global::System.Windows.Forms.GroupBox();
            this.btnForceUpdate = new global::System.Windows.Forms.Button();
            this.Label19 = new global::System.Windows.Forms.Label();
            this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
            this.btnUpdatePathReset = new global::System.Windows.Forms.Button();
            this.Label2 = new global::System.Windows.Forms.Label();
            this.txtUpdatePath = new global::System.Windows.Forms.TextBox();
            this.Label37 = new global::System.Windows.Forms.Label();
            this.Label34 = new global::System.Windows.Forms.Label();
            this.btnUpdate = new global::System.Windows.Forms.Button();
            this.chkUpdates = new global::System.Windows.Forms.CheckBox();
            this.TabPage1 = new global::System.Windows.Forms.TabPage();
            this.Label15 = new global::System.Windows.Forms.Label();
            this.Label10 = new global::System.Windows.Forms.Label();
            this.cmbAction = new global::System.Windows.Forms.ComboBox();
            this.GroupBox9 = new global::System.Windows.Forms.GroupBox();
            this.lblExample = new global::System.Windows.Forms.Label();
            this.GroupBox7 = new global::System.Windows.Forms.GroupBox();
            this.listScenarios = new global::System.Windows.Forms.ListBox();
            this.chkColourPrint = new global::System.Windows.Forms.CheckBox();
            this.myTip = new global::System.Windows.Forms.ToolTip(this.components);
            this.cPicker = new global::System.Windows.Forms.ColorDialog();
            this.fbdSave = new global::System.Windows.Forms.FolderBrowserDialog();
            this.TeamSize = new global::System.Windows.Forms.NumericUpDown();
            this.Label16 = new global::System.Windows.Forms.Label();
            this.TabControl1.SuspendLayout();
            this.TabPage3.SuspendLayout();
            this.GroupBox17.SuspendLayout();
            this.udStatSize.BeginInit();
            this.udRTFSize.BeginInit();
            this.GroupBox5.SuspendLayout();
            this.GroupBox14.SuspendLayout();
            this.udIOLevel.BeginInit();
            this.GroupBox3.SuspendLayout();
            this.TabPage2.SuspendLayout();
            this.GroupBox2.SuspendLayout();
            this.GroupBox15.SuspendLayout();
            this.GroupBox8.SuspendLayout();
            this.GroupBox6.SuspendLayout();
            this.TabPage6.SuspendLayout();
            this.GroupBox13.SuspendLayout();
            this.udForceLevel.BeginInit();
            this.GroupBox10.SuspendLayout();
            this.udBaseToHit.BeginInit();
            this.GroupBox4.SuspendLayout();
            this.udExLow.BeginInit();
            this.udExHigh.BeginInit();
            this.TabPage4.SuspendLayout();
            this.GroupBox12.SuspendLayout();
            this.GroupBox11.SuspendLayout();
            this.TabPage5.SuspendLayout();
            this.GroupBox16.SuspendLayout();
            this.GroupBox1.SuspendLayout();
            this.TabPage1.SuspendLayout();
            this.GroupBox9.SuspendLayout();
            this.GroupBox7.SuspendLayout();
            this.TeamSize.BeginInit();
            base.SuspendLayout();
            this.btnOK.DialogResult = global::System.Windows.Forms.DialogResult.OK;
            global::System.Drawing.Point point = new global::System.Drawing.Point(504, 360);
            this.btnOK.Location = point;
            this.btnOK.Name = "btnOK";
            global::System.Drawing.Size size = new global::System.Drawing.Size(75, 28);
            this.btnOK.Size = size;
            this.btnOK.TabIndex = 59;
            this.btnOK.Text = "OK";
            this.btnCancel.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
            point = new global::System.Drawing.Point(408, 360);
            this.btnCancel.Location = point;
            this.btnCancel.Name = "btnCancel";
            size = new global::System.Drawing.Size(75, 28);
            this.btnCancel.Size = size;
            this.btnCancel.TabIndex = 60;
            this.btnCancel.Text = "Cancel";
            this.TabControl1.Controls.Add(this.TabPage3);
            this.TabControl1.Controls.Add(this.TabPage2);
            this.TabControl1.Controls.Add(this.TabPage6);
            this.TabControl1.Controls.Add(this.TabPage4);
            this.TabControl1.Controls.Add(this.TabPage5);
            this.TabControl1.Controls.Add(this.TabPage1);
            point = new global::System.Drawing.Point(0, 0);
            this.TabControl1.Location = point;
            this.TabControl1.Name = "TabControl1";
            this.TabControl1.SelectedIndex = 0;
            size = new global::System.Drawing.Size(638, 352);
            this.TabControl1.Size = size;
            this.TabControl1.TabIndex = 0;
            this.TabPage3.Controls.Add(this.chkShowAlphaPopup);
            this.TabPage3.Controls.Add(this.chkNoTips);
            this.TabPage3.Controls.Add(this.chkMiddle);
            this.TabPage3.Controls.Add(this.GroupBox17);
            this.TabPage3.Controls.Add(this.chkIOPrintLevels);
            this.TabPage3.Controls.Add(this.GroupBox5);
            this.TabPage3.Controls.Add(this.GroupBox14);
            this.TabPage3.Controls.Add(this.GroupBox3);
            point = new global::System.Drawing.Point(4, 23);
            this.TabPage3.Location = point;
            this.TabPage3.Name = "TabPage3";
            size = new global::System.Drawing.Size(700, 325);
            this.TabPage3.Size = size;
            this.TabPage3.TabIndex = 2;
            this.TabPage3.Text = "Enhancements & View";
            this.TabPage3.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(434, 285);
            this.chkShowAlphaPopup.Location = point;
            this.chkShowAlphaPopup.Name = "chkShowAlphaPopup";
            size = new global::System.Drawing.Size(190, 18);
            this.chkShowAlphaPopup.Size = size;
            this.chkShowAlphaPopup.TabIndex = 79;
            this.chkShowAlphaPopup.Text = "Include Alpha buffs in popups";
            point = new global::System.Drawing.Point(434, 304);
            this.chkNoTips.Location = point;
            this.chkNoTips.Name = "chkNoTips";
            size = new global::System.Drawing.Size(141, 18);
            this.chkNoTips.Size = size;
            this.chkNoTips.TabIndex = 78;
            this.chkNoTips.Text = "No Tooltips";
            this.chkNoTips.Visible = false;
            point = new global::System.Drawing.Point(206, 304);
            this.chkMiddle.Location = point;
            this.chkMiddle.Name = "chkMiddle";
            size = new global::System.Drawing.Size(222, 18);
            this.chkMiddle.Size = size;
            this.chkMiddle.TabIndex = 77;
            this.chkMiddle.Text = "Middle-Click repeats last enhancement";
            this.GroupBox17.Controls.Add(this.chkColorInherent);
            this.GroupBox17.Controls.Add(this.chkHighVis);
            this.GroupBox17.Controls.Add(this.Label36);
            this.GroupBox17.Controls.Add(this.chkStatBold);
            this.GroupBox17.Controls.Add(this.chkTextBold);
            this.GroupBox17.Controls.Add(this.btnFontColour);
            this.GroupBox17.Controls.Add(this.Label22);
            this.GroupBox17.Controls.Add(this.chkVillainColour);
            this.GroupBox17.Controls.Add(this.Label21);
            this.GroupBox17.Controls.Add(this.udStatSize);
            this.GroupBox17.Controls.Add(this.udRTFSize);
            point = new global::System.Drawing.Point(196, 136);
            this.GroupBox17.Location = point;
            this.GroupBox17.Name = "GroupBox17";
            size = new global::System.Drawing.Size(380, 143);
            this.GroupBox17.Size = size;
            this.GroupBox17.TabIndex = 76;
            this.GroupBox17.TabStop = false;
            this.GroupBox17.Text = "Font Size/Colors:";
            point = new global::System.Drawing.Point(10, 118);
            this.chkColorInherent.Location = point;
            this.chkColorInherent.Name = "chkColorInherent";
            size = new global::System.Drawing.Size(222, 20);
            this.chkColorInherent.Size = size;
            this.chkColorInherent.TabIndex = 70;
            this.chkColorInherent.Text = "Use alternate colors for inherents";
            this.myTip.SetToolTip(this.chkColorInherent, "Draws villain builds in red rather than blue.");
            point = new global::System.Drawing.Point(10, 74);
            this.chkHighVis.Location = point;
            this.chkHighVis.Name = "chkHighVis";
            size = new global::System.Drawing.Size(222, 20);
            this.chkHighVis.Size = size;
            this.chkHighVis.TabIndex = 69;
            this.chkHighVis.Text = "Use High-Visiblity text on the build view";
            this.myTip.SetToolTip(this.chkHighVis, "Draw white text with a black outline on the build view (power bars on the right of the screen)");
            point = new global::System.Drawing.Point(141, 9);
            this.Label36.Location = point;
            this.Label36.Name = "Label36";
            size = new global::System.Drawing.Size(39, 16);
            this.Label36.Size = size;
            this.Label36.TabIndex = 64;
            this.Label36.Text = "Bold";
            this.Label36.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.chkStatBold.AutoSize = true;
            point = new global::System.Drawing.Point(150, 51);
            this.chkStatBold.Location = point;
            this.chkStatBold.Name = "chkStatBold";
            size = new global::System.Drawing.Size(15, 14);
            this.chkStatBold.Size = size;
            this.chkStatBold.TabIndex = 63;
            this.chkStatBold.UseVisualStyleBackColor = true;
            this.chkTextBold.AutoSize = true;
            point = new global::System.Drawing.Point(150, 26);
            this.chkTextBold.Location = point;
            this.chkTextBold.Name = "chkTextBold";
            size = new global::System.Drawing.Size(15, 14);
            this.chkTextBold.Size = size;
            this.chkTextBold.TabIndex = 62;
            this.chkTextBold.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(200, 19);
            this.btnFontColour.Location = point;
            this.btnFontColour.Name = "btnFontColour";
            size = new global::System.Drawing.Size(172, 27);
            this.btnFontColour.Size = size;
            this.btnFontColour.TabIndex = 61;
            this.btnFontColour.Text = "Set Colors...";
            this.btnFontColour.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(7, 48);
            this.Label22.Location = point;
            this.Label22.Name = "Label22";
            size = new global::System.Drawing.Size(78, 20);
            this.Label22.Size = size;
            this.Label22.TabIndex = 60;
            this.Label22.Text = "Stats/Powers:";
            this.Label22.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(10, 96);
            this.chkVillainColour.Location = point;
            this.chkVillainColour.Name = "chkVillainColour";
            size = new global::System.Drawing.Size(222, 20);
            this.chkVillainColour.Size = size;
            this.chkVillainColour.TabIndex = 68;
            this.chkVillainColour.Text = "Use alternate colors for villains";
            this.myTip.SetToolTip(this.chkVillainColour, "Draws villain builds in red rather than blue.");
            point = new global::System.Drawing.Point(7, 23);
            this.Label21.Location = point;
            this.Label21.Name = "Label21";
            size = new global::System.Drawing.Size(78, 20);
            this.Label21.Size = size;
            this.Label21.TabIndex = 59;
            this.Label21.Text = "Info Tab Text:";
            this.Label21.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.udStatSize.DecimalPlaces = 2;
            point = new global::System.Drawing.Point(87, 48);
            this.udStatSize.Location = point;
            int[] array = new int[4];
            array[0] = 14;
            decimal num = new decimal(array);
            this.udStatSize.Maximum = num;
            array = new int[4];
            array[0] = 6;
            num = new decimal(array);
            this.udStatSize.Minimum = num;
            this.udStatSize.Name = "udStatSize";
            size = new global::System.Drawing.Size(52, 20);
            this.udStatSize.Size = size;
            this.udStatSize.TabIndex = 1;
            num = new decimal(new int[]
            {
                825,
                0,
                0,
                131072
            });
            this.udStatSize.Value = num;
            point = new global::System.Drawing.Point(87, 22);
            this.udRTFSize.Location = point;
            array = new int[4];
            array[0] = 14;
            num = new decimal(array);
            this.udRTFSize.Maximum = num;
            array = new int[4];
            array[0] = 6;
            num = new decimal(array);
            this.udRTFSize.Minimum = num;
            this.udRTFSize.Name = "udRTFSize";
            size = new global::System.Drawing.Size(52, 20);
            this.udRTFSize.Size = size;
            this.udRTFSize.TabIndex = 0;
            array = new int[4];
            array[0] = 8;
            num = new decimal(array);
            this.udRTFSize.Value = num;
            point = new global::System.Drawing.Point(207, 285);
            this.chkIOPrintLevels.Location = point;
            this.chkIOPrintLevels.Name = "chkIOPrintLevels";
            size = new global::System.Drawing.Size(221, 18);
            this.chkIOPrintLevels.Size = size;
            this.chkIOPrintLevels.TabIndex = 75;
            this.chkIOPrintLevels.Text = "Display Invention levels in printed builds";
            this.GroupBox5.Controls.Add(this.rbGraphSimple);
            this.GroupBox5.Controls.Add(this.rbGraphStacked);
            this.GroupBox5.Controls.Add(this.rbGraphTwoLine);
            point = new global::System.Drawing.Point(388, 4);
            this.GroupBox5.Location = point;
            this.GroupBox5.Name = "GroupBox5";
            size = new global::System.Drawing.Size(188, 125);
            this.GroupBox5.Size = size;
            this.GroupBox5.TabIndex = 72;
            this.GroupBox5.TabStop = false;
            this.GroupBox5.Text = "Damage Graph Style:";
            point = new global::System.Drawing.Point(6, 89);
            this.rbGraphSimple.Location = point;
            this.rbGraphSimple.Name = "rbGraphSimple";
            size = new global::System.Drawing.Size(164, 32);
            this.rbGraphSimple.Size = size;
            this.rbGraphSimple.TabIndex = 5;
            this.rbGraphSimple.Text = "Base against Enhanced";
            this.myTip.SetToolTip(this.rbGraphSimple, "This graph type doesn't reflect the max damage potential of other powers.");
            point = new global::System.Drawing.Point(6, 53);
            this.rbGraphStacked.Location = point;
            this.rbGraphStacked.Name = "rbGraphStacked";
            size = new global::System.Drawing.Size(164, 32);
            this.rbGraphStacked.Size = size;
            this.rbGraphStacked.TabIndex = 4;
            this.rbGraphStacked.Text = "Base + Enhanced (stacked) against Max Enhancable";
            this.myTip.SetToolTip(this.rbGraphStacked, "'Max Enhacable' is damage if slotted with 6 +3 damage enhancements.");
            this.rbGraphTwoLine.Checked = true;
            point = new global::System.Drawing.Point(6, 17);
            this.rbGraphTwoLine.Location = point;
            this.rbGraphTwoLine.Name = "rbGraphTwoLine";
            size = new global::System.Drawing.Size(164, 32);
            this.rbGraphTwoLine.Size = size;
            this.rbGraphTwoLine.TabIndex = 3;
            this.rbGraphTwoLine.TabStop = true;
            this.rbGraphTwoLine.Text = "Base / Enhanced against Max Enhancable (Default)";
            this.myTip.SetToolTip(this.rbGraphTwoLine, "The blue bar will indicate base damage, the yellow bar will indicate enhanced damage.");
            this.GroupBox14.Controls.Add(this.chkIOLevel);
            this.GroupBox14.Controls.Add(this.btnIOReset);
            this.GroupBox14.Controls.Add(this.Label40);
            this.GroupBox14.Controls.Add(this.udIOLevel);
            point = new global::System.Drawing.Point(196, 4);
            this.GroupBox14.Location = point;
            this.GroupBox14.Name = "GroupBox14";
            size = new global::System.Drawing.Size(188, 125);
            this.GroupBox14.Size = size;
            this.GroupBox14.TabIndex = 69;
            this.GroupBox14.TabStop = false;
            this.GroupBox14.Text = "Inventions:";
            point = new global::System.Drawing.Point(8, 44);
            this.chkIOLevel.Location = point;
            this.chkIOLevel.Name = "chkIOLevel";
            size = new global::System.Drawing.Size(172, 24);
            this.chkIOLevel.Size = size;
            this.chkIOLevel.TabIndex = 60;
            this.chkIOLevel.Text = "Display IO Levels";
            this.myTip.SetToolTip(this.chkIOLevel, "Show the level of Inventions in the build view");
            point = new global::System.Drawing.Point(8, 72);
            this.btnIOReset.Location = point;
            this.btnIOReset.Name = "btnIOReset";
            size = new global::System.Drawing.Size(172, 44);
            this.btnIOReset.Size = size;
            this.btnIOReset.TabIndex = 59;
            this.btnIOReset.Text = "Set All IO and SetO levels to default";
            point = new global::System.Drawing.Point(8, 20);
            this.Label40.Location = point;
            this.Label40.Name = "Label40";
            size = new global::System.Drawing.Size(96, 20);
            this.Label40.Size = size;
            this.Label40.TabIndex = 58;
            this.Label40.Text = "Default IO Level:";
            this.Label40.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(108, 20);
            this.udIOLevel.Location = point;
            array = new int[4];
            array[0] = 50;
            num = new decimal(array);
            this.udIOLevel.Maximum = num;
            array = new int[4];
            array[0] = 10;
            num = new decimal(array);
            this.udIOLevel.Minimum = num;
            this.udIOLevel.Name = "udIOLevel";
            size = new global::System.Drawing.Size(72, 20);
            this.udIOLevel.Size = size;
            this.udIOLevel.TabIndex = 57;
            this.myTip.SetToolTip(this.udIOLevel, "Inventions will be placed at this level by default. You can override the default by typing a level number in the picker.");
            array = new int[4];
            array[0] = 50;
            num = new decimal(array);
            this.udIOLevel.Value = num;
            this.GroupBox3.Controls.Add(this.chkRelSignOnly);
            this.GroupBox3.Controls.Add(this.Label3);
            this.GroupBox3.Controls.Add(this.optTO);
            this.GroupBox3.Controls.Add(this.optDO);
            this.GroupBox3.Controls.Add(this.optSO);
            this.GroupBox3.Controls.Add(this.optEnh);
            this.GroupBox3.Controls.Add(this.cbEnhLevel);
            this.GroupBox3.Controls.Add(this.Label4);
            point = new global::System.Drawing.Point(4, 4);
            this.GroupBox3.Location = point;
            this.GroupBox3.Name = "GroupBox3";
            size = new global::System.Drawing.Size(184, 301);
            this.GroupBox3.Size = size;
            this.GroupBox3.TabIndex = 62;
            this.GroupBox3.TabStop = false;
            this.GroupBox3.Text = "Regular Enhancements:";
            point = new global::System.Drawing.Point(11, 252);
            this.chkRelSignOnly.Location = point;
            this.chkRelSignOnly.Name = "chkRelSignOnly";
            size = new global::System.Drawing.Size(167, 43);
            this.chkRelSignOnly.Size = size;
            this.chkRelSignOnly.TabIndex = 69;
            this.chkRelSignOnly.Text = "Show signs only for relative levels ('++' rather than '+2')";
            this.myTip.SetToolTip(this.chkRelSignOnly, "Draws villain builds in red rather than blue.");
            point = new global::System.Drawing.Point(6, 142);
            this.Label3.Location = point;
            this.Label3.Name = "Label3";
            size = new global::System.Drawing.Size(172, 79);
            this.Label3.Size = size;
            this.Label3.TabIndex = 59;
            this.Label3.Text = "Default Relative Level:\r\n(Ehancements can function up to five levels above or three below that of the character.)";
            this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.optTO.Appearance = global::System.Windows.Forms.Appearance.Button;
            this.optTO.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
            this.optTO.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("optTO.Image");
            point = new global::System.Drawing.Point(24, 74);
            this.optTO.Location = point;
            this.optTO.Name = "optTO";
            size = new global::System.Drawing.Size(44, 44);
            this.optTO.Size = size;
            this.optTO.TabIndex = 48;
            this.optTO.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.myTip.SetToolTip(this.optTO, "Training enhancements are the weakest kind.");
            this.optDO.Appearance = global::System.Windows.Forms.Appearance.Button;
            this.optDO.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
            this.optDO.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("optDO.Image");
            point = new global::System.Drawing.Point(72, 74);
            this.optDO.Location = point;
            this.optDO.Name = "optDO";
            size = new global::System.Drawing.Size(44, 44);
            this.optDO.Size = size;
            this.optDO.TabIndex = 49;
            this.optDO.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.myTip.SetToolTip(this.optDO, "Dual Origin enhancements can be bought from level 12 onwards.");
            this.optSO.Appearance = global::System.Windows.Forms.Appearance.Button;
            this.optSO.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
            this.optSO.Checked = true;
            this.optSO.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("optSO.Image");
            point = new global::System.Drawing.Point(120, 74);
            this.optSO.Location = point;
            this.optSO.Name = "optSO";
            size = new global::System.Drawing.Size(44, 44);
            this.optSO.Size = size;
            this.optSO.TabIndex = 50;
            this.optSO.TabStop = true;
            this.optSO.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.myTip.SetToolTip(this.optSO, "Single Origin enhancements are the most powerful kind, and can be bought from level 22.");
            this.optEnh.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.optEnh.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(21, 121);
            this.optEnh.Location = point;
            this.optEnh.Name = "optEnh";
            size = new global::System.Drawing.Size(143, 16);
            this.optEnh.Size = size;
            this.optEnh.TabIndex = 52;
            this.optEnh.Text = "Single Origin";
            this.optEnh.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.cbEnhLevel.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbEnhLevel.Items.AddRange(new object[]
            {
                "None (Enh. has no effect)",
                "-3 Levels",
                "-2 Levels",
                "-1 Level",
                "Even Level",
                "+1 Level",
                "+2 Levels",
                "+3 Levels"
            });
            point = new global::System.Drawing.Point(9, 224);
            this.cbEnhLevel.Location = point;
            this.cbEnhLevel.Name = "cbEnhLevel";
            size = new global::System.Drawing.Size(167, 22);
            this.cbEnhLevel.Size = size;
            this.cbEnhLevel.TabIndex = 53;
            this.cbEnhLevel.Tag = "";
            this.myTip.SetToolTip(this.cbEnhLevel, "This is the relative level of the enhancements in relation to your own. ");
            point = new global::System.Drawing.Point(6, 18);
            this.Label4.Location = point;
            this.Label4.Name = "Label4";
            size = new global::System.Drawing.Size(172, 50);
            this.Label4.Size = size;
            this.Label4.TabIndex = 58;
            this.Label4.Text = "Default Enhancement Type:\r\n(This does not affect Inventions or Special enhancements)";
            this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.TabPage2.Controls.Add(this.Label16);
            this.TabPage2.Controls.Add(this.TeamSize);
            this.TabPage2.Controls.Add(this.GroupBox2);
            this.TabPage2.Controls.Add(this.chkUseArcanaTime);
            this.TabPage2.Controls.Add(this.GroupBox15);
            this.TabPage2.Controls.Add(this.GroupBox8);
            this.TabPage2.Controls.Add(this.GroupBox6);
            point = new global::System.Drawing.Point(4, 23);
            this.TabPage2.Location = point;
            this.TabPage2.Name = "TabPage2";
            size = new global::System.Drawing.Size(630, 325);
            this.TabPage2.Size = size;
            this.TabPage2.TabIndex = 1;
            this.TabPage2.Text = "Effects & Maths";
            this.TabPage2.UseVisualStyleBackColor = true;
            this.GroupBox2.Controls.Add(this.clbSuppression);
            this.GroupBox2.Controls.Add(this.Label8);
            point = new global::System.Drawing.Point(517, 4);
            this.GroupBox2.Location = point;
            this.GroupBox2.Name = "GroupBox2";
            size = new global::System.Drawing.Size(107, 283);
            this.GroupBox2.Size = size;
            this.GroupBox2.TabIndex = 69;
            this.GroupBox2.TabStop = false;
            this.GroupBox2.Text = "Suppression";
            this.clbSuppression.CheckOnClick = true;
            this.clbSuppression.FormattingEnabled = true;
            point = new global::System.Drawing.Point(9, 104);
            this.clbSuppression.Location = point;
            this.clbSuppression.Name = "clbSuppression";
            size = new global::System.Drawing.Size(92, 169);
            this.clbSuppression.Size = size;
            this.clbSuppression.TabIndex = 9;
            point = new global::System.Drawing.Point(6, 17);
            this.Label8.Location = point;
            this.Label8.Name = "Label8";
            size = new global::System.Drawing.Size(95, 86);
            this.Label8.Size = size;
            this.Label8.TabIndex = 65;
            this.Label8.Text = "Some effects are suppressed on specific conditions. You can enable those conditions here.";
            point = new global::System.Drawing.Point(15, 294);
            this.chkUseArcanaTime.Location = point;
            this.chkUseArcanaTime.Name = "chkUseArcanaTime";
            size = new global::System.Drawing.Size(204, 22);
            this.chkUseArcanaTime.Size = size;
            this.chkUseArcanaTime.TabIndex = 66;
            this.chkUseArcanaTime.Text = "Use ArcanaTime for Animation Times";
            this.myTip.SetToolTip(this.chkUseArcanaTime, "Displays all cast times in ArcanaTime, the real time all animations take due to server clock ticks.");
            this.GroupBox15.Controls.Add(this.Label20);
            this.GroupBox15.Controls.Add(this.chkSetBonus);
            this.GroupBox15.Controls.Add(this.chkIOEffects);
            point = new global::System.Drawing.Point(316, 166);
            this.GroupBox15.Location = point;
            this.GroupBox15.Name = "GroupBox15";
            size = new global::System.Drawing.Size(195, 121);
            this.GroupBox15.Size = size;
            this.GroupBox15.TabIndex = 68;
            this.GroupBox15.TabStop = false;
            this.GroupBox15.Text = "Invention Effects:";
            point = new global::System.Drawing.Point(6, 17);
            this.Label20.Location = point;
            this.Label20.Name = "Label20";
            size = new global::System.Drawing.Size(179, 49);
            this.Label20.Size = size;
            this.Label20.TabIndex = 65;
            this.Label20.Text = "The effects of set bonusses and special IO enhancements can be included when stats are calculated.";
            point = new global::System.Drawing.Point(11, 93);
            this.chkSetBonus.Location = point;
            this.chkSetBonus.Name = "chkSetBonus";
            size = new global::System.Drawing.Size(169, 22);
            this.chkSetBonus.Size = size;
            this.chkSetBonus.TabIndex = 64;
            this.chkSetBonus.Text = "Include Set Bonus effects\r\n";
            this.myTip.SetToolTip(this.chkSetBonus, "Add set bonus effects to the totals view.");
            point = new global::System.Drawing.Point(11, 69);
            this.chkIOEffects.Location = point;
            this.chkIOEffects.Name = "chkIOEffects";
            size = new global::System.Drawing.Size(169, 22);
            this.chkIOEffects.Size = size;
            this.chkIOEffects.TabIndex = 63;
            this.chkIOEffects.Text = "Include Enhancement effects";
            this.myTip.SetToolTip(this.chkIOEffects, "Some enhancments have power effects, such as minor Psionic resistance. This effect can be added into the power.");
            this.GroupBox8.Controls.Add(this.rbChanceIgnore);
            this.GroupBox8.Controls.Add(this.rbChanceAverage);
            this.GroupBox8.Controls.Add(this.rbChanceMax);
            this.GroupBox8.Controls.Add(this.Label9);
            point = new global::System.Drawing.Point(4, 4);
            this.GroupBox8.Location = point;
            this.GroupBox8.Name = "GroupBox8";
            size = new global::System.Drawing.Size(507, 156);
            this.GroupBox8.Size = size;
            this.GroupBox8.TabIndex = 3;
            this.GroupBox8.TabStop = false;
            this.GroupBox8.Text = "Chance of Damage:";
            point = new global::System.Drawing.Point(221, 113);
            this.rbChanceIgnore.Location = point;
            this.rbChanceIgnore.Name = "rbChanceIgnore";
            size = new global::System.Drawing.Size(224, 20);
            this.rbChanceIgnore.Size = size;
            this.rbChanceIgnore.TabIndex = 8;
            this.rbChanceIgnore.Text = "Ignore Extra Damage (Show minimum)";
            this.rbChanceAverage.Checked = true;
            point = new global::System.Drawing.Point(11, 97);
            this.rbChanceAverage.Location = point;
            this.rbChanceAverage.Name = "rbChanceAverage";
            size = new global::System.Drawing.Size(204, 20);
            this.rbChanceAverage.Size = size;
            this.rbChanceAverage.TabIndex = 7;
            this.rbChanceAverage.TabStop = true;
            this.rbChanceAverage.Text = "Show Average (Damage x Chance)";
            point = new global::System.Drawing.Point(221, 83);
            this.rbChanceMax.Location = point;
            this.rbChanceMax.Name = "rbChanceMax";
            size = new global::System.Drawing.Size(204, 20);
            this.rbChanceMax.Size = size;
            this.rbChanceMax.TabIndex = 6;
            this.rbChanceMax.Text = "Show Max Possible Damage";
            point = new global::System.Drawing.Point(8, 16);
            this.Label9.Location = point;
            this.Label9.Name = "Label9";
            size = new global::System.Drawing.Size(499, 56);
            this.Label9.Size = size;
            this.Label9.TabIndex = 4;
            this.Label9.Text = componentResourceManager.GetString("Label9.Text");
            this.GroupBox6.Controls.Add(this.Label7);
            this.GroupBox6.Controls.Add(this.rbPvP);
            this.GroupBox6.Controls.Add(this.rbPvE);
            point = new global::System.Drawing.Point(8, 166);
            this.GroupBox6.Location = point;
            this.GroupBox6.Name = "GroupBox6";
            size = new global::System.Drawing.Size(301, 122);
            this.GroupBox6.Size = size;
            this.GroupBox6.TabIndex = 1;
            this.GroupBox6.TabStop = false;
            this.GroupBox6.Text = "Targets:";
            point = new global::System.Drawing.Point(8, 16);
            this.Label7.Location = point;
            this.Label7.Name = "Label7";
            size = new global::System.Drawing.Size(295, 54);
            this.Label7.Size = size;
            this.Label7.TabIndex = 2;
            this.Label7.Text = "Some powers  have different effects when used against players (Mez effects are a good example of this). Where a power has different effects, which should be displayed?";
            point = new global::System.Drawing.Point(11, 93);
            this.rbPvP.Location = point;
            this.rbPvP.Name = "rbPvP";
            size = new global::System.Drawing.Size(260, 20);
            this.rbPvP.Size = size;
            this.rbPvP.TabIndex = 1;
            this.rbPvP.Text = "Show values for Players (PvP)";
            this.rbPvE.Checked = true;
            point = new global::System.Drawing.Point(11, 73);
            this.rbPvE.Location = point;
            this.rbPvE.Name = "rbPvE";
            size = new global::System.Drawing.Size(260, 20);
            this.rbPvE.Size = size;
            this.rbPvE.TabIndex = 0;
            this.rbPvE.TabStop = true;
            this.rbPvE.Text = "Show values for Critters (PvE)";
            this.TabPage6.Controls.Add(this.Label6);
            this.TabPage6.Controls.Add(this.GroupBox13);
            this.TabPage6.Controls.Add(this.GroupBox10);
            this.TabPage6.Controls.Add(this.GroupBox4);
            point = new global::System.Drawing.Point(4, 23);
            this.TabPage6.Location = point;
            this.TabPage6.Name = "TabPage6";
            size = new global::System.Drawing.Size(630, 325);
            this.TabPage6.Size = size;
            this.TabPage6.TabIndex = 5;
            this.TabPage6.Text = "Exemping & Base Values";
            this.TabPage6.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(401, 85);
            this.Label6.Location = point;
            this.Label6.Name = "Label6";
            size = new global::System.Drawing.Size(169, 119);
            this.Label6.Size = size;
            this.Label6.TabIndex = 71;
            this.Label6.Text = "Exemplar and level-accurate scaling features will be added in the future!";
            this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.GroupBox13.Controls.Add(this.udForceLevel);
            this.GroupBox13.Controls.Add(this.Label38);
            this.GroupBox13.Enabled = false;
            point = new global::System.Drawing.Point(284, 4);
            this.GroupBox13.Location = point;
            this.GroupBox13.Name = "GroupBox13";
            size = new global::System.Drawing.Size(96, 184);
            this.GroupBox13.Size = size;
            this.GroupBox13.TabIndex = 70;
            this.GroupBox13.TabStop = false;
            this.GroupBox13.Text = "Forced Level:";
            point = new global::System.Drawing.Point(8, 124);
            this.udForceLevel.Location = point;
            array = new int[4];
            array[0] = 50;
            num = new decimal(array);
            this.udForceLevel.Maximum = num;
            array = new int[4];
            array[0] = 1;
            num = new decimal(array);
            this.udForceLevel.Minimum = num;
            this.udForceLevel.Name = "udForceLevel";
            size = new global::System.Drawing.Size(80, 20);
            this.udForceLevel.Size = size;
            this.udForceLevel.TabIndex = 55;
            array = new int[4];
            array[0] = 50;
            num = new decimal(array);
            this.udForceLevel.Value = num;
            point = new global::System.Drawing.Point(4, 16);
            this.Label38.Location = point;
            this.Label38.Name = "Label38";
            size = new global::System.Drawing.Size(88, 100);
            this.Label38.Size = size;
            this.Label38.TabIndex = 1;
            this.Label38.Text = "Slots/Powers placed after this level won't be included in stats, and will be dimmed in the build view.";
            this.GroupBox10.Controls.Add(this.btnBaseReset);
            this.GroupBox10.Controls.Add(this.Label14);
            this.GroupBox10.Controls.Add(this.udBaseToHit);
            this.GroupBox10.Controls.Add(this.Label13);
            point = new global::System.Drawing.Point(4, 196);
            this.GroupBox10.Location = point;
            this.GroupBox10.Name = "GroupBox10";
            size = new global::System.Drawing.Size(376, 104);
            this.GroupBox10.Size = size;
            this.GroupBox10.TabIndex = 69;
            this.GroupBox10.TabStop = false;
            this.GroupBox10.Text = "Base Values:";
            point = new global::System.Drawing.Point(240, 76);
            this.btnBaseReset.Location = point;
            this.btnBaseReset.Name = "btnBaseReset";
            size = new global::System.Drawing.Size(120, 20);
            this.btnBaseReset.Size = size;
            this.btnBaseReset.TabIndex = 61;
            this.btnBaseReset.Text = "Reset Values";
            point = new global::System.Drawing.Point(147, 39);
            this.Label14.Location = point;
            this.Label14.Name = "Label14";
            size = new global::System.Drawing.Size(112, 20);
            this.Label14.Size = size;
            this.Label14.TabIndex = 58;
            this.Label14.Text = "Base ToHit:";
            this.Label14.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(263, 39);
            this.udBaseToHit.Location = point;
            array = new int[4];
            array[0] = 1;
            num = new decimal(array);
            this.udBaseToHit.Minimum = num;
            this.udBaseToHit.Name = "udBaseToHit";
            size = new global::System.Drawing.Size(88, 20);
            this.udBaseToHit.Size = size;
            this.udBaseToHit.TabIndex = 57;
            this.myTip.SetToolTip(this.udBaseToHit, "Chance of hitting a foe. Accuracy = (Base ToHit + Buffs) * Enhancements");
            array = new int[4];
            array[0] = 75;
            num = new decimal(array);
            this.udBaseToHit.Value = num;
            point = new global::System.Drawing.Point(8, 16);
            this.Label13.Location = point;
            this.Label13.Name = "Label13";
            size = new global::System.Drawing.Size(136, 84);
            this.Label13.Size = size;
            this.Label13.TabIndex = 0;
            this.Label13.Text = "These values are used as the base for stats calculation. They shouldn't ever need to be changed unless there's a change to the game.";
            this.GroupBox4.Controls.Add(this.Label12);
            this.GroupBox4.Controls.Add(this.udExLow);
            this.GroupBox4.Controls.Add(this.Label11);
            this.GroupBox4.Controls.Add(this.Label5);
            this.GroupBox4.Controls.Add(this.udExHigh);
            this.GroupBox4.Enabled = false;
            point = new global::System.Drawing.Point(4, 4);
            this.GroupBox4.Location = point;
            this.GroupBox4.Name = "GroupBox4";
            size = new global::System.Drawing.Size(276, 184);
            this.GroupBox4.Size = size;
            this.GroupBox4.TabIndex = 68;
            this.GroupBox4.TabStop = false;
            this.GroupBox4.Text = "Exemplar Level:";
            point = new global::System.Drawing.Point(8, 148);
            this.Label12.Location = point;
            this.Label12.Name = "Label12";
            size = new global::System.Drawing.Size(160, 20);
            this.Label12.Size = size;
            this.Label12.TabIndex = 58;
            this.Label12.Text = "Exemplared (Lower) Level:";
            this.Label12.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(172, 148);
            this.udExLow.Location = point;
            array = new int[4];
            array[0] = 50;
            num = new decimal(array);
            this.udExLow.Maximum = num;
            array = new int[4];
            array[0] = 1;
            num = new decimal(array);
            this.udExLow.Minimum = num;
            this.udExLow.Name = "udExLow";
            size = new global::System.Drawing.Size(88, 20);
            this.udExLow.Size = size;
            this.udExLow.TabIndex = 57;
            this.myTip.SetToolTip(this.udExLow, "Set the target exemplar level. Your enhancements will be calculated as though you are exemplared to this level, and their effect will be reduced accordingly");
            array = new int[4];
            array[0] = 50;
            num = new decimal(array);
            this.udExLow.Value = num;
            point = new global::System.Drawing.Point(8, 124);
            this.Label11.Location = point;
            this.Label11.Name = "Label11";
            size = new global::System.Drawing.Size(160, 20);
            this.Label11.Size = size;
            this.Label11.TabIndex = 56;
            this.Label11.Text = "Starting (Higher) Level:";
            this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(8, 16);
            this.Label5.Location = point;
            this.Label5.Name = "Label5";
            size = new global::System.Drawing.Size(264, 96);
            this.Label5.Size = size;
            this.Label5.TabIndex = 55;
            this.Label5.Text = componentResourceManager.GetString("Label5.Text");
            point = new global::System.Drawing.Point(172, 124);
            this.udExHigh.Location = point;
            array = new int[4];
            array[0] = 50;
            num = new decimal(array);
            this.udExHigh.Maximum = num;
            array = new int[4];
            array[0] = 1;
            num = new decimal(array);
            this.udExHigh.Minimum = num;
            this.udExHigh.Name = "udExHigh";
            size = new global::System.Drawing.Size(88, 20);
            this.udExHigh.Size = size;
            this.udExHigh.TabIndex = 54;
            this.myTip.SetToolTip(this.udExHigh, componentResourceManager.GetString("udExHigh.ToolTip"));
            array = new int[4];
            array[0] = 50;
            num = new decimal(array);
            this.udExHigh.Value = num;
            this.TabPage4.Controls.Add(this.GroupBox12);
            this.TabPage4.Controls.Add(this.GroupBox11);
            point = new global::System.Drawing.Point(4, 23);
            this.TabPage4.Location = point;
            this.TabPage4.Name = "TabPage4";
            size = new global::System.Drawing.Size(630, 325);
            this.TabPage4.Size = size;
            this.TabPage4.TabIndex = 3;
            this.TabPage4.Text = "Forum Export Settings";
            this.TabPage4.UseVisualStyleBackColor = true;
            this.GroupBox12.Controls.Add(this.fcReset);
            this.GroupBox12.Controls.Add(this.fcSet);
            this.GroupBox12.Controls.Add(this.fcNotes);
            this.GroupBox12.Controls.Add(this.fcDelete);
            this.GroupBox12.Controls.Add(this.fcAdd);
            this.GroupBox12.Controls.Add(this.fcName);
            this.GroupBox12.Controls.Add(this.fcWSTab);
            this.GroupBox12.Controls.Add(this.fcWSSpace);
            this.GroupBox12.Controls.Add(this.fcUnderlineOff);
            this.GroupBox12.Controls.Add(this.fcUnderlineOn);
            this.GroupBox12.Controls.Add(this.Label32);
            this.GroupBox12.Controls.Add(this.fcItalicOff);
            this.GroupBox12.Controls.Add(this.fcItalicOn);
            this.GroupBox12.Controls.Add(this.Label31);
            this.GroupBox12.Controls.Add(this.fcBoldOff);
            this.GroupBox12.Controls.Add(this.fcBoldOn);
            this.GroupBox12.Controls.Add(this.Label30);
            this.GroupBox12.Controls.Add(this.fcTextOff);
            this.GroupBox12.Controls.Add(this.fcTextOn);
            this.GroupBox12.Controls.Add(this.Label29);
            this.GroupBox12.Controls.Add(this.Label28);
            this.GroupBox12.Controls.Add(this.Label27);
            this.GroupBox12.Controls.Add(this.fcColorOff);
            this.GroupBox12.Controls.Add(this.fcColorOn);
            this.GroupBox12.Controls.Add(this.Label26);
            this.GroupBox12.Controls.Add(this.fcList);
            this.GroupBox12.Controls.Add(this.Label25);
            this.GroupBox12.Controls.Add(this.Label24);
            this.GroupBox12.Controls.Add(this.Label33);
            point = new global::System.Drawing.Point(180, 8);
            this.GroupBox12.Location = point;
            this.GroupBox12.Name = "GroupBox12";
            size = new global::System.Drawing.Size(392, 308);
            this.GroupBox12.Size = size;
            this.GroupBox12.TabIndex = 1;
            this.GroupBox12.TabStop = false;
            this.GroupBox12.Text = "Formatting Codes:";
            point = new global::System.Drawing.Point(16, 280);
            this.fcReset.Location = point;
            this.fcReset.Name = "fcReset";
            size = new global::System.Drawing.Size(124, 24);
            this.fcReset.Size = size;
            this.fcReset.TabIndex = 18;
            this.fcReset.Text = "Reset To Defaults";
            point = new global::System.Drawing.Point(8, 200);
            this.fcSet.Location = point;
            this.fcSet.Name = "fcSet";
            size = new global::System.Drawing.Size(136, 20);
            this.fcSet.Size = size;
            this.fcSet.TabIndex = 4;
            this.fcSet.Text = "Set New Name";
            point = new global::System.Drawing.Point(8, 228);
            this.fcNotes.Location = point;
            this.fcNotes.Multiline = true;
            this.fcNotes.Name = "fcNotes";
            size = new global::System.Drawing.Size(136, 48);
            this.fcNotes.Size = size;
            this.fcNotes.TabIndex = 5;
            point = new global::System.Drawing.Point(8, 148);
            this.fcDelete.Location = point;
            this.fcDelete.Name = "fcDelete";
            size = new global::System.Drawing.Size(64, 20);
            this.fcDelete.Size = size;
            this.fcDelete.TabIndex = 1;
            this.fcDelete.Text = "Delete";
            point = new global::System.Drawing.Point(80, 148);
            this.fcAdd.Location = point;
            this.fcAdd.Name = "fcAdd";
            size = new global::System.Drawing.Size(64, 20);
            this.fcAdd.Size = size;
            this.fcAdd.TabIndex = 2;
            this.fcAdd.Text = "Add";
            point = new global::System.Drawing.Point(8, 176);
            this.fcName.Location = point;
            this.fcName.Name = "fcName";
            size = new global::System.Drawing.Size(136, 20);
            this.fcName.Size = size;
            this.fcName.TabIndex = 3;
            point = new global::System.Drawing.Point(304, 196);
            this.fcWSTab.Location = point;
            this.fcWSTab.Name = "fcWSTab";
            size = new global::System.Drawing.Size(80, 20);
            this.fcWSTab.Size = size;
            this.fcWSTab.TabIndex = 17;
            this.fcWSTab.Text = "Tab";
            point = new global::System.Drawing.Point(220, 196);
            this.fcWSSpace.Location = point;
            this.fcWSSpace.Name = "fcWSSpace";
            size = new global::System.Drawing.Size(80, 20);
            this.fcWSSpace.Size = size;
            this.fcWSSpace.TabIndex = 16;
            this.fcWSSpace.Text = "Space";
            point = new global::System.Drawing.Point(324, 160);
            this.fcUnderlineOff.Location = point;
            this.fcUnderlineOff.Name = "fcUnderlineOff";
            size = new global::System.Drawing.Size(60, 20);
            this.fcUnderlineOff.Size = size;
            this.fcUnderlineOff.TabIndex = 15;
            point = new global::System.Drawing.Point(220, 160);
            this.fcUnderlineOn.Location = point;
            this.fcUnderlineOn.Name = "fcUnderlineOn";
            size = new global::System.Drawing.Size(100, 20);
            this.fcUnderlineOn.Size = size;
            this.fcUnderlineOn.TabIndex = 14;
            point = new global::System.Drawing.Point(148, 160);
            this.Label32.Location = point;
            this.Label32.Name = "Label32";
            size = new global::System.Drawing.Size(68, 20);
            this.Label32.Size = size;
            this.Label32.TabIndex = 30;
            this.Label32.Text = "Underline:";
            this.Label32.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(324, 136);
            this.fcItalicOff.Location = point;
            this.fcItalicOff.Name = "fcItalicOff";
            size = new global::System.Drawing.Size(60, 20);
            this.fcItalicOff.Size = size;
            this.fcItalicOff.TabIndex = 13;
            point = new global::System.Drawing.Point(220, 136);
            this.fcItalicOn.Location = point;
            this.fcItalicOn.Name = "fcItalicOn";
            size = new global::System.Drawing.Size(100, 20);
            this.fcItalicOn.Size = size;
            this.fcItalicOn.TabIndex = 12;
            point = new global::System.Drawing.Point(148, 136);
            this.Label31.Location = point;
            this.Label31.Name = "Label31";
            size = new global::System.Drawing.Size(68, 20);
            this.Label31.Size = size;
            this.Label31.TabIndex = 27;
            this.Label31.Text = "Italic:";
            this.Label31.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(324, 112);
            this.fcBoldOff.Location = point;
            this.fcBoldOff.Name = "fcBoldOff";
            size = new global::System.Drawing.Size(60, 20);
            this.fcBoldOff.Size = size;
            this.fcBoldOff.TabIndex = 11;
            point = new global::System.Drawing.Point(220, 112);
            this.fcBoldOn.Location = point;
            this.fcBoldOn.Name = "fcBoldOn";
            size = new global::System.Drawing.Size(100, 20);
            this.fcBoldOn.Size = size;
            this.fcBoldOn.TabIndex = 10;
            point = new global::System.Drawing.Point(148, 112);
            this.Label30.Location = point;
            this.Label30.Name = "Label30";
            size = new global::System.Drawing.Size(68, 20);
            this.Label30.Size = size;
            this.Label30.TabIndex = 24;
            this.Label30.Text = "Bold:";
            this.Label30.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(324, 88);
            this.fcTextOff.Location = point;
            this.fcTextOff.Name = "fcTextOff";
            size = new global::System.Drawing.Size(60, 20);
            this.fcTextOff.Size = size;
            this.fcTextOff.TabIndex = 9;
            point = new global::System.Drawing.Point(220, 88);
            this.fcTextOn.Location = point;
            this.fcTextOn.Name = "fcTextOn";
            size = new global::System.Drawing.Size(100, 20);
            this.fcTextOn.Size = size;
            this.fcTextOn.TabIndex = 8;
            point = new global::System.Drawing.Point(148, 88);
            this.Label29.Location = point;
            this.Label29.Name = "Label29";
            size = new global::System.Drawing.Size(68, 20);
            this.Label29.Size = size;
            this.Label29.TabIndex = 21;
            this.Label29.Text = "Code Block:";
            this.Label29.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(324, 44);
            this.Label28.Location = point;
            this.Label28.Name = "Label28";
            size = new global::System.Drawing.Size(60, 16);
            this.Label28.Size = size;
            this.Label28.TabIndex = 20;
            this.Label28.Text = "Off";
            this.Label28.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            point = new global::System.Drawing.Point(220, 44);
            this.Label27.Location = point;
            this.Label27.Name = "Label27";
            size = new global::System.Drawing.Size(100, 16);
            this.Label27.Size = size;
            this.Label27.TabIndex = 19;
            this.Label27.Text = "On";
            this.Label27.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            point = new global::System.Drawing.Point(324, 64);
            this.fcColorOff.Location = point;
            this.fcColorOff.Name = "fcColorOff";
            size = new global::System.Drawing.Size(60, 20);
            this.fcColorOff.Size = size;
            this.fcColorOff.TabIndex = 7;
            point = new global::System.Drawing.Point(220, 64);
            this.fcColorOn.Location = point;
            this.fcColorOn.Name = "fcColorOn";
            size = new global::System.Drawing.Size(100, 20);
            this.fcColorOn.Size = size;
            this.fcColorOn.TabIndex = 6;
            point = new global::System.Drawing.Point(148, 64);
            this.Label26.Location = point;
            this.Label26.Name = "Label26";
            size = new global::System.Drawing.Size(68, 20);
            this.Label26.Size = size;
            this.Label26.TabIndex = 16;
            this.Label26.Text = "Color:";
            this.Label26.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.fcList.ItemHeight = 14;
            point = new global::System.Drawing.Point(8, 40);
            this.fcList.Location = point;
            this.fcList.Name = "fcList";
            size = new global::System.Drawing.Size(136, 102);
            this.fcList.Size = size;
            this.fcList.TabIndex = 0;
            point = new global::System.Drawing.Point(148, 224);
            this.Label25.Location = point;
            this.Label25.Name = "Label25";
            size = new global::System.Drawing.Size(236, 76);
            this.Label25.Size = size;
            this.Label25.TabIndex = 14;
            this.Label25.Text = "When defining a formatting code which takes a value, such as a color tag, use %VAL% as a placeholder for the actual value, which will replace it when a build is exported.";
            this.Label25.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            point = new global::System.Drawing.Point(8, 16);
            this.Label24.Location = point;
            this.Label24.Name = "Label24";
            size = new global::System.Drawing.Size(344, 20);
            this.Label24.Size = size;
            this.Label24.TabIndex = 13;
            this.Label24.Text = "You can set the formatting codes available for Forum Export here.";
            point = new global::System.Drawing.Point(140, 196);
            this.Label33.Location = point;
            this.Label33.Name = "Label33";
            size = new global::System.Drawing.Size(76, 20);
            this.Label33.Size = size;
            this.Label33.TabIndex = 33;
            this.Label33.Text = "White Space:";
            this.Label33.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.GroupBox11.Controls.Add(this.csReset);
            this.GroupBox11.Controls.Add(this.csBtnEdit);
            this.GroupBox11.Controls.Add(this.csDelete);
            this.GroupBox11.Controls.Add(this.csAdd);
            this.GroupBox11.Controls.Add(this.csList);
            point = new global::System.Drawing.Point(12, 8);
            this.GroupBox11.Location = point;
            this.GroupBox11.Name = "GroupBox11";
            size = new global::System.Drawing.Size(160, 308);
            this.GroupBox11.Size = size;
            this.GroupBox11.TabIndex = 0;
            this.GroupBox11.TabStop = false;
            this.GroupBox11.Text = "Color Schemes:";
            point = new global::System.Drawing.Point(8, 280);
            this.csReset.Location = point;
            this.csReset.Name = "csReset";
            size = new global::System.Drawing.Size(144, 24);
            this.csReset.Size = size;
            this.csReset.TabIndex = 4;
            this.csReset.Text = "Reset To Defaults";
            point = new global::System.Drawing.Point(8, 242);
            this.csBtnEdit.Location = point;
            this.csBtnEdit.Name = "csBtnEdit";
            size = new global::System.Drawing.Size(144, 32);
            this.csBtnEdit.Size = size;
            this.csBtnEdit.TabIndex = 3;
            this.csBtnEdit.Text = "Edit...";
            point = new global::System.Drawing.Point(8, 216);
            this.csDelete.Location = point;
            this.csDelete.Name = "csDelete";
            size = new global::System.Drawing.Size(64, 20);
            this.csDelete.Size = size;
            this.csDelete.TabIndex = 1;
            this.csDelete.Text = "Delete";
            point = new global::System.Drawing.Point(88, 216);
            this.csAdd.Location = point;
            this.csAdd.Name = "csAdd";
            size = new global::System.Drawing.Size(64, 20);
            this.csAdd.Size = size;
            this.csAdd.TabIndex = 2;
            this.csAdd.Text = "Add";
            this.csList.ItemHeight = 14;
            point = new global::System.Drawing.Point(8, 20);
            this.csList.Location = point;
            this.csList.Name = "csList";
            size = new global::System.Drawing.Size(144, 186);
            this.csList.Size = size;
            this.csList.TabIndex = 0;
            this.TabPage5.Controls.Add(this.btnSaveFolderReset);
            this.TabPage5.Controls.Add(this.lblSaveFolder);
            this.TabPage5.Controls.Add(this.btnSaveFolder);
            this.TabPage5.Controls.Add(this.chkLoadLastFile);
            this.TabPage5.Controls.Add(this.Label1);
            this.TabPage5.Controls.Add(this.GroupBox16);
            this.TabPage5.Controls.Add(this.GroupBox1);
            point = new global::System.Drawing.Point(4, 23);
            this.TabPage5.Location = point;
            this.TabPage5.Name = "TabPage5";
            size = new global::System.Drawing.Size(630, 325);
            this.TabPage5.Size = size;
            this.TabPage5.TabIndex = 4;
            this.TabPage5.Text = "Updates & Paths";
            this.TabPage5.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(459, 298);
            this.btnSaveFolderReset.Location = point;
            this.btnSaveFolderReset.Name = "btnSaveFolderReset";
            size = new global::System.Drawing.Size(105, 22);
            this.btnSaveFolderReset.Size = size;
            this.btnSaveFolderReset.TabIndex = 64;
            this.btnSaveFolderReset.Text = "Reset to Default";
            this.btnSaveFolderReset.UseVisualStyleBackColor = true;
            this.lblSaveFolder.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(17, 270);
            this.lblSaveFolder.Location = point;
            this.lblSaveFolder.Name = "lblSaveFolder";
            size = new global::System.Drawing.Size(436, 22);
            this.lblSaveFolder.Size = size;
            this.lblSaveFolder.TabIndex = 63;
            this.lblSaveFolder.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            this.lblSaveFolder.UseMnemonic = false;
            point = new global::System.Drawing.Point(459, 270);
            this.btnSaveFolder.Location = point;
            this.btnSaveFolder.Name = "btnSaveFolder";
            size = new global::System.Drawing.Size(105, 22);
            this.btnSaveFolder.Size = size;
            this.btnSaveFolder.TabIndex = 62;
            this.btnSaveFolder.Text = "Browse...";
            this.btnSaveFolder.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(17, 295);
            this.chkLoadLastFile.Location = point;
            this.chkLoadLastFile.Name = "chkLoadLastFile";
            size = new global::System.Drawing.Size(156, 16);
            this.chkLoadLastFile.Size = size;
            this.chkLoadLastFile.TabIndex = 61;
            this.chkLoadLastFile.Text = "Load last file at startup";
            point = new global::System.Drawing.Point(5, 246);
            this.Label1.Location = point;
            this.Label1.Name = "Label1";
            size = new global::System.Drawing.Size(123, 24);
            this.Label1.Size = size;
            this.Label1.TabIndex = 8;
            this.Label1.Text = "Default Save Folder:";
            this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            this.GroupBox16.Controls.Add(this.btnForceUpdate);
            this.GroupBox16.Controls.Add(this.Label19);
            point = new global::System.Drawing.Point(417, 3);
            this.GroupBox16.Location = point;
            this.GroupBox16.Name = "GroupBox16";
            size = new global::System.Drawing.Size(153, 240);
            this.GroupBox16.Size = size;
            this.GroupBox16.TabIndex = 6;
            this.GroupBox16.TabStop = false;
            this.GroupBox16.Text = "Panic Button:";
            this.GroupBox16.Visible = false;
            point = new global::System.Drawing.Point(6, 157);
            this.btnForceUpdate.Location = point;
            this.btnForceUpdate.Name = "btnForceUpdate";
            size = new global::System.Drawing.Size(140, 44);
            this.btnForceUpdate.Size = size;
            this.btnForceUpdate.TabIndex = 5;
            this.btnForceUpdate.Text = "Force Database Re-Download";
            point = new global::System.Drawing.Point(5, 21);
            this.Label19.Location = point;
            this.Label19.Name = "Label19";
            size = new global::System.Drawing.Size(143, 117);
            this.Label19.Size = size;
            this.Label19.TabIndex = 7;
            this.Label19.Text = "If the database is damaged and not working properly, you can force the application to redownload the most recent version.";
            this.Label19.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.GroupBox1.Controls.Add(this.btnUpdatePathReset);
            this.GroupBox1.Controls.Add(this.Label2);
            this.GroupBox1.Controls.Add(this.txtUpdatePath);
            this.GroupBox1.Controls.Add(this.Label37);
            this.GroupBox1.Controls.Add(this.Label34);
            this.GroupBox1.Controls.Add(this.btnUpdate);
            this.GroupBox1.Controls.Add(this.chkUpdates);
            point = new global::System.Drawing.Point(8, 3);
            this.GroupBox1.Location = point;
            this.GroupBox1.Name = "GroupBox1";
            size = new global::System.Drawing.Size(403, 240);
            this.GroupBox1.Size = size;
            this.GroupBox1.TabIndex = 7;
            this.GroupBox1.TabStop = false;
            this.GroupBox1.Text = "Automatic Updates:";
            point = new global::System.Drawing.Point(142, 212);
            this.btnUpdatePathReset.Location = point;
            this.btnUpdatePathReset.Name = "btnUpdatePathReset";
            size = new global::System.Drawing.Size(119, 22);
            this.btnUpdatePathReset.Size = size;
            this.btnUpdatePathReset.TabIndex = 65;
            this.btnUpdatePathReset.Text = "Reset to Default";
            this.btnUpdatePathReset.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(6, 168);
            this.Label2.Location = point;
            this.Label2.Name = "Label2";
            size = new global::System.Drawing.Size(197, 20);
            this.Label2.Size = size;
            this.Label2.TabIndex = 10;
            this.Label2.Text = "Address of update information data:";
            this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(9, 191);
            this.txtUpdatePath.Location = point;
            this.txtUpdatePath.Name = "txtUpdatePath";
            size = new global::System.Drawing.Size(391, 20);
            this.txtUpdatePath.Size = size;
            this.txtUpdatePath.TabIndex = 9;
            point = new global::System.Drawing.Point(6, 87);
            this.Label37.Location = point;
            this.Label37.Name = "Label37";
            size = new global::System.Drawing.Size(384, 43);
            this.Label37.Size = size;
            this.Label37.TabIndex = 7;
            this.Label37.Text = "Please note that the availability of automatic updates may vary due to bandwidth use of the hosting site.";
            this.Label37.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            point = new global::System.Drawing.Point(6, 16);
            this.Label34.Location = point;
            this.Label34.Name = "Label34";
            size = new global::System.Drawing.Size(384, 41);
            this.Label34.Size = size;
            this.Label34.TabIndex = 5;
            this.Label34.Text = "The hero designer can automatically check for updates and download newer versions when it starts. This feature requires an internet connection.";
            this.Label34.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            point = new global::System.Drawing.Point(121, 133);
            this.btnUpdate.Location = point;
            this.btnUpdate.Name = "btnUpdate";
            size = new global::System.Drawing.Size(160, 28);
            this.btnUpdate.Size = size;
            this.btnUpdate.TabIndex = 8;
            this.btnUpdate.Text = "Check for updates now";
            point = new global::System.Drawing.Point(9, 60);
            this.chkUpdates.Location = point;
            this.chkUpdates.Name = "chkUpdates";
            size = new global::System.Drawing.Size(304, 24);
            this.chkUpdates.Size = size;
            this.chkUpdates.TabIndex = 6;
            this.chkUpdates.Text = "Check for updates on startup";
            this.TabPage1.Controls.Add(this.Label15);
            this.TabPage1.Controls.Add(this.Label10);
            this.TabPage1.Controls.Add(this.cmbAction);
            this.TabPage1.Controls.Add(this.GroupBox9);
            this.TabPage1.Controls.Add(this.GroupBox7);
            point = new global::System.Drawing.Point(4, 23);
            this.TabPage1.Location = point;
            this.TabPage1.Name = "TabPage1";
            size = new global::System.Drawing.Size(630, 325);
            this.TabPage1.Size = size;
            this.TabPage1.TabIndex = 6;
            this.TabPage1.Text = "Drag & Drop";
            this.TabPage1.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(14, 9);
            this.Label15.Location = point;
            this.Label15.Name = "Label15";
            size = new global::System.Drawing.Size(602, 92);
            this.Label15.Size = size;
            this.Label15.TabIndex = 4;
            this.Label15.Text = componentResourceManager.GetString("Label15.Text");
            this.Label10.AutoSize = true;
            this.Label10.Font = new global::System.Drawing.Font("Arial", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
            point = new global::System.Drawing.Point(19, 268);
            this.Label10.Location = point;
            this.Label10.Name = "Label10";
            size = new global::System.Drawing.Size(285, 15);
            this.Label10.Size = size;
            this.Label10.TabIndex = 3;
            this.Label10.Text = "Action to take whenever the above scenario occurs:";
            this.cmbAction.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbAction.FormattingEnabled = true;
            point = new global::System.Drawing.Point(18, 293);
            this.cmbAction.Location = point;
            this.cmbAction.Name = "cmbAction";
            size = new global::System.Drawing.Size(356, 22);
            this.cmbAction.Size = size;
            this.cmbAction.TabIndex = 2;
            this.GroupBox9.Controls.Add(this.lblExample);
            point = new global::System.Drawing.Point(403, 104);
            this.GroupBox9.Location = point;
            this.GroupBox9.Name = "GroupBox9";
            size = new global::System.Drawing.Size(214, 161);
            this.GroupBox9.Size = size;
            this.GroupBox9.TabIndex = 1;
            this.GroupBox9.TabStop = false;
            this.GroupBox9.Text = "Description / Example(s)";
            point = new global::System.Drawing.Point(13, 17);
            this.lblExample.Location = point;
            this.lblExample.Name = "lblExample";
            size = new global::System.Drawing.Size(188, 130);
            this.lblExample.Size = size;
            this.lblExample.TabIndex = 0;
            this.GroupBox7.Controls.Add(this.listScenarios);
            point = new global::System.Drawing.Point(8, 102);
            this.GroupBox7.Location = point;
            this.GroupBox7.Name = "GroupBox7";
            size = new global::System.Drawing.Size(380, 163);
            this.GroupBox7.Size = size;
            this.GroupBox7.TabIndex = 0;
            this.GroupBox7.TabStop = false;
            this.GroupBox7.Text = "Scenario";
            this.listScenarios.FormattingEnabled = true;
            this.listScenarios.ItemHeight = 14;
            this.listScenarios.Items.AddRange(new object[]
            {
                "Power is moved or swapped too low",
                "Power is moved too high (some powers will no longer fit)",
                "Power is moved or swapped higher than slots' levels",
                "Power is moved or swapped too high to have # slots",
                "Power being replaced is swapped too low",
                "Power being replaced is swapped higher than slots' levels",
                "Power being replaced is swapped too high to have # slots",
                "Power being shifted down cannot shift to the necessary level",
                "Power being shifted up has slots from lower levels",
                "Power being shifted up has impossible # of slots",
                "There is a gap in a group of powers that are being shifted",
                "A power placed at its minimum level is being shifted up",
                "The power in the destination slot is prevented from being shifted up",
                "Slot being level-swapped is too low for the destination power",
                "Slot being level-swapped is too low for the source power"
            });
            point = new global::System.Drawing.Point(13, 19);
            this.listScenarios.Location = point;
            this.listScenarios.Name = "listScenarios";
            size = new global::System.Drawing.Size(353, 116);
            this.listScenarios.Size = size;
            this.listScenarios.TabIndex = 0;
            point = new global::System.Drawing.Point(246, 354);
            this.chkColourPrint.Location = point;
            this.chkColourPrint.Name = "chkColourPrint";
            size = new global::System.Drawing.Size(156, 16);
            this.chkColourPrint.Size = size;
            this.chkColourPrint.TabIndex = 2;
            this.chkColourPrint.Text = "Print in color";
            this.chkColourPrint.Visible = false;
            this.myTip.AutoPopDelay = 10000;
            this.myTip.InitialDelay = 500;
            this.myTip.ReshowDelay = 100;
            this.cPicker.FullOpen = true;
            point = new global::System.Drawing.Point(536, 296);
            this.TeamSize.Location = point;
            array = new int[4];
            array[0] = 8;
            num = new decimal(array);
            this.TeamSize.Maximum = num;
            array = new int[4];
            array[0] = 1;
            num = new decimal(array);
            this.TeamSize.Minimum = num;
            this.TeamSize.Name = "TeamSize";
            size = new global::System.Drawing.Size(88, 20);
            this.TeamSize.Size = size;
            this.TeamSize.TabIndex = 70;
            this.myTip.SetToolTip(this.TeamSize, "Set this to the number of players on your team.");
            array = new int[4];
            array[0] = 8;
            num = new decimal(array);
            this.TeamSize.Value = num;
            point = new global::System.Drawing.Point(473, 297);
            this.Label16.Location = point;
            this.Label16.Name = "Label16";
            size = new global::System.Drawing.Size(57, 18);
            this.Label16.Size = size;
            this.Label16.TabIndex = 66;
            this.Label16.Text = "Team Size";
            base.AcceptButton = this.btnOK;
            base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = global::System.Drawing.SystemColors.Control;
            base.CancelButton = this.btnCancel;
            size = new global::System.Drawing.Size(640, 392);
            base.ClientSize = size;
            base.Controls.Add(this.chkColourPrint);
            base.Controls.Add(this.TabControl1);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            this.Font = new global::System.Drawing.Font("Arial", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Pixel, 0);
            this.ForeColor = global::System.Drawing.SystemColors.ControlText;
            base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
            base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmCalcOpt";
            base.ShowInTaskbar = false;
            base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Options";
            this.TabControl1.ResumeLayout(false);
            this.TabPage3.ResumeLayout(false);
            this.GroupBox17.ResumeLayout(false);
            this.GroupBox17.PerformLayout();
            this.udStatSize.EndInit();
            this.udRTFSize.EndInit();
            this.GroupBox5.ResumeLayout(false);
            this.GroupBox14.ResumeLayout(false);
            this.udIOLevel.EndInit();
            this.GroupBox3.ResumeLayout(false);
            this.TabPage2.ResumeLayout(false);
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox15.ResumeLayout(false);
            this.GroupBox8.ResumeLayout(false);
            this.GroupBox6.ResumeLayout(false);
            this.TabPage6.ResumeLayout(false);
            this.GroupBox13.ResumeLayout(false);
            this.udForceLevel.EndInit();
            this.GroupBox10.ResumeLayout(false);
            this.udBaseToHit.EndInit();
            this.GroupBox4.ResumeLayout(false);
            this.udExLow.EndInit();
            this.udExHigh.EndInit();
            this.TabPage4.ResumeLayout(false);
            this.GroupBox12.ResumeLayout(false);
            this.GroupBox12.PerformLayout();
            this.GroupBox11.ResumeLayout(false);
            this.TabPage5.ResumeLayout(false);
            this.GroupBox16.ResumeLayout(false);
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox1.PerformLayout();
            this.TabPage1.ResumeLayout(false);
            this.TabPage1.PerformLayout();
            this.GroupBox9.ResumeLayout(false);
            this.GroupBox7.ResumeLayout(false);
            this.TeamSize.EndInit();
            base.ResumeLayout(false);
        }


        private global::System.ComponentModel.IContainer components;
    }
}
