namespace Hero_Designer
{

    public partial class frmCompare : global::System.Windows.Forms.Form
    {

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }
        [global::System.Diagnostics.DebuggerStepThrough]
        void InitializeComponent()
        {
            this.components = new global::System.ComponentModel.Container();
            global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmCompare));
            this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
            this.lblKeyColor1 = new global::System.Windows.Forms.Label();
            this.cbSet1 = new global::System.Windows.Forms.ComboBox();
            this.cbType1 = new global::System.Windows.Forms.ComboBox();
            this.cbAT1 = new global::System.Windows.Forms.ComboBox();
            this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
            this.lblKeyColor2 = new global::System.Windows.Forms.Label();
            this.cbSet2 = new global::System.Windows.Forms.ComboBox();
            this.cbType2 = new global::System.Windows.Forms.ComboBox();
            this.cbAT2 = new global::System.Windows.Forms.ComboBox();
            this.lblScale = new global::System.Windows.Forms.Label();
            this.tbScaleX = new global::System.Windows.Forms.TrackBar();
            this.chkMatching = new global::System.Windows.Forms.CheckBox();
            this.tTip = new global::System.Windows.Forms.ToolTip(this.components);
            this.btnTweakMatch = new global::System.Windows.Forms.Button();
            this.chkOnTop = new global::midsControls.ImageButton();
            this.btnClose = new global::midsControls.ImageButton();
            this.Graph = new global::midsControls.ctlMultiGraph();
            this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
            this.lstDisplay = new global::System.Windows.Forms.ListBox();
            this.GroupBox1.SuspendLayout();
            this.GroupBox2.SuspendLayout();
            this.tbScaleX.BeginInit();
            this.GroupBox4.SuspendLayout();
            base.SuspendLayout();
            this.GroupBox1.Controls.Add(this.lblKeyColor1);
            this.GroupBox1.Controls.Add(this.cbSet1);
            this.GroupBox1.Controls.Add(this.cbType1);
            this.GroupBox1.Controls.Add(this.cbAT1);
            this.GroupBox1.ForeColor = global::System.Drawing.Color.White;
            global::System.Drawing.Point point = new global::System.Drawing.Point(4, 4);
            this.GroupBox1.Location = point;
            this.GroupBox1.Name = "GroupBox1";
            global::System.Drawing.Size size = new global::System.Drawing.Size(144, 116);
            this.GroupBox1.Size = size;
            this.GroupBox1.TabIndex = 2;
            this.GroupBox1.TabStop = false;
            this.GroupBox1.Text = "Powerset 1:";
            this.lblKeyColor1.BackColor = global::System.Drawing.Color.Blue;
            this.lblKeyColor1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(8, 20);
            this.lblKeyColor1.Location = point;
            this.lblKeyColor1.Name = "lblKeyColor1";
            size = new global::System.Drawing.Size(132, 16);
            this.lblKeyColor1.Size = size;
            this.lblKeyColor1.TabIndex = 3;
            this.cbSet1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            point = new global::System.Drawing.Point(8, 88);
            this.cbSet1.Location = point;
            this.cbSet1.Name = "cbSet1";
            size = new global::System.Drawing.Size(132, 22);
            this.cbSet1.Size = size;
            this.cbSet1.TabIndex = 2;
            this.cbType1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            point = new global::System.Drawing.Point(8, 64);
            this.cbType1.Location = point;
            this.cbType1.Name = "cbType1";
            size = new global::System.Drawing.Size(132, 22);
            this.cbType1.Size = size;
            this.cbType1.TabIndex = 1;
            this.cbAT1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            point = new global::System.Drawing.Point(8, 40);
            this.cbAT1.Location = point;
            this.cbAT1.Name = "cbAT1";
            size = new global::System.Drawing.Size(132, 22);
            this.cbAT1.Size = size;
            this.cbAT1.TabIndex = 0;
            this.GroupBox2.Controls.Add(this.lblKeyColor2);
            this.GroupBox2.Controls.Add(this.cbSet2);
            this.GroupBox2.Controls.Add(this.cbType2);
            this.GroupBox2.Controls.Add(this.cbAT2);
            this.GroupBox2.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(4, 126);
            this.GroupBox2.Location = point;
            this.GroupBox2.Name = "GroupBox2";
            size = new global::System.Drawing.Size(144, 116);
            this.GroupBox2.Size = size;
            this.GroupBox2.TabIndex = 3;
            this.GroupBox2.TabStop = false;
            this.GroupBox2.Text = "Powerset 2:";
            this.lblKeyColor2.BackColor = global::System.Drawing.Color.Yellow;
            this.lblKeyColor2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(8, 20);
            this.lblKeyColor2.Location = point;
            this.lblKeyColor2.Name = "lblKeyColor2";
            size = new global::System.Drawing.Size(132, 16);
            this.lblKeyColor2.Size = size;
            this.lblKeyColor2.TabIndex = 3;
            this.cbSet2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            point = new global::System.Drawing.Point(8, 88);
            this.cbSet2.Location = point;
            this.cbSet2.Name = "cbSet2";
            size = new global::System.Drawing.Size(132, 22);
            this.cbSet2.Size = size;
            this.cbSet2.TabIndex = 2;
            this.cbType2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            point = new global::System.Drawing.Point(8, 64);
            this.cbType2.Location = point;
            this.cbType2.Name = "cbType2";
            size = new global::System.Drawing.Size(132, 22);
            this.cbType2.Size = size;
            this.cbType2.TabIndex = 1;
            this.cbAT2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            point = new global::System.Drawing.Point(8, 40);
            this.cbAT2.Location = point;
            this.cbAT2.Name = "cbAT2";
            size = new global::System.Drawing.Size(132, 22);
            this.cbAT2.Size = size;
            this.cbAT2.TabIndex = 0;
            point = new global::System.Drawing.Point(312, 500);
            this.lblScale.Location = point;
            this.lblScale.Name = "lblScale";
            size = new global::System.Drawing.Size(108, 20);
            this.lblScale.Size = size;
            this.lblScale.TabIndex = 9;
            this.lblScale.Text = "Scale: 100%";
            this.lblScale.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.tbScaleX.LargeChange = 1;
            point = new global::System.Drawing.Point(184, 476);
            this.tbScaleX.Location = point;
            this.tbScaleX.Minimum = 1;
            this.tbScaleX.Name = "tbScaleX";
            size = new global::System.Drawing.Size(340, 45);
            this.tbScaleX.Size = size;
            this.tbScaleX.TabIndex = 8;
            this.tbScaleX.TickFrequency = 10;
            this.tbScaleX.TickStyle = global::System.Windows.Forms.TickStyle.None;
            this.tbScaleX.Value = 10;
            point = new global::System.Drawing.Point(8, 508);
            this.chkMatching.Location = point;
            this.chkMatching.Name = "chkMatching";
            size = new global::System.Drawing.Size(116, 20);
            this.chkMatching.Size = size;
            this.chkMatching.TabIndex = 11;
            this.chkMatching.Text = "Attempt Matching";
            this.tTip.AutoPopDelay = 10000;
            this.tTip.InitialDelay = 500;
            this.tTip.ReshowDelay = 100;
            this.btnTweakMatch.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.btnTweakMatch.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnTweakMatch.ForeColor = global::System.Drawing.Color.Black;
            point = new global::System.Drawing.Point(130, 508);
            this.btnTweakMatch.Location = point;
            this.btnTweakMatch.Name = "btnTweakMatch";
            size = new global::System.Drawing.Size(60, 20);
            this.btnTweakMatch.Size = size;
            this.btnTweakMatch.TabIndex = 12;
            this.btnTweakMatch.Text = "Tweak";
            this.tTip.SetToolTip(this.btnTweakMatch, "Modify the data used to perform power matching");
            this.btnTweakMatch.UseVisualStyleBackColor = true;
            this.btnTweakMatch.Visible = false;
            this.chkOnTop.Checked = true;
            this.chkOnTop.Font = new global::System.Drawing.Font("Arial", 11f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Pixel, 0);
            point = new global::System.Drawing.Point(0, 0);
            this.chkOnTop.KnockoutLocationPoint = point;
            point = new global::System.Drawing.Point(530, 476);
            this.chkOnTop.Location = point;
            this.chkOnTop.Name = "chkOnTop";
            size = new global::System.Drawing.Size(105, 22);
            this.chkOnTop.Size = size;
            this.chkOnTop.TabIndex = 15;
            this.chkOnTop.TextOff = "Keep On Top";
            this.chkOnTop.TextOn = "Keep On Top";
            this.chkOnTop.Toggle = true;
            this.btnClose.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
            this.btnClose.Checked = false;
            this.btnClose.Font = new global::System.Drawing.Font("Arial", 11f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Pixel, 0);
            point = new global::System.Drawing.Point(0, 0);
            this.btnClose.KnockoutLocationPoint = point;
            point = new global::System.Drawing.Point(530, 504);
            this.btnClose.Location = point;
            global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btnClose.Margin = margin;
            this.btnClose.Name = "btnClose";
            size = new global::System.Drawing.Size(105, 22);
            this.btnClose.Size = size;
            this.btnClose.TabIndex = 14;
            this.btnClose.TextOff = "Close";
            this.btnClose.TextOn = "Close";
            this.btnClose.Toggle = false;
            this.Graph.BackColor = global::System.Drawing.Color.FromArgb(0, 0, 32);
            this.Graph.Border = true;
            this.Graph.Clickable = false;
            this.Graph.ColorBase = global::System.Drawing.Color.Blue;
            this.Graph.ColorEnh = global::System.Drawing.Color.Yellow;
            this.Graph.ColorFadeEnd = global::System.Drawing.Color.Red;
            this.Graph.ColorFadeStart = global::System.Drawing.Color.Black;
            this.Graph.ColorHighlight = global::System.Drawing.Color.White;
            this.Graph.ColorLines = global::System.Drawing.Color.Black;
            this.Graph.ColorMarkerInner = global::System.Drawing.Color.Black;
            this.Graph.ColorMarkerOuter = global::System.Drawing.Color.Yellow;
            this.Graph.Dual = true;
            this.Graph.Font = new global::System.Drawing.Font("Arial", 7.5f);
            this.Graph.ForcedMax = 0f;
            this.Graph.ForeColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.Graph.Highlight = true;
            this.Graph.ImeMode = global::System.Windows.Forms.ImeMode.Off;
            this.Graph.ItemHeight = 26;
            this.Graph.Lines = true;
            point = new global::System.Drawing.Point(152, 4);
            this.Graph.Location = point;
            this.Graph.MarkerValue = 0f;
            this.Graph.Max = 100f;
            this.Graph.Name = "Graph";
            this.Graph.PaddingX = 2f;
            this.Graph.PaddingY = 6f;
            this.Graph.ScaleHeight = 16;
            this.Graph.ScaleIndex = 8;
            this.Graph.ShowScale = true;
            size = new global::System.Drawing.Size(484, 468);
            this.Graph.Size = size;
            this.Graph.Style = global::Enums.GraphStyle.Twin;
            this.Graph.TabIndex = 1;
            this.Graph.TextWidth = 120;
            this.GroupBox4.Controls.Add(this.lstDisplay);
            this.GroupBox4.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(8, 248);
            this.GroupBox4.Location = point;
            this.GroupBox4.Name = "GroupBox4";
            size = new global::System.Drawing.Size(144, 254);
            this.GroupBox4.Size = size;
            this.GroupBox4.TabIndex = 16;
            this.GroupBox4.TabStop = false;
            this.GroupBox4.Text = "Display:";
            this.lstDisplay.FormattingEnabled = true;
            this.lstDisplay.ItemHeight = 14;
            point = new global::System.Drawing.Point(6, 19);
            this.lstDisplay.Location = point;
            this.lstDisplay.Name = "lstDisplay";
            size = new global::System.Drawing.Size(130, 228);
            this.lstDisplay.Size = size;
            this.lstDisplay.TabIndex = 0;
            base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = global::System.Drawing.Color.FromArgb(0, 0, 32);
            size = new global::System.Drawing.Size(640, 532);
            base.ClientSize = size;
            base.Controls.Add(this.GroupBox4);
            base.Controls.Add(this.chkOnTop);
            base.Controls.Add(this.btnClose);
            base.Controls.Add(this.btnTweakMatch);
            base.Controls.Add(this.chkMatching);
            base.Controls.Add(this.lblScale);
            base.Controls.Add(this.tbScaleX);
            base.Controls.Add(this.GroupBox2);
            base.Controls.Add(this.GroupBox1);
            base.Controls.Add(this.Graph);
            this.Font = new global::System.Drawing.Font("Arial", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Pixel, 0);
            this.ForeColor = global::System.Drawing.Color.White;
            base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
            base.KeyPreview = true;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmCompare";
            base.StartPosition = global::System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Powerset Comparison";
            base.TopMost = true;
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox2.ResumeLayout(false);
            this.tbScaleX.EndInit();
            this.GroupBox4.ResumeLayout(false);
            base.ResumeLayout(false);
            base.PerformLayout();
        }
        global::System.ComponentModel.IContainer components;
    }
}
