namespace Hero_Designer
{

    public partial class frmDBEdit : global::System.Windows.Forms.Form
    {

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }


        [global::System.Diagnostics.DebuggerStepThrough]
        void InitializeComponent()
        {
            global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmDBEdit));
            this.udIssue = new global::System.Windows.Forms.NumericUpDown();
            this.Label1 = new global::System.Windows.Forms.Label();
            this.Label2 = new global::System.Windows.Forms.Label();
            this.lblDate = new global::System.Windows.Forms.Label();
            this.btnEditEnh = new global::System.Windows.Forms.Button();
            this.btnEditIOSet = new global::System.Windows.Forms.Button();
            this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
            this.lblCountSalvage = new global::System.Windows.Forms.Label();
            this.Label6 = new global::System.Windows.Forms.Label();
            this.lblCountRecipe = new global::System.Windows.Forms.Label();
            this.Label4 = new global::System.Windows.Forms.Label();
            this.lblCountFX = new global::System.Windows.Forms.Label();
            this.Label15 = new global::System.Windows.Forms.Label();
            this.lblCountPwr = new global::System.Windows.Forms.Label();
            this.Label13 = new global::System.Windows.Forms.Label();
            this.lblCountPS = new global::System.Windows.Forms.Label();
            this.Label11 = new global::System.Windows.Forms.Label();
            this.lblCountIOSet = new global::System.Windows.Forms.Label();
            this.Label9 = new global::System.Windows.Forms.Label();
            this.lblCountEnh = new global::System.Windows.Forms.Label();
            this.Label7 = new global::System.Windows.Forms.Label();
            this.lblCountAT = new global::System.Windows.Forms.Label();
            this.Label5 = new global::System.Windows.Forms.Label();
            this.btnClose = new global::System.Windows.Forms.Button();
            this.btnDate = new global::System.Windows.Forms.Button();
            this.btnSalvage = new global::System.Windows.Forms.Button();
            this.btnRecipe = new global::System.Windows.Forms.Button();
            this.btnCSV = new global::System.Windows.Forms.Button();
            this.btnEditEntity = new global::System.Windows.Forms.Button();
            this.btnPSBrowse = new global::System.Windows.Forms.Button();
            this.txtDBVer = new global::System.Windows.Forms.TextBox();
            this.Label3 = new global::System.Windows.Forms.Label();
            this.btnFileReport = new global::System.Windows.Forms.Button();
            this.exportIndexes = new global::System.Windows.Forms.Button();
            this.udIssue.BeginInit();
            this.GroupBox1.SuspendLayout();
            base.SuspendLayout();
            global::System.Drawing.Point point = new global::System.Drawing.Point(148, 44);
            this.udIssue.Location = point;
            int[] array = new int[4];
            array[0] = 1;
            decimal num = new decimal(array);
            this.udIssue.Minimum = num;
            this.udIssue.Name = "udIssue";
            global::System.Drawing.Size size = new global::System.Drawing.Size(84, 20);
            this.udIssue.Size = size;
            this.udIssue.TabIndex = 0;
            this.udIssue.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
            array = new int[4];
            array[0] = 12;
            num = new decimal(array);
            this.udIssue.Value = num;
            point = new global::System.Drawing.Point(22, 44);
            this.Label1.Location = point;
            this.Label1.Name = "Label1";
            size = new global::System.Drawing.Size(120, 20);
            this.Label1.Size = size;
            this.Label1.TabIndex = 2;
            this.Label1.Text = "CoX Issue Supported:";
            this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(4, 16);
            this.Label2.Location = point;
            this.Label2.Name = "Label2";
            size = new global::System.Drawing.Size(144, 20);
            this.Label2.Size = size;
            this.Label2.TabIndex = 3;
            this.Label2.Text = "Database Update Date:";
            this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.lblDate.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(148, 16);
            this.lblDate.Location = point;
            this.lblDate.Name = "lblDate";
            size = new global::System.Drawing.Size(84, 20);
            this.lblDate.Size = size;
            this.lblDate.TabIndex = 4;
            this.lblDate.Text = "DD/MM/YYYY";
            this.lblDate.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditEnh.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnEditEnh.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnEditEnh.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(48, 168);
            this.btnEditEnh.Location = point;
            this.btnEditEnh.Name = "btnEditEnh";
            size = new global::System.Drawing.Size(160, 24);
            this.btnEditEnh.Size = size;
            this.btnEditEnh.TabIndex = 5;
            this.btnEditEnh.Text = "Enhancement Editor";
            this.btnEditEnh.UseVisualStyleBackColor = true;
            this.btnEditIOSet.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnEditIOSet.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnEditIOSet.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(48, 198);
            this.btnEditIOSet.Location = point;
            this.btnEditIOSet.Name = "btnEditIOSet";
            size = new global::System.Drawing.Size(160, 24);
            this.btnEditIOSet.Size = size;
            this.btnEditIOSet.TabIndex = 6;
            this.btnEditIOSet.Text = "Invention Set Editor";
            this.btnEditIOSet.UseVisualStyleBackColor = true;
            this.GroupBox1.Controls.Add(this.lblCountSalvage);
            this.GroupBox1.Controls.Add(this.Label6);
            this.GroupBox1.Controls.Add(this.lblCountRecipe);
            this.GroupBox1.Controls.Add(this.Label4);
            this.GroupBox1.Controls.Add(this.lblCountFX);
            this.GroupBox1.Controls.Add(this.Label15);
            this.GroupBox1.Controls.Add(this.lblCountPwr);
            this.GroupBox1.Controls.Add(this.Label13);
            this.GroupBox1.Controls.Add(this.lblCountPS);
            this.GroupBox1.Controls.Add(this.Label11);
            this.GroupBox1.Controls.Add(this.lblCountIOSet);
            this.GroupBox1.Controls.Add(this.Label9);
            this.GroupBox1.Controls.Add(this.lblCountEnh);
            this.GroupBox1.Controls.Add(this.Label7);
            this.GroupBox1.Controls.Add(this.lblCountAT);
            this.GroupBox1.Controls.Add(this.Label5);
            this.GroupBox1.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(236, 4);
            this.GroupBox1.Location = point;
            this.GroupBox1.Name = "GroupBox1";
            size = new global::System.Drawing.Size(164, 218);
            this.GroupBox1.Size = size;
            this.GroupBox1.TabIndex = 9;
            this.GroupBox1.TabStop = false;
            this.GroupBox1.Text = "Statistics:";
            this.lblCountSalvage.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(88, 184);
            this.lblCountSalvage.Location = point;
            this.lblCountSalvage.Name = "lblCountSalvage";
            size = new global::System.Drawing.Size(68, 20);
            this.lblCountSalvage.Size = size;
            this.lblCountSalvage.TabIndex = 20;
            this.lblCountSalvage.Text = "Count";
            this.lblCountSalvage.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(4, 184);
            this.Label6.Location = point;
            this.Label6.Name = "Label6";
            size = new global::System.Drawing.Size(84, 20);
            this.Label6.Size = size;
            this.Label6.TabIndex = 19;
            this.Label6.Text = "Salvage:";
            this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.lblCountRecipe.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(88, 160);
            this.lblCountRecipe.Location = point;
            this.lblCountRecipe.Name = "lblCountRecipe";
            size = new global::System.Drawing.Size(68, 20);
            this.lblCountRecipe.Size = size;
            this.lblCountRecipe.TabIndex = 18;
            this.lblCountRecipe.Text = "Count";
            this.lblCountRecipe.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(4, 160);
            this.Label4.Location = point;
            this.Label4.Name = "Label4";
            size = new global::System.Drawing.Size(84, 20);
            this.Label4.Size = size;
            this.Label4.TabIndex = 17;
            this.Label4.Text = "Recipes:";
            this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.lblCountFX.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(88, 136);
            this.lblCountFX.Location = point;
            this.lblCountFX.Name = "lblCountFX";
            size = new global::System.Drawing.Size(68, 20);
            this.lblCountFX.Size = size;
            this.lblCountFX.TabIndex = 16;
            this.lblCountFX.Text = "Count";
            this.lblCountFX.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(4, 136);
            this.Label15.Location = point;
            this.Label15.Name = "Label15";
            size = new global::System.Drawing.Size(84, 20);
            this.Label15.Size = size;
            this.Label15.TabIndex = 15;
            this.Label15.Text = "Power Effects:";
            this.Label15.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.lblCountPwr.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(88, 112);
            this.lblCountPwr.Location = point;
            this.lblCountPwr.Name = "lblCountPwr";
            size = new global::System.Drawing.Size(68, 20);
            this.lblCountPwr.Size = size;
            this.lblCountPwr.TabIndex = 14;
            this.lblCountPwr.Text = "Count";
            this.lblCountPwr.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(4, 112);
            this.Label13.Location = point;
            this.Label13.Name = "Label13";
            size = new global::System.Drawing.Size(84, 20);
            this.Label13.Size = size;
            this.Label13.TabIndex = 13;
            this.Label13.Text = "Powers:";
            this.Label13.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.lblCountPS.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(88, 88);
            this.lblCountPS.Location = point;
            this.lblCountPS.Name = "lblCountPS";
            size = new global::System.Drawing.Size(68, 20);
            this.lblCountPS.Size = size;
            this.lblCountPS.TabIndex = 12;
            this.lblCountPS.Text = "Count";
            this.lblCountPS.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(4, 88);
            this.Label11.Location = point;
            this.Label11.Name = "Label11";
            size = new global::System.Drawing.Size(84, 20);
            this.Label11.Size = size;
            this.Label11.TabIndex = 11;
            this.Label11.Text = "Powersets:";
            this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.lblCountIOSet.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(88, 64);
            this.lblCountIOSet.Location = point;
            this.lblCountIOSet.Name = "lblCountIOSet";
            size = new global::System.Drawing.Size(68, 20);
            this.lblCountIOSet.Size = size;
            this.lblCountIOSet.TabIndex = 10;
            this.lblCountIOSet.Text = "Count";
            this.lblCountIOSet.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(4, 64);
            this.Label9.Location = point;
            this.Label9.Name = "Label9";
            size = new global::System.Drawing.Size(84, 20);
            this.Label9.Size = size;
            this.Label9.TabIndex = 9;
            this.Label9.Text = "Invention Sets:";
            this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.lblCountEnh.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(88, 40);
            this.lblCountEnh.Location = point;
            this.lblCountEnh.Name = "lblCountEnh";
            size = new global::System.Drawing.Size(68, 20);
            this.lblCountEnh.Size = size;
            this.lblCountEnh.TabIndex = 8;
            this.lblCountEnh.Text = "Count";
            this.lblCountEnh.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(4, 40);
            this.Label7.Location = point;
            this.Label7.Name = "Label7";
            size = new global::System.Drawing.Size(84, 20);
            this.Label7.Size = size;
            this.Label7.TabIndex = 7;
            this.Label7.Text = "Enhancements:";
            this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.lblCountAT.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(88, 16);
            this.lblCountAT.Location = point;
            this.lblCountAT.Name = "lblCountAT";
            size = new global::System.Drawing.Size(68, 20);
            this.lblCountAT.Size = size;
            this.lblCountAT.TabIndex = 6;
            this.lblCountAT.Text = "Count";
            this.lblCountAT.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
            point = new global::System.Drawing.Point(4, 16);
            this.Label5.Location = point;
            this.Label5.Name = "Label5";
            size = new global::System.Drawing.Size(84, 20);
            this.Label5.Size = size;
            this.Label5.TabIndex = 5;
            this.Label5.Text = "Classes:";
            this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnClose.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
            this.btnClose.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnClose.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(236, 288);
            this.btnClose.Location = point;
            this.btnClose.Name = "btnClose";
            size = new global::System.Drawing.Size(164, 24);
            this.btnClose.Size = size;
            this.btnClose.TabIndex = 10;
            this.btnClose.Text = "Close";
            this.btnClose.UseVisualStyleBackColor = true;
            this.btnDate.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnDate.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnDate.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(31, 16);
            this.btnDate.Location = point;
            this.btnDate.Name = "btnDate";
            size = new global::System.Drawing.Size(111, 20);
            this.btnDate.Size = size;
            this.btnDate.TabIndex = 13;
            this.btnDate.Text = "Set Date";
            this.btnDate.UseVisualStyleBackColor = true;
            this.btnDate.Visible = false;
            this.btnSalvage.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnSalvage.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnSalvage.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(48, 228);
            this.btnSalvage.Location = point;
            this.btnSalvage.Name = "btnSalvage";
            size = new global::System.Drawing.Size(160, 24);
            this.btnSalvage.Size = size;
            this.btnSalvage.TabIndex = 14;
            this.btnSalvage.Text = "Salvage Editor";
            this.btnSalvage.UseVisualStyleBackColor = true;
            this.btnRecipe.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnRecipe.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnRecipe.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(48, 258);
            this.btnRecipe.Location = point;
            this.btnRecipe.Name = "btnRecipe";
            size = new global::System.Drawing.Size(160, 24);
            this.btnRecipe.Size = size;
            this.btnRecipe.TabIndex = 15;
            this.btnRecipe.Text = "Recipe Editor";
            this.btnRecipe.UseVisualStyleBackColor = true;
            this.btnCSV.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnCSV.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnCSV.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(48, 288);
            this.btnCSV.Location = point;
            this.btnCSV.Name = "btnCSV";
            size = new global::System.Drawing.Size(160, 24);
            this.btnCSV.Size = size;
            this.btnCSV.TabIndex = 16;
            this.btnCSV.Text = "CSV Importer";
            this.btnCSV.UseVisualStyleBackColor = true;
            this.btnEditEntity.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnEditEntity.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnEditEntity.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(48, 138);
            this.btnEditEntity.Location = point;
            this.btnEditEntity.Name = "btnEditEntity";
            size = new global::System.Drawing.Size(160, 24);
            this.btnEditEntity.Size = size;
            this.btnEditEntity.TabIndex = 17;
            this.btnEditEntity.Text = "Entity Editor";
            this.btnEditEntity.UseVisualStyleBackColor = true;
            this.btnPSBrowse.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnPSBrowse.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnPSBrowse.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(48, 94);
            this.btnPSBrowse.Location = point;
            this.btnPSBrowse.Name = "btnPSBrowse";
            size = new global::System.Drawing.Size(160, 38);
            this.btnPSBrowse.Size = size;
            this.btnPSBrowse.TabIndex = 18;
            this.btnPSBrowse.Text = "Main Database Editor";
            this.btnPSBrowse.UseVisualStyleBackColor = true;
            point = new global::System.Drawing.Point(148, 68);
            this.txtDBVer.Location = point;
            this.txtDBVer.Name = "txtDBVer";
            size = new global::System.Drawing.Size(84, 20);
            this.txtDBVer.Size = size;
            this.txtDBVer.TabIndex = 21;
            point = new global::System.Drawing.Point(22, 68);
            this.Label3.Location = point;
            this.Label3.Name = "Label3";
            size = new global::System.Drawing.Size(120, 20);
            this.Label3.Size = size;
            this.Label3.TabIndex = 22;
            this.Label3.Text = "Database Version:";
            this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.btnFileReport.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.btnFileReport.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.btnFileReport.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(236, 258);
            this.btnFileReport.Location = point;
            this.btnFileReport.Name = "btnFileReport";
            size = new global::System.Drawing.Size(164, 24);
            this.btnFileReport.Size = size;
            this.btnFileReport.TabIndex = 23;
            this.btnFileReport.Text = "File Load Report";
            this.btnFileReport.UseVisualStyleBackColor = true;
            this.btnFileReport.Visible = false;
            this.exportIndexes.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
            this.exportIndexes.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
            this.exportIndexes.ForeColor = global::System.Drawing.SystemColors.ControlText;
            point = new global::System.Drawing.Point(236, 228);
            this.exportIndexes.Location = point;
            this.exportIndexes.Name = "exportIndexes";
            size = new global::System.Drawing.Size(164, 24);
            this.exportIndexes.Size = size;
            this.exportIndexes.TabIndex = 24;
            this.exportIndexes.Text = "Export Power Indexes";
            this.exportIndexes.UseVisualStyleBackColor = true;
            this.exportIndexes.Visible = false;
            size = new global::System.Drawing.Size(5, 13);
            this.AutoScaleBaseSize = size;
            this.BackColor = global::System.Drawing.Color.FromArgb(0, 0, 32);
            size = new global::System.Drawing.Size(416, 327);
            base.ClientSize = size;
            base.Controls.Add(this.btnFileReport);
            base.Controls.Add(this.Label3);
            base.Controls.Add(this.txtDBVer);
            base.Controls.Add(this.btnPSBrowse);
            base.Controls.Add(this.btnEditEntity);
            base.Controls.Add(this.btnCSV);
            base.Controls.Add(this.btnRecipe);
            base.Controls.Add(this.btnSalvage);
            base.Controls.Add(this.btnDate);
            base.Controls.Add(this.btnClose);
            base.Controls.Add(this.GroupBox1);
            base.Controls.Add(this.btnEditIOSet);
            base.Controls.Add(this.btnEditEnh);
            base.Controls.Add(this.lblDate);
            base.Controls.Add(this.Label2);
            base.Controls.Add(this.Label1);
            base.Controls.Add(this.udIssue);
            this.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
            this.ForeColor = global::System.Drawing.Color.White;
            base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
            base.KeyPreview = true;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmDBEdit";
            base.ShowInTaskbar = false;
            base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Database Editor";
            this.udIssue.EndInit();
            this.GroupBox1.ResumeLayout(false);
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        global::System.ComponentModel.IContainer components;
    }
}
