namespace Hero_Designer
{

    public partial class frmExportColor : global::System.Windows.Forms.Form
    {

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }


        [global::System.Diagnostics.DebuggerStepThrough]
        void InitializeComponent()
        {
            this.components = new global::System.ComponentModel.Container();
            global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmExportColor));
            this.myTip = new global::System.Windows.Forms.ToolTip(this.components);
            this.csSlots = new global::System.Windows.Forms.Label();
            this.csLevel = new global::System.Windows.Forms.Label();
            this.csHeading = new global::System.Windows.Forms.Label();
            this.csTitle = new global::System.Windows.Forms.Label();
            this.csIO = new global::System.Windows.Forms.Label();
            this.csSet = new global::System.Windows.Forms.Label();
            this.csHO = new global::System.Windows.Forms.Label();
            this.csPower = new global::System.Windows.Forms.Label();
            this.cPicker = new global::System.Windows.Forms.ColorDialog();
            this.Label21 = new global::System.Windows.Forms.Label();
            this.Label22 = new global::System.Windows.Forms.Label();
            this.Label20 = new global::System.Windows.Forms.Label();
            this.Label19 = new global::System.Windows.Forms.Label();
            this.txtName = new global::System.Windows.Forms.TextBox();
            this.Label1 = new global::System.Windows.Forms.Label();
            this.Label4 = new global::System.Windows.Forms.Label();
            this.Label5 = new global::System.Windows.Forms.Label();
            this.Label7 = new global::System.Windows.Forms.Label();
            this.Label9 = new global::System.Windows.Forms.Label();
            this.btnOK = new global::System.Windows.Forms.Button();
            this.btnCancel = new global::System.Windows.Forms.Button();
            this.Label3 = new global::System.Windows.Forms.Label();
            base.SuspendLayout();
            this.myTip.AutoPopDelay = 10000;
            this.myTip.InitialDelay = 500;
            this.myTip.ReshowDelay = 100;
            this.csSlots.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csSlots.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            global::System.Drawing.Point point = new global::System.Drawing.Point(128, 164);
            this.csSlots.Location = point;
            this.csSlots.Name = "csSlots";
            global::System.Drawing.Size size = new global::System.Drawing.Size(52, 16);
            this.csSlots.Size = size;
            this.csSlots.TabIndex = 17;
            this.myTip.SetToolTip(this.csSlots, "Click here to select the colour for this attribute.");
            this.csLevel.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csLevel.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(128, 124);
            this.csLevel.Location = point;
            this.csLevel.Name = "csLevel";
            size = new global::System.Drawing.Size(52, 16);
            this.csLevel.Size = size;
            this.csLevel.TabIndex = 16;
            this.myTip.SetToolTip(this.csLevel, "Click here to select the colour for this attribute.");
            this.csHeading.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csHeading.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(128, 104);
            this.csHeading.Location = point;
            this.csHeading.Name = "csHeading";
            size = new global::System.Drawing.Size(52, 16);
            this.csHeading.Size = size;
            this.csHeading.TabIndex = 15;
            this.myTip.SetToolTip(this.csHeading, "Click here to select the colour for this attribute.");
            this.csTitle.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csTitle.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(128, 84);
            this.csTitle.Location = point;
            this.csTitle.Name = "csTitle";
            size = new global::System.Drawing.Size(52, 16);
            this.csTitle.Size = size;
            this.csTitle.TabIndex = 14;
            this.myTip.SetToolTip(this.csTitle, "Click here to select the colour for this attribute.");
            this.csIO.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csIO.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(128, 184);
            this.csIO.Location = point;
            this.csIO.Name = "csIO";
            size = new global::System.Drawing.Size(52, 16);
            this.csIO.Size = size;
            this.csIO.TabIndex = 23;
            this.myTip.SetToolTip(this.csIO, "Click here to select the colour for this attribute.");
            this.csSet.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csSet.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(128, 204);
            this.csSet.Location = point;
            this.csSet.Name = "csSet";
            size = new global::System.Drawing.Size(52, 16);
            this.csSet.Size = size;
            this.csSet.TabIndex = 26;
            this.myTip.SetToolTip(this.csSet, "Click here to select the colour for this attribute.");
            this.csHO.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csHO.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(128, 224);
            this.csHO.Location = point;
            this.csHO.Name = "csHO";
            size = new global::System.Drawing.Size(52, 16);
            this.csHO.Size = size;
            this.csHO.TabIndex = 28;
            this.myTip.SetToolTip(this.csHO, "Click here to select the colour for this attribute.");
            this.csPower.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csPower.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(128, 144);
            this.csPower.Location = point;
            this.csPower.Name = "csPower";
            size = new global::System.Drawing.Size(52, 16);
            this.csPower.Size = size;
            this.csPower.TabIndex = 32;
            this.myTip.SetToolTip(this.csPower, "Click here to select the colour for this attribute.");
            this.cPicker.FullOpen = true;
            point = new global::System.Drawing.Point(36, 164);
            this.Label21.Location = point;
            this.Label21.Name = "Label21";
            size = new global::System.Drawing.Size(88, 16);
            this.Label21.Size = size;
            this.Label21.TabIndex = 13;
            this.Label21.Text = "Normal Slots:";
            this.Label21.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(36, 124);
            this.Label22.Location = point;
            this.Label22.Name = "Label22";
            size = new global::System.Drawing.Size(88, 16);
            this.Label22.Size = size;
            this.Label22.TabIndex = 12;
            this.Label22.Text = "Levels:";
            this.Label22.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(36, 104);
            this.Label20.Location = point;
            this.Label20.Name = "Label20";
            size = new global::System.Drawing.Size(88, 16);
            this.Label20.Size = size;
            this.Label20.TabIndex = 11;
            this.Label20.Text = "Subheadings:";
            this.Label20.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(36, 84);
            this.Label19.Location = point;
            this.Label19.Name = "Label19";
            size = new global::System.Drawing.Size(88, 16);
            this.Label19.Size = size;
            this.Label19.TabIndex = 10;
            this.Label19.Text = "Title Text:";
            this.Label19.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(72, 8);
            this.txtName.Location = point;
            this.txtName.Name = "txtName";
            size = new global::System.Drawing.Size(124, 20);
            this.txtName.Size = size;
            this.txtName.TabIndex = 18;
            this.txtName.Text = "Scheme Name";
            point = new global::System.Drawing.Point(8, 8);
            this.Label1.Location = point;
            this.Label1.Name = "Label1";
            size = new global::System.Drawing.Size(64, 20);
            this.Label1.Size = size;
            this.Label1.TabIndex = 19;
            this.Label1.Text = "Name:";
            this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(36, 184);
            this.Label4.Location = point;
            this.Label4.Name = "Label4";
            size = new global::System.Drawing.Size(88, 16);
            this.Label4.Size = size;
            this.Label4.TabIndex = 22;
            this.Label4.Text = "Inventions:";
            this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(8, 36);
            this.Label5.Location = point;
            this.Label5.Name = "Label5";
            size = new global::System.Drawing.Size(192, 36);
            this.Label5.Size = size;
            this.Label5.TabIndex = 24;
            this.Label5.Text = "Click on a colour box to modify it.";
            this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            point = new global::System.Drawing.Point(36, 204);
            this.Label7.Location = point;
            this.Label7.Name = "Label7";
            size = new global::System.Drawing.Size(88, 16);
            this.Label7.Size = size;
            this.Label7.TabIndex = 25;
            this.Label7.Text = "Sets:";
            this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(36, 224);
            this.Label9.Location = point;
            this.Label9.Name = "Label9";
            size = new global::System.Drawing.Size(88, 16);
            this.Label9.Size = size;
            this.Label9.TabIndex = 27;
            this.Label9.Text = "Hami-Os:";
            this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.btnOK.DialogResult = global::System.Windows.Forms.DialogResult.OK;
            point = new global::System.Drawing.Point(128, 256);
            this.btnOK.Location = point;
            this.btnOK.Name = "btnOK";
            size = new global::System.Drawing.Size(75, 23);
            this.btnOK.Size = size;
            this.btnOK.TabIndex = 29;
            this.btnOK.Text = "OK";
            this.btnCancel.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
            point = new global::System.Drawing.Point(44, 256);
            this.btnCancel.Location = point;
            this.btnCancel.Name = "btnCancel";
            size = new global::System.Drawing.Size(75, 23);
            this.btnCancel.Size = size;
            this.btnCancel.TabIndex = 30;
            this.btnCancel.Text = "Cancel";
            point = new global::System.Drawing.Point(36, 144);
            this.Label3.Location = point;
            this.Label3.Name = "Label3";
            size = new global::System.Drawing.Size(88, 16);
            this.Label3.Size = size;
            this.Label3.TabIndex = 31;
            this.Label3.Text = "Power Names:";
            this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            base.AcceptButton = this.btnOK;
            base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.None;
            base.CancelButton = this.btnCancel;
            size = new global::System.Drawing.Size(210, 292);
            base.ClientSize = size;
            base.Controls.Add(this.csPower);
            base.Controls.Add(this.Label3);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.csHO);
            base.Controls.Add(this.Label9);
            base.Controls.Add(this.csSet);
            base.Controls.Add(this.Label7);
            base.Controls.Add(this.Label5);
            base.Controls.Add(this.csIO);
            base.Controls.Add(this.Label4);
            base.Controls.Add(this.Label1);
            base.Controls.Add(this.txtName);
            base.Controls.Add(this.csSlots);
            base.Controls.Add(this.csLevel);
            base.Controls.Add(this.csHeading);
            base.Controls.Add(this.csTitle);
            base.Controls.Add(this.Label21);
            base.Controls.Add(this.Label22);
            base.Controls.Add(this.Label20);
            base.Controls.Add(this.Label19);
            base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmExportColor";
            base.ShowInTaskbar = false;
            base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Colour Scheme Editor";
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        global::System.ComponentModel.IContainer components;
    }
}
