namespace Hero_Designer
{
	// Token: 0x0200002D RID: 45
	public partial class frmEditPower : global::System.Windows.Forms.Form
	{
		// Token: 0x06000752 RID: 1874 RVA: 0x0004A894 File Offset: 0x00048A94
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06000767 RID: 1895 RVA: 0x0004C468 File Offset: 0x0004A668
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmEditPower));
			this.tcPower = new global::System.Windows.Forms.TabControl();
			this.tpText = new global::System.Windows.Forms.TabPage();
			this.chkNoAUReq = new global::System.Windows.Forms.CheckBox();
			this.chkNoAutoUpdate = new global::System.Windows.Forms.CheckBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.chkSortOverride = new global::System.Windows.Forms.CheckBox();
			this.chkSubInclude = new global::System.Windows.Forms.CheckBox();
			this.chkAlwaysToggle = new global::System.Windows.Forms.CheckBox();
			this.chkBuffCycle = new global::System.Windows.Forms.CheckBox();
			this.chkGraphFix = new global::System.Windows.Forms.CheckBox();
			this.chkAltSub = new global::System.Windows.Forms.CheckBox();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.txtVisualLocation = new global::System.Windows.Forms.TextBox();
			this.GroupBox7 = new global::System.Windows.Forms.GroupBox();
			this.cbForcedClass = new global::System.Windows.Forms.ComboBox();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.chkSummonDisplayEntity = new global::System.Windows.Forms.CheckBox();
			this.chkSummonStealAttributes = new global::System.Windows.Forms.CheckBox();
			this.chkSummonStealEffects = new global::System.Windows.Forms.CheckBox();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.txtDescLong = new global::System.Windows.Forms.TextBox();
			this.txtDescShort = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.udScaleMax = new global::System.Windows.Forms.NumericUpDown();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.udScaleMin = new global::System.Windows.Forms.NumericUpDown();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.txtScaleName = new global::System.Windows.Forms.TextBox();
			this.chkScale = new global::System.Windows.Forms.CheckBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.lblStaticIndex = new global::System.Windows.Forms.Label();
			this.chkHidden = new global::System.Windows.Forms.CheckBox();
			this.lblNameUnique = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.lblNameFull = new global::System.Windows.Forms.Label();
			this.cbNameSet = new global::System.Windows.Forms.ComboBox();
			this.txtNameDisplay = new global::System.Windows.Forms.TextBox();
			this.cbNameGroup = new global::System.Windows.Forms.ComboBox();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.txtNamePower = new global::System.Windows.Forms.TextBox();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.tpBasic = new global::System.Windows.Forms.TabPage();
			this.Label46 = new global::System.Windows.Forms.Label();
			this.Label47 = new global::System.Windows.Forms.Label();
			this.txtLifeTimeReal = new global::System.Windows.Forms.TextBox();
			this.Label44 = new global::System.Windows.Forms.Label();
			this.Label45 = new global::System.Windows.Forms.Label();
			this.txtLifeTimeGame = new global::System.Windows.Forms.TextBox();
			this.Label42 = new global::System.Windows.Forms.Label();
			this.Label43 = new global::System.Windows.Forms.Label();
			this.txtUseageTime = new global::System.Windows.Forms.TextBox();
			this.Label41 = new global::System.Windows.Forms.Label();
			this.txtNumCharges = new global::System.Windows.Forms.TextBox();
			this.chkIgnoreStrength = new global::System.Windows.Forms.CheckBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.txtRangeSec = new global::System.Windows.Forms.TextBox();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.GroupBox9 = new global::System.Windows.Forms.GroupBox();
			this.rbFlagCastThrough = new global::System.Windows.Forms.RadioButton();
			this.rbFlagDisallow = new global::System.Windows.Forms.RadioButton();
			this.rbFlagRequired = new global::System.Windows.Forms.RadioButton();
			this.rbFlagVector = new global::System.Windows.Forms.RadioButton();
			this.rbFlagCast = new global::System.Windows.Forms.RadioButton();
			this.clbFlags = new global::System.Windows.Forms.CheckedListBox();
			this.rbFlagTargetsSec = new global::System.Windows.Forms.RadioButton();
			this.rbFlagTargets = new global::System.Windows.Forms.RadioButton();
			this.rbFlagAffected = new global::System.Windows.Forms.RadioButton();
			this.rbFlagAutoHit = new global::System.Windows.Forms.RadioButton();
			this.cbNotify = new global::System.Windows.Forms.ComboBox();
			this.chkLos = new global::System.Windows.Forms.CheckBox();
			this.txtMaxTargets = new global::System.Windows.Forms.TextBox();
			this.lblEndCost = new global::System.Windows.Forms.Label();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.lblAcc = new global::System.Windows.Forms.Label();
			this.Label40 = new global::System.Windows.Forms.Label();
			this.Label39 = new global::System.Windows.Forms.Label();
			this.Label38 = new global::System.Windows.Forms.Label();
			this.Label37 = new global::System.Windows.Forms.Label();
			this.Label36 = new global::System.Windows.Forms.Label();
			this.Label35 = new global::System.Windows.Forms.Label();
			this.Label34 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.txtArc = new global::System.Windows.Forms.TextBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.txtRadius = new global::System.Windows.Forms.TextBox();
			this.txtLevel = new global::System.Windows.Forms.TextBox();
			this.cbEffectArea = new global::System.Windows.Forms.ComboBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.txtEndCost = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.txtActivate = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.txtRechargeTime = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.txtCastTime = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.txtInterrupt = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.txtRange = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.txtAcc = new global::System.Windows.Forms.TextBox();
			this.cbPowerType = new global::System.Windows.Forms.ComboBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.tpEffects = new global::System.Windows.Forms.TabPage();
			this.lvFX = new global::System.Windows.Forms.ListBox();
			this.pnlFX = new global::System.Windows.Forms.Panel();
			this.btnSetDamage = new global::System.Windows.Forms.Button();
			this.btnFXEdit = new global::System.Windows.Forms.Button();
			this.btnFXDown = new global::System.Windows.Forms.Button();
			this.btnFXUp = new global::System.Windows.Forms.Button();
			this.btnFXRemove = new global::System.Windows.Forms.Button();
			this.btnFXDuplicate = new global::System.Windows.Forms.Button();
			this.btnFXAdd = new global::System.Windows.Forms.Button();
			this.tpEnh = new global::System.Windows.Forms.TabPage();
			this.chkBoostUsePlayerLevel = new global::System.Windows.Forms.CheckBox();
			this.chkBoostBoostable = new global::System.Windows.Forms.CheckBox();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.pbEnhancements = new global::System.Windows.Forms.PictureBox();
			this.chkPRFrontLoad = new global::System.Windows.Forms.CheckBox();
			this.pbEnhancementList = new global::System.Windows.Forms.PictureBox();
			this.lblEnhName = new global::System.Windows.Forms.Label();
			this.tpSets = new global::System.Windows.Forms.TabPage();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.lblInvSet = new global::System.Windows.Forms.Label();
			this.pbInvSetList = new global::System.Windows.Forms.PictureBox();
			this.pbInvSetUsed = new global::System.Windows.Forms.PictureBox();
			this.tpPreReq = new global::System.Windows.Forms.TabPage();
			this.GroupBox11 = new global::System.Windows.Forms.GroupBox();
			this.btnPrReset = new global::System.Windows.Forms.Button();
			this.btnPrSetNone = new global::System.Windows.Forms.Button();
			this.btnPrDown = new global::System.Windows.Forms.Button();
			this.btnPrUp = new global::System.Windows.Forms.Button();
			this.rbPrRemove = new global::System.Windows.Forms.Button();
			this.rbPrAdd = new global::System.Windows.Forms.Button();
			this.rbPrPowerB = new global::System.Windows.Forms.RadioButton();
			this.rbPrPowerA = new global::System.Windows.Forms.RadioButton();
			this.lvPrPower = new global::System.Windows.Forms.ListView();
			this.ColumnHeader9 = new global::System.Windows.Forms.ColumnHeader();
			this.lvPrSet = new global::System.Windows.Forms.ListView();
			this.ColumnHeader10 = new global::System.Windows.Forms.ColumnHeader();
			this.lvPrGroup = new global::System.Windows.Forms.ListView();
			this.ColumnHeader11 = new global::System.Windows.Forms.ColumnHeader();
			this.lvPrListing = new global::System.Windows.Forms.ListView();
			this.ColumnHeader6 = new global::System.Windows.Forms.ColumnHeader();
			this.ColumnHeader7 = new global::System.Windows.Forms.ColumnHeader();
			this.ColumnHeader8 = new global::System.Windows.Forms.ColumnHeader();
			this.GroupBox10 = new global::System.Windows.Forms.GroupBox();
			this.clbClassExclude = new global::System.Windows.Forms.CheckedListBox();
			this.GroupBox8 = new global::System.Windows.Forms.GroupBox();
			this.clbClassReq = new global::System.Windows.Forms.CheckedListBox();
			this.tpSpecialEnh = new global::System.Windows.Forms.TabPage();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.lvDisablePass4 = new global::System.Windows.Forms.ListBox();
			this.lvDisablePass1 = new global::System.Windows.Forms.ListBox();
			this.tpMutex = new global::System.Windows.Forms.TabPage();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.btnMutexAdd = new global::System.Windows.Forms.Button();
			this.clbMutex = new global::System.Windows.Forms.CheckedListBox();
			this.chkMutexAuto = new global::System.Windows.Forms.CheckBox();
			this.chkMutexSkip = new global::System.Windows.Forms.CheckBox();
			this.tpSubPower = new global::System.Windows.Forms.TabPage();
			this.btnSPAdd = new global::System.Windows.Forms.Button();
			this.btnSPRemove = new global::System.Windows.Forms.Button();
			this.lvSPSelected = new global::System.Windows.Forms.ListView();
			this.ColumnHeader4 = new global::System.Windows.Forms.ColumnHeader();
			this.lvSPPower = new global::System.Windows.Forms.ListView();
			this.ColumnHeader1 = new global::System.Windows.Forms.ColumnHeader();
			this.lvSPSet = new global::System.Windows.Forms.ListView();
			this.ColumnHeader2 = new global::System.Windows.Forms.ColumnHeader();
			this.lvSPGroup = new global::System.Windows.Forms.ListView();
			this.ColumnHeader3 = new global::System.Windows.Forms.ColumnHeader();
			this.btnOK = new global::System.Windows.Forms.Button();
			this.btnCancel = new global::System.Windows.Forms.Button();
			this.btnFullPaste = new global::System.Windows.Forms.Button();
			this.btnFullCopy = new global::System.Windows.Forms.Button();
			this.btnCSVImport = new global::System.Windows.Forms.Button();
			this.tcPower.SuspendLayout();
			this.tpText.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox7.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.udScaleMax.BeginInit();
			this.udScaleMin.BeginInit();
			this.GroupBox1.SuspendLayout();
			this.tpBasic.SuspendLayout();
			this.GroupBox9.SuspendLayout();
			this.tpEffects.SuspendLayout();
			this.pnlFX.SuspendLayout();
			this.tpEnh.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbEnhancements).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbEnhancementList).BeginInit();
			this.tpSets.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbInvSetList).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbInvSetUsed).BeginInit();
			this.tpPreReq.SuspendLayout();
			this.GroupBox11.SuspendLayout();
			this.GroupBox10.SuspendLayout();
			this.GroupBox8.SuspendLayout();
			this.tpSpecialEnh.SuspendLayout();
			this.tpMutex.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.tpSubPower.SuspendLayout();
			base.SuspendLayout();
			this.tcPower.Controls.Add(this.tpText);
			this.tcPower.Controls.Add(this.tpBasic);
			this.tcPower.Controls.Add(this.tpEffects);
			this.tcPower.Controls.Add(this.tpEnh);
			this.tcPower.Controls.Add(this.tpSets);
			this.tcPower.Controls.Add(this.tpPreReq);
			this.tcPower.Controls.Add(this.tpSpecialEnh);
			this.tcPower.Controls.Add(this.tpMutex);
			this.tcPower.Controls.Add(this.tpSubPower);
			global::System.Drawing.Point point = new global::System.Drawing.Point(8, 8);
			this.tcPower.Location = point;
			this.tcPower.Name = "tcPower";
			this.tcPower.SelectedIndex = 0;
			global::System.Drawing.Size size = new global::System.Drawing.Size(840, 364);
			this.tcPower.Size = size;
			this.tcPower.TabIndex = 2;
			this.tpText.Controls.Add(this.chkNoAUReq);
			this.tpText.Controls.Add(this.chkNoAutoUpdate);
			this.tpText.Controls.Add(this.GroupBox4);
			this.tpText.Controls.Add(this.GroupBox7);
			this.tpText.Controls.Add(this.GroupBox6);
			this.tpText.Controls.Add(this.GroupBox5);
			this.tpText.Controls.Add(this.GroupBox3);
			this.tpText.Controls.Add(this.GroupBox1);
			point = new global::System.Drawing.Point(4, 23);
			this.tpText.Location = point;
			this.tpText.Name = "tpText";
			size = new global::System.Drawing.Size(832, 337);
			this.tpText.Size = size;
			this.tpText.TabIndex = 2;
			this.tpText.Text = "Basic";
			this.tpText.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(332, 293);
			this.chkNoAUReq.Location = point;
			this.chkNoAUReq.Name = "chkNoAUReq";
			size = new global::System.Drawing.Size(269, 33);
			this.chkNoAUReq.Size = size;
			this.chkNoAUReq.TabIndex = 46;
			this.chkNoAUReq.Text = "Do not automatically update this power's requirements";
			this.chkNoAUReq.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(13, 306);
			this.chkNoAutoUpdate.Location = point;
			this.chkNoAutoUpdate.Name = "chkNoAutoUpdate";
			size = new global::System.Drawing.Size(313, 20);
			this.chkNoAutoUpdate.Size = size;
			this.chkNoAutoUpdate.TabIndex = 23;
			this.chkNoAutoUpdate.Text = "Do not automatically update this power during bulk-imports";
			this.chkNoAutoUpdate.UseVisualStyleBackColor = true;
			this.GroupBox4.Controls.Add(this.chkSortOverride);
			this.GroupBox4.Controls.Add(this.chkSubInclude);
			this.GroupBox4.Controls.Add(this.chkAlwaysToggle);
			this.GroupBox4.Controls.Add(this.chkBuffCycle);
			this.GroupBox4.Controls.Add(this.chkGraphFix);
			this.GroupBox4.Controls.Add(this.chkAltSub);
			this.GroupBox4.Controls.Add(this.Label21);
			this.GroupBox4.Controls.Add(this.txtVisualLocation);
			point = new global::System.Drawing.Point(607, 115);
			this.GroupBox4.Location = point;
			this.GroupBox4.Name = "GroupBox4";
			size = new global::System.Drawing.Size(214, 211);
			this.GroupBox4.Size = size;
			this.GroupBox4.TabIndex = 45;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "MxD Special Flags";
			point = new global::System.Drawing.Point(6, 96);
			this.chkSortOverride.Location = point;
			this.chkSortOverride.Name = "chkSortOverride";
			size = new global::System.Drawing.Size(184, 22);
			this.chkSortOverride.Size = size;
			this.chkSortOverride.TabIndex = 42;
			this.chkSortOverride.Text = "Priority Sort Order";
			this.chkSortOverride.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(6, 152);
			this.chkSubInclude.Location = point;
			this.chkSubInclude.Name = "chkSubInclude";
			size = new global::System.Drawing.Size(153, 20);
			this.chkSubInclude.Size = size;
			this.chkSubInclude.TabIndex = 4;
			this.chkSubInclude.Text = "Sub-Power Include Flag";
			this.chkSubInclude.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(6, 42);
			this.chkAlwaysToggle.Location = point;
			this.chkAlwaysToggle.Name = "chkAlwaysToggle";
			size = new global::System.Drawing.Size(168, 20);
			this.chkAlwaysToggle.Size = size;
			this.chkAlwaysToggle.TabIndex = 1;
			this.chkAlwaysToggle.Text = "Toggle Defaults to ON";
			point = new global::System.Drawing.Point(6, 16);
			this.chkBuffCycle.Location = point;
			this.chkBuffCycle.Name = "chkBuffCycle";
			size = new global::System.Drawing.Size(168, 20);
			this.chkBuffCycle.Size = size;
			this.chkBuffCycle.TabIndex = 0;
			this.chkBuffCycle.Text = "Power is a Click-Buff";
			point = new global::System.Drawing.Point(6, 68);
			this.chkGraphFix.Location = point;
			this.chkGraphFix.Name = "chkGraphFix";
			size = new global::System.Drawing.Size(184, 22);
			this.chkGraphFix.Size = size;
			this.chkGraphFix.TabIndex = 2;
			this.chkGraphFix.Text = "Ignore when setting graph scale";
			this.chkGraphFix.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(6, 124);
			this.chkAltSub.Location = point;
			this.chkAltSub.Name = "chkAltSub";
			size = new global::System.Drawing.Size(183, 22);
			this.chkAltSub.Size = size;
			this.chkAltSub.TabIndex = 3;
			this.chkAltSub.Text = "Sub-Power Colour Flag (ToDo)";
			this.chkAltSub.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(21, 178);
			this.Label21.Location = point;
			this.Label21.Name = "Label21";
			size = new global::System.Drawing.Size(88, 20);
			this.Label21.Size = size;
			this.Label21.TabIndex = 41;
			this.Label21.Text = "Inherent Index:";
			this.Label21.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(113, 178);
			this.txtVisualLocation.Location = point;
			this.txtVisualLocation.Name = "txtVisualLocation";
			size = new global::System.Drawing.Size(76, 20);
			this.txtVisualLocation.Size = size;
			this.txtVisualLocation.TabIndex = 5;
			this.txtVisualLocation.Text = "0";
			this.GroupBox7.Controls.Add(this.cbForcedClass);
			this.GroupBox7.Controls.Add(this.Label29);
			point = new global::System.Drawing.Point(332, 211);
			this.GroupBox7.Location = point;
			this.GroupBox7.Name = "GroupBox7";
			size = new global::System.Drawing.Size(269, 74);
			this.GroupBox7.Size = size;
			this.GroupBox7.TabIndex = 22;
			this.GroupBox7.TabStop = false;
			this.GroupBox7.Text = "Forced Class";
			this.cbForcedClass.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cbForcedClass.FormattingEnabled = true;
			point = new global::System.Drawing.Point(88, 30);
			this.cbForcedClass.Location = point;
			this.cbForcedClass.Name = "cbForcedClass";
			size = new global::System.Drawing.Size(175, 22);
			this.cbForcedClass.Size = size;
			this.cbForcedClass.TabIndex = 0;
			point = new global::System.Drawing.Point(7, 30);
			this.Label29.Location = point;
			this.Label29.Name = "Label29";
			size = new global::System.Drawing.Size(77, 20);
			this.Label29.Size = size;
			this.Label29.TabIndex = 18;
			this.Label29.Text = "Class Name:";
			this.Label29.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.GroupBox6.Controls.Add(this.chkSummonDisplayEntity);
			this.GroupBox6.Controls.Add(this.chkSummonStealAttributes);
			this.GroupBox6.Controls.Add(this.chkSummonStealEffects);
			point = new global::System.Drawing.Point(332, 115);
			this.GroupBox6.Location = point;
			this.GroupBox6.Name = "GroupBox6";
			size = new global::System.Drawing.Size(269, 90);
			this.GroupBox6.Size = size;
			this.GroupBox6.TabIndex = 21;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "Summon Handling";
			point = new global::System.Drawing.Point(6, 68);
			this.chkSummonDisplayEntity.Location = point;
			this.chkSummonDisplayEntity.Name = "chkSummonDisplayEntity";
			size = new global::System.Drawing.Size(257, 20);
			this.chkSummonDisplayEntity.Size = size;
			this.chkSummonDisplayEntity.TabIndex = 2;
			this.chkSummonDisplayEntity.Text = "Display entity even if absorbed";
			this.chkSummonDisplayEntity.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(6, 42);
			this.chkSummonStealAttributes.Location = point;
			this.chkSummonStealAttributes.Name = "chkSummonStealAttributes";
			size = new global::System.Drawing.Size(257, 20);
			this.chkSummonStealAttributes.Size = size;
			this.chkSummonStealAttributes.TabIndex = 1;
			this.chkSummonStealAttributes.Text = "Power absorbs summoned entity's attributes\r\n";
			this.chkSummonStealAttributes.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(6, 16);
			this.chkSummonStealEffects.Location = point;
			this.chkSummonStealEffects.Name = "chkSummonStealEffects";
			size = new global::System.Drawing.Size(257, 20);
			this.chkSummonStealEffects.Size = size;
			this.chkSummonStealEffects.TabIndex = 0;
			this.chkSummonStealEffects.Text = "Power absorbs summoned entity's effects";
			this.chkSummonStealEffects.UseVisualStyleBackColor = true;
			this.GroupBox5.Controls.Add(this.txtDescLong);
			this.GroupBox5.Controls.Add(this.txtDescShort);
			this.GroupBox5.Controls.Add(this.Label2);
			this.GroupBox5.Controls.Add(this.Label3);
			point = new global::System.Drawing.Point(332, 3);
			this.GroupBox5.Location = point;
			this.GroupBox5.Name = "GroupBox5";
			size = new global::System.Drawing.Size(489, 106);
			this.GroupBox5.Size = size;
			this.GroupBox5.TabIndex = 20;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Descriptions";
			point = new global::System.Drawing.Point(58, 42);
			this.txtDescLong.Location = point;
			this.txtDescLong.Multiline = true;
			this.txtDescLong.Name = "txtDescLong";
			this.txtDescLong.ScrollBars = global::System.Windows.Forms.ScrollBars.Vertical;
			size = new global::System.Drawing.Size(425, 57);
			this.txtDescLong.Size = size;
			this.txtDescLong.TabIndex = 1;
			this.txtDescLong.Text = "Power Desc Long";
			point = new global::System.Drawing.Point(58, 16);
			this.txtDescShort.Location = point;
			this.txtDescShort.Name = "txtDescShort";
			size = new global::System.Drawing.Size(425, 20);
			this.txtDescShort.Size = size;
			this.txtDescShort.TabIndex = 0;
			this.txtDescShort.Text = "Power Desc Short";
			point = new global::System.Drawing.Point(6, 16);
			this.Label2.Location = point;
			this.Label2.Name = "Label2";
			size = new global::System.Drawing.Size(48, 20);
			this.Label2.Size = size;
			this.Label2.TabIndex = 3;
			this.Label2.Text = "Short:";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(6, 42);
			this.Label3.Location = point;
			this.Label3.Name = "Label3";
			size = new global::System.Drawing.Size(48, 20);
			this.Label3.Size = size;
			this.Label3.TabIndex = 5;
			this.Label3.Text = "Long";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.GroupBox3.Controls.Add(this.Label28);
			this.GroupBox3.Controls.Add(this.udScaleMax);
			this.GroupBox3.Controls.Add(this.Label27);
			this.GroupBox3.Controls.Add(this.udScaleMin);
			this.GroupBox3.Controls.Add(this.Label26);
			this.GroupBox3.Controls.Add(this.txtScaleName);
			this.GroupBox3.Controls.Add(this.chkScale);
			point = new global::System.Drawing.Point(13, 199);
			this.GroupBox3.Location = point;
			this.GroupBox3.Name = "GroupBox3";
			size = new global::System.Drawing.Size(313, 101);
			this.GroupBox3.Size = size;
			this.GroupBox3.TabIndex = 8;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Power Scaling";
			point = new global::System.Drawing.Point(181, 72);
			this.Label28.Location = point;
			this.Label28.Name = "Label28";
			size = new global::System.Drawing.Size(52, 20);
			this.Label28.Size = size;
			this.Label28.TabIndex = 7;
			this.Label28.Text = "To";
			this.Label28.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			point = new global::System.Drawing.Point(239, 72);
			this.udScaleMax.Location = point;
			this.udScaleMax.Name = "udScaleMax";
			size = new global::System.Drawing.Size(63, 20);
			this.udScaleMax.Size = size;
			this.udScaleMax.TabIndex = 3;
			point = new global::System.Drawing.Point(5, 72);
			this.Label27.Location = point;
			this.Label27.Name = "Label27";
			size = new global::System.Drawing.Size(101, 20);
			this.Label27.Size = size;
			this.Label27.TabIndex = 5;
			this.Label27.Text = "Scale Range:";
			this.Label27.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(112, 72);
			this.udScaleMin.Location = point;
			this.udScaleMin.Name = "udScaleMin";
			size = new global::System.Drawing.Size(63, 20);
			this.udScaleMin.Size = size;
			this.udScaleMin.TabIndex = 2;
			point = new global::System.Drawing.Point(5, 46);
			this.Label26.Location = point;
			this.Label26.Name = "Label26";
			size = new global::System.Drawing.Size(101, 20);
			this.Label26.Size = size;
			this.Label26.TabIndex = 3;
			this.Label26.Text = "Scaling Variable:";
			this.Label26.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(112, 46);
			this.txtScaleName.Location = point;
			this.txtScaleName.Name = "txtScaleName";
			size = new global::System.Drawing.Size(190, 20);
			this.txtScaleName.Size = size;
			this.txtScaleName.TabIndex = 1;
			this.txtScaleName.Text = "Foes Hit";
			point = new global::System.Drawing.Point(6, 19);
			this.chkScale.Location = point;
			this.chkScale.Name = "chkScale";
			size = new global::System.Drawing.Size(302, 21);
			this.chkScale.Size = size;
			this.chkScale.TabIndex = 0;
			this.chkScale.Text = "Enable scaling for this power";
			this.chkScale.UseVisualStyleBackColor = true;
			this.GroupBox1.Controls.Add(this.lblStaticIndex);
			this.GroupBox1.Controls.Add(this.chkHidden);
			this.GroupBox1.Controls.Add(this.lblNameUnique);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.lblNameFull);
			this.GroupBox1.Controls.Add(this.cbNameSet);
			this.GroupBox1.Controls.Add(this.txtNameDisplay);
			this.GroupBox1.Controls.Add(this.cbNameGroup);
			this.GroupBox1.Controls.Add(this.Label22);
			this.GroupBox1.Controls.Add(this.Label31);
			this.GroupBox1.Controls.Add(this.txtNamePower);
			this.GroupBox1.Controls.Add(this.Label33);
			point = new global::System.Drawing.Point(13, 3);
			this.GroupBox1.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			size = new global::System.Drawing.Size(313, 190);
			this.GroupBox1.Size = size;
			this.GroupBox1.TabIndex = 19;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Name";
			this.lblStaticIndex.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			point = new global::System.Drawing.Point(6, 42);
			this.lblStaticIndex.Location = point;
			this.lblStaticIndex.Name = "lblStaticIndex";
			size = new global::System.Drawing.Size(56, 20);
			this.lblStaticIndex.Size = size;
			this.lblStaticIndex.TabIndex = 25;
			this.lblStaticIndex.Text = "000";
			this.lblStaticIndex.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			point = new global::System.Drawing.Point(5, 69);
			this.chkHidden.Location = point;
			this.chkHidden.Name = "chkHidden";
			size = new global::System.Drawing.Size(57, 25);
			this.chkHidden.Size = size;
			this.chkHidden.TabIndex = 24;
			this.chkHidden.Text = "Hide";
			this.chkHidden.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(6, 163);
			this.lblNameUnique.Location = point;
			this.lblNameUnique.Name = "lblNameUnique";
			size = new global::System.Drawing.Size(296, 20);
			this.lblNameUnique.Size = size;
			this.lblNameUnique.TabIndex = 19;
			this.lblNameUnique.Text = "This name is unique.";
			this.lblNameUnique.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			point = new global::System.Drawing.Point(6, 16);
			this.Label1.Location = point;
			this.Label1.Name = "Label1";
			size = new global::System.Drawing.Size(96, 20);
			this.Label1.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "Display Name:";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lblNameFull.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			point = new global::System.Drawing.Point(9, 127);
			this.lblNameFull.Location = point;
			this.lblNameFull.Name = "lblNameFull";
			size = new global::System.Drawing.Size(293, 32);
			this.lblNameFull.Size = size;
			this.lblNameFull.TabIndex = 16;
			this.lblNameFull.Text = "Group_Name.Powerset_Name.Power_Name";
			this.lblNameFull.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.cbNameSet.FormattingEnabled = true;
			point = new global::System.Drawing.Point(106, 70);
			this.cbNameSet.Location = point;
			this.cbNameSet.Name = "cbNameSet";
			size = new global::System.Drawing.Size(196, 22);
			this.cbNameSet.Size = size;
			this.cbNameSet.TabIndex = 2;
			point = new global::System.Drawing.Point(106, 16);
			this.txtNameDisplay.Location = point;
			this.txtNameDisplay.Name = "txtNameDisplay";
			size = new global::System.Drawing.Size(196, 20);
			this.txtNameDisplay.Size = size;
			this.txtNameDisplay.TabIndex = 0;
			this.txtNameDisplay.Text = "PowerName";
			this.cbNameGroup.FormattingEnabled = true;
			point = new global::System.Drawing.Point(106, 42);
			this.cbNameGroup.Location = point;
			this.cbNameGroup.Name = "cbNameGroup";
			size = new global::System.Drawing.Size(196, 22);
			this.cbNameGroup.Size = size;
			this.cbNameGroup.TabIndex = 1;
			point = new global::System.Drawing.Point(53, 42);
			this.Label22.Location = point;
			this.Label22.Name = "Label22";
			size = new global::System.Drawing.Size(49, 20);
			this.Label22.Size = size;
			this.Label22.TabIndex = 10;
			this.Label22.Text = "Group:";
			this.Label22.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(65, 70);
			this.Label31.Location = point;
			this.Label31.Name = "Label31";
			size = new global::System.Drawing.Size(35, 20);
			this.Label31.Size = size;
			this.Label31.TabIndex = 12;
			this.Label31.Text = "Set:";
			this.Label31.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(106, 98);
			this.txtNamePower.Location = point;
			this.txtNamePower.Name = "txtNamePower";
			size = new global::System.Drawing.Size(196, 20);
			this.txtNamePower.Size = size;
			this.txtNamePower.TabIndex = 3;
			this.txtNamePower.Text = "PowerName";
			point = new global::System.Drawing.Point(14, 98);
			this.Label33.Location = point;
			this.Label33.Name = "Label33";
			size = new global::System.Drawing.Size(86, 20);
			this.Label33.Size = size;
			this.Label33.TabIndex = 14;
			this.Label33.Text = "Power Name:";
			this.Label33.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.tpBasic.Controls.Add(this.Label46);
			this.tpBasic.Controls.Add(this.Label47);
			this.tpBasic.Controls.Add(this.txtLifeTimeReal);
			this.tpBasic.Controls.Add(this.Label44);
			this.tpBasic.Controls.Add(this.Label45);
			this.tpBasic.Controls.Add(this.txtLifeTimeGame);
			this.tpBasic.Controls.Add(this.Label42);
			this.tpBasic.Controls.Add(this.Label43);
			this.tpBasic.Controls.Add(this.txtUseageTime);
			this.tpBasic.Controls.Add(this.Label41);
			this.tpBasic.Controls.Add(this.txtNumCharges);
			this.tpBasic.Controls.Add(this.chkIgnoreStrength);
			this.tpBasic.Controls.Add(this.Label12);
			this.tpBasic.Controls.Add(this.Label17);
			this.tpBasic.Controls.Add(this.txtRangeSec);
			this.tpBasic.Controls.Add(this.Label18);
			this.tpBasic.Controls.Add(this.GroupBox9);
			this.tpBasic.Controls.Add(this.cbNotify);
			this.tpBasic.Controls.Add(this.chkLos);
			this.tpBasic.Controls.Add(this.txtMaxTargets);
			this.tpBasic.Controls.Add(this.lblEndCost);
			this.tpBasic.Controls.Add(this.Label20);
			this.tpBasic.Controls.Add(this.lblAcc);
			this.tpBasic.Controls.Add(this.Label40);
			this.tpBasic.Controls.Add(this.Label39);
			this.tpBasic.Controls.Add(this.Label38);
			this.tpBasic.Controls.Add(this.Label37);
			this.tpBasic.Controls.Add(this.Label36);
			this.tpBasic.Controls.Add(this.Label35);
			this.tpBasic.Controls.Add(this.Label34);
			this.tpBasic.Controls.Add(this.Label16);
			this.tpBasic.Controls.Add(this.txtArc);
			this.tpBasic.Controls.Add(this.Label15);
			this.tpBasic.Controls.Add(this.txtRadius);
			this.tpBasic.Controls.Add(this.txtLevel);
			this.tpBasic.Controls.Add(this.cbEffectArea);
			this.tpBasic.Controls.Add(this.Label14);
			this.tpBasic.Controls.Add(this.Label13);
			this.tpBasic.Controls.Add(this.txtEndCost);
			this.tpBasic.Controls.Add(this.Label10);
			this.tpBasic.Controls.Add(this.txtActivate);
			this.tpBasic.Controls.Add(this.Label11);
			this.tpBasic.Controls.Add(this.txtRechargeTime);
			this.tpBasic.Controls.Add(this.Label8);
			this.tpBasic.Controls.Add(this.txtCastTime);
			this.tpBasic.Controls.Add(this.Label9);
			this.tpBasic.Controls.Add(this.txtInterrupt);
			this.tpBasic.Controls.Add(this.Label7);
			this.tpBasic.Controls.Add(this.txtRange);
			this.tpBasic.Controls.Add(this.Label6);
			this.tpBasic.Controls.Add(this.txtAcc);
			this.tpBasic.Controls.Add(this.cbPowerType);
			this.tpBasic.Controls.Add(this.Label5);
			this.tpBasic.Controls.Add(this.Label4);
			point = new global::System.Drawing.Point(4, 23);
			this.tpBasic.Location = point;
			this.tpBasic.Name = "tpBasic";
			size = new global::System.Drawing.Size(832, 337);
			this.tpBasic.Size = size;
			this.tpBasic.TabIndex = 0;
			this.tpBasic.Text = "Power Attributes";
			this.tpBasic.UseVisualStyleBackColor = true;
			this.tpBasic.Visible = false;
			point = new global::System.Drawing.Point(447, 219);
			this.Label46.Location = point;
			this.Label46.Name = "Label46";
			size = new global::System.Drawing.Size(20, 20);
			this.Label46.Size = size;
			this.Label46.TabIndex = 118;
			this.Label46.Text = "s";
			this.Label46.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(256, 219);
			this.Label47.Location = point;
			this.Label47.Name = "Label47";
			size = new global::System.Drawing.Size(124, 20);
			this.Label47.Size = size;
			this.Label47.TabIndex = 117;
			this.Label47.Text = "Life Time Real-World:";
			this.Label47.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(384, 219);
			this.txtLifeTimeReal.Location = point;
			this.txtLifeTimeReal.Name = "txtLifeTimeReal";
			size = new global::System.Drawing.Size(57, 20);
			this.txtLifeTimeReal.Size = size;
			this.txtLifeTimeReal.TabIndex = 116;
			this.txtLifeTimeReal.Text = "1";
			this.txtLifeTimeReal.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(447, 193);
			this.Label44.Location = point;
			this.Label44.Name = "Label44";
			size = new global::System.Drawing.Size(20, 20);
			this.Label44.Size = size;
			this.Label44.TabIndex = 115;
			this.Label44.Text = "s";
			this.Label44.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(256, 193);
			this.Label45.Location = point;
			this.Label45.Name = "Label45";
			size = new global::System.Drawing.Size(124, 20);
			this.Label45.Size = size;
			this.Label45.TabIndex = 114;
			this.Label45.Text = "Life Time In-Game:";
			this.Label45.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(384, 193);
			this.txtLifeTimeGame.Location = point;
			this.txtLifeTimeGame.Name = "txtLifeTimeGame";
			size = new global::System.Drawing.Size(57, 20);
			this.txtLifeTimeGame.Size = size;
			this.txtLifeTimeGame.TabIndex = 113;
			this.txtLifeTimeGame.Text = "1";
			this.txtLifeTimeGame.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(447, 167);
			this.Label42.Location = point;
			this.Label42.Name = "Label42";
			size = new global::System.Drawing.Size(20, 20);
			this.Label42.Size = size;
			this.Label42.TabIndex = 112;
			this.Label42.Text = "s";
			this.Label42.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(256, 167);
			this.Label43.Location = point;
			this.Label43.Name = "Label43";
			size = new global::System.Drawing.Size(124, 20);
			this.Label43.Size = size;
			this.Label43.TabIndex = 111;
			this.Label43.Text = "Usage Time:";
			this.Label43.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(384, 167);
			this.txtUseageTime.Location = point;
			this.txtUseageTime.Name = "txtUseageTime";
			size = new global::System.Drawing.Size(57, 20);
			this.txtUseageTime.Size = size;
			this.txtUseageTime.TabIndex = 110;
			this.txtUseageTime.Text = "1";
			this.txtUseageTime.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(256, 141);
			this.Label41.Location = point;
			this.Label41.Name = "Label41";
			size = new global::System.Drawing.Size(124, 20);
			this.Label41.Size = size;
			this.Label41.TabIndex = 108;
			this.Label41.Text = "Charge Count:";
			this.Label41.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(384, 141);
			this.txtNumCharges.Location = point;
			this.txtNumCharges.Name = "txtNumCharges";
			size = new global::System.Drawing.Size(57, 20);
			this.txtNumCharges.Size = size;
			this.txtNumCharges.TabIndex = 107;
			this.txtNumCharges.Text = "1";
			this.txtNumCharges.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.chkIgnoreStrength.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.chkIgnoreStrength.Checked = true;
			this.chkIgnoreStrength.CheckState = global::System.Windows.Forms.CheckState.Checked;
			point = new global::System.Drawing.Point(256, 116);
			this.chkIgnoreStrength.Location = point;
			this.chkIgnoreStrength.Name = "chkIgnoreStrength";
			size = new global::System.Drawing.Size(223, 20);
			this.chkIgnoreStrength.Size = size;
			this.chkIgnoreStrength.TabIndex = 16;
			this.chkIgnoreStrength.Text = "Ignore Strength";
			this.chkIgnoreStrength.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(180, 219);
			this.Label12.Location = point;
			this.Label12.Name = "Label12";
			size = new global::System.Drawing.Size(20, 20);
			this.Label12.Size = size;
			this.Label12.TabIndex = 106;
			this.Label12.Text = "ft";
			this.Label12.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(9, 219);
			this.Label17.Location = point;
			this.Label17.Name = "Label17";
			size = new global::System.Drawing.Size(104, 20);
			this.Label17.Size = size;
			this.Label17.TabIndex = 105;
			this.Label17.Text = "Secondary  Range:";
			this.Label17.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 219);
			this.txtRangeSec.Location = point;
			this.txtRangeSec.Name = "txtRangeSec";
			size = new global::System.Drawing.Size(57, 20);
			this.txtRangeSec.Size = size;
			this.txtRangeSec.TabIndex = 8;
			this.txtRangeSec.Text = "1.0";
			this.txtRangeSec.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(256, 63);
			this.Label18.Location = point;
			this.Label18.Name = "Label18";
			size = new global::System.Drawing.Size(122, 20);
			this.Label18.Size = size;
			this.Label18.TabIndex = 33;
			this.Label18.Text = "Notify Mobs:";
			this.Label18.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.GroupBox9.Controls.Add(this.rbFlagCastThrough);
			this.GroupBox9.Controls.Add(this.rbFlagDisallow);
			this.GroupBox9.Controls.Add(this.rbFlagRequired);
			this.GroupBox9.Controls.Add(this.rbFlagVector);
			this.GroupBox9.Controls.Add(this.rbFlagCast);
			this.GroupBox9.Controls.Add(this.clbFlags);
			this.GroupBox9.Controls.Add(this.rbFlagTargetsSec);
			this.GroupBox9.Controls.Add(this.rbFlagTargets);
			this.GroupBox9.Controls.Add(this.rbFlagAffected);
			this.GroupBox9.Controls.Add(this.rbFlagAutoHit);
			point = new global::System.Drawing.Point(521, 8);
			this.GroupBox9.Location = point;
			this.GroupBox9.Name = "GroupBox9";
			size = new global::System.Drawing.Size(300, 320);
			this.GroupBox9.Size = size;
			this.GroupBox9.TabIndex = 103;
			this.GroupBox9.TabStop = false;
			this.GroupBox9.Text = "Adv. Attributes";
			point = new global::System.Drawing.Point(152, 111);
			this.rbFlagCastThrough.Location = point;
			this.rbFlagCastThrough.Name = "rbFlagCastThrough";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagCastThrough.Size = size;
			this.rbFlagCastThrough.TabIndex = 9;
			this.rbFlagCastThrough.TabStop = true;
			this.rbFlagCastThrough.Text = "Cast Through...";
			this.rbFlagCastThrough.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(152, 88);
			this.rbFlagDisallow.Location = point;
			this.rbFlagDisallow.Name = "rbFlagDisallow";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagDisallow.Size = size;
			this.rbFlagDisallow.TabIndex = 7;
			this.rbFlagDisallow.TabStop = true;
			this.rbFlagDisallow.Text = "Modes Disallowed";
			this.rbFlagDisallow.UseVisualStyleBackColor = true;
			this.rbFlagRequired.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(6, 88);
			this.rbFlagRequired.Location = point;
			this.rbFlagRequired.Name = "rbFlagRequired";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagRequired.Size = size;
			this.rbFlagRequired.TabIndex = 6;
			this.rbFlagRequired.TabStop = true;
			this.rbFlagRequired.Text = "Modes Required";
			this.rbFlagRequired.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.rbFlagRequired.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(152, 65);
			this.rbFlagVector.Location = point;
			this.rbFlagVector.Name = "rbFlagVector";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagVector.Size = size;
			this.rbFlagVector.TabIndex = 5;
			this.rbFlagVector.TabStop = true;
			this.rbFlagVector.Text = "Vector / Damage Types";
			this.rbFlagVector.UseVisualStyleBackColor = true;
			this.rbFlagCast.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(6, 65);
			this.rbFlagCast.Location = point;
			this.rbFlagCast.Name = "rbFlagCast";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagCast.Size = size;
			this.rbFlagCast.TabIndex = 4;
			this.rbFlagCast.TabStop = true;
			this.rbFlagCast.Text = "Cast Flags";
			this.rbFlagCast.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.rbFlagCast.UseVisualStyleBackColor = true;
			this.clbFlags.FormattingEnabled = true;
			point = new global::System.Drawing.Point(6, 130);
			this.clbFlags.Location = point;
			this.clbFlags.Name = "clbFlags";
			size = new global::System.Drawing.Size(288, 184);
			this.clbFlags.Size = size;
			this.clbFlags.TabIndex = 10;
			point = new global::System.Drawing.Point(152, 42);
			this.rbFlagTargetsSec.Location = point;
			this.rbFlagTargetsSec.Name = "rbFlagTargetsSec";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagTargetsSec.Size = size;
			this.rbFlagTargetsSec.TabIndex = 3;
			this.rbFlagTargetsSec.TabStop = true;
			this.rbFlagTargetsSec.Text = "Secondary Targets";
			this.rbFlagTargetsSec.UseVisualStyleBackColor = true;
			this.rbFlagTargets.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(6, 42);
			this.rbFlagTargets.Location = point;
			this.rbFlagTargets.Name = "rbFlagTargets";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagTargets.Size = size;
			this.rbFlagTargets.TabIndex = 2;
			this.rbFlagTargets.TabStop = true;
			this.rbFlagTargets.Text = "Targets";
			this.rbFlagTargets.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.rbFlagTargets.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(152, 19);
			this.rbFlagAffected.Location = point;
			this.rbFlagAffected.Name = "rbFlagAffected";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagAffected.Size = size;
			this.rbFlagAffected.TabIndex = 1;
			this.rbFlagAffected.TabStop = true;
			this.rbFlagAffected.Text = "Entities Affected";
			this.rbFlagAffected.UseVisualStyleBackColor = true;
			this.rbFlagAutoHit.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(6, 19);
			this.rbFlagAutoHit.Location = point;
			this.rbFlagAutoHit.Name = "rbFlagAutoHit";
			size = new global::System.Drawing.Size(140, 17);
			this.rbFlagAutoHit.Size = size;
			this.rbFlagAutoHit.TabIndex = 0;
			this.rbFlagAutoHit.TabStop = true;
			this.rbFlagAutoHit.Text = "Entities AutoHit";
			this.rbFlagAutoHit.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.rbFlagAutoHit.UseVisualStyleBackColor = true;
			this.cbNotify.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			point = new global::System.Drawing.Point(384, 63);
			this.cbNotify.Location = point;
			this.cbNotify.Name = "cbNotify";
			size = new global::System.Drawing.Size(95, 22);
			this.cbNotify.Size = size;
			this.cbNotify.TabIndex = 14;
			this.chkLos.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.chkLos.Checked = true;
			this.chkLos.CheckState = global::System.Windows.Forms.CheckState.Checked;
			point = new global::System.Drawing.Point(256, 90);
			this.chkLos.Location = point;
			this.chkLos.Name = "chkLos";
			size = new global::System.Drawing.Size(223, 20);
			this.chkLos.Size = size;
			this.chkLos.TabIndex = 15;
			this.chkLos.Text = "Requires Line of Sight";
			this.chkLos.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 295);
			this.txtMaxTargets.Location = point;
			this.txtMaxTargets.Name = "txtMaxTargets";
			size = new global::System.Drawing.Size(57, 20);
			this.txtMaxTargets.Size = size;
			this.txtMaxTargets.TabIndex = 11;
			this.txtMaxTargets.Text = "1";
			this.txtMaxTargets.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(180, 167);
			this.lblEndCost.Location = point;
			this.lblEndCost.Name = "lblEndCost";
			size = new global::System.Drawing.Size(50, 20);
			this.lblEndCost.Size = size;
			this.lblEndCost.TabIndex = 101;
			this.lblEndCost.Text = "(1.05/s)";
			this.lblEndCost.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(12, 295);
			this.Label20.Location = point;
			this.Label20.Name = "Label20";
			size = new global::System.Drawing.Size(101, 20);
			this.Label20.Size = size;
			this.Label20.TabIndex = 39;
			this.Label20.Text = "Max Targets:";
			this.Label20.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(180, 37);
			this.lblAcc.Location = point;
			this.lblAcc.Name = "lblAcc";
			size = new global::System.Drawing.Size(50, 20);
			this.lblAcc.Size = size;
			this.lblAcc.TabIndex = 100;
			this.lblAcc.Text = "(75%)";
			this.lblAcc.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(180, 269);
			this.Label40.Location = point;
			this.Label40.Name = "Label40";
			size = new global::System.Drawing.Size(30, 20);
			this.Label40.Size = size;
			this.Label40.TabIndex = 99;
			this.Label40.Text = "deg.";
			this.Label40.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(180, 245);
			this.Label39.Location = point;
			this.Label39.Name = "Label39";
			size = new global::System.Drawing.Size(30, 20);
			this.Label39.Size = size;
			this.Label39.TabIndex = 98;
			this.Label39.Text = "ft";
			this.Label39.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(180, 193);
			this.Label38.Location = point;
			this.Label38.Name = "Label38";
			size = new global::System.Drawing.Size(20, 20);
			this.Label38.Size = size;
			this.Label38.TabIndex = 97;
			this.Label38.Text = "ft";
			this.Label38.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(180, 141);
			this.Label37.Location = point;
			this.Label37.Name = "Label37";
			size = new global::System.Drawing.Size(20, 20);
			this.Label37.Size = size;
			this.Label37.TabIndex = 96;
			this.Label37.Text = "s";
			this.Label37.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(180, 115);
			this.Label36.Location = point;
			this.Label36.Name = "Label36";
			size = new global::System.Drawing.Size(20, 20);
			this.Label36.Size = size;
			this.Label36.TabIndex = 95;
			this.Label36.Text = "s";
			this.Label36.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(180, 89);
			this.Label35.Location = point;
			this.Label35.Name = "Label35";
			size = new global::System.Drawing.Size(20, 20);
			this.Label35.Size = size;
			this.Label35.TabIndex = 94;
			this.Label35.Text = "s";
			this.Label35.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(180, 63);
			this.Label34.Location = point;
			this.Label34.Name = "Label34";
			size = new global::System.Drawing.Size(20, 20);
			this.Label34.Size = size;
			this.Label34.TabIndex = 93;
			this.Label34.Text = "s";
			this.Label34.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(35, 269);
			this.Label16.Location = point;
			this.Label16.Name = "Label16";
			size = new global::System.Drawing.Size(78, 20);
			this.Label16.Size = size;
			this.Label16.TabIndex = 30;
			this.Label16.Text = "Arc:";
			this.Label16.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 269);
			this.txtArc.Location = point;
			this.txtArc.Name = "txtArc";
			size = new global::System.Drawing.Size(57, 20);
			this.txtArc.Size = size;
			this.txtArc.TabIndex = 10;
			this.txtArc.Text = "1";
			this.txtArc.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(35, 245);
			this.Label15.Location = point;
			this.Label15.Name = "Label15";
			size = new global::System.Drawing.Size(78, 20);
			this.Label15.Size = size;
			this.Label15.TabIndex = 28;
			this.Label15.Text = "Radius:";
			this.Label15.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 245);
			this.txtRadius.Location = point;
			this.txtRadius.Name = "txtRadius";
			size = new global::System.Drawing.Size(57, 20);
			this.txtRadius.Size = size;
			this.txtRadius.TabIndex = 9;
			this.txtRadius.Text = "1";
			this.txtRadius.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(117, 11);
			this.txtLevel.Location = point;
			this.txtLevel.Name = "txtLevel";
			size = new global::System.Drawing.Size(57, 20);
			this.txtLevel.Size = size;
			this.txtLevel.TabIndex = 0;
			this.txtLevel.Text = "1";
			this.txtLevel.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.cbEffectArea.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cbEffectArea.Items.AddRange(new object[]
			{
				"None",
				"Character",
				"Sphere",
				"Cone",
				"Location"
			});
			point = new global::System.Drawing.Point(384, 37);
			this.cbEffectArea.Location = point;
			this.cbEffectArea.Name = "cbEffectArea";
			size = new global::System.Drawing.Size(95, 22);
			this.cbEffectArea.Size = size;
			this.cbEffectArea.TabIndex = 13;
			point = new global::System.Drawing.Point(256, 37);
			this.Label14.Location = point;
			this.Label14.Name = "Label14";
			size = new global::System.Drawing.Size(122, 20);
			this.Label14.Size = size;
			this.Label14.TabIndex = 24;
			this.Label14.Text = "Effect Area:";
			this.Label14.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(9, 167);
			this.Label13.Location = point;
			this.Label13.Name = "Label13";
			size = new global::System.Drawing.Size(104, 20);
			this.Label13.Size = size;
			this.Label13.TabIndex = 19;
			this.Label13.Text = "Endurance Cost:";
			this.Label13.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 167);
			this.txtEndCost.Location = point;
			this.txtEndCost.Name = "txtEndCost";
			size = new global::System.Drawing.Size(57, 20);
			this.txtEndCost.Size = size;
			this.txtEndCost.TabIndex = 6;
			this.txtEndCost.Text = "1.0";
			this.txtEndCost.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(9, 141);
			this.Label10.Location = point;
			this.Label10.Name = "Label10";
			size = new global::System.Drawing.Size(104, 20);
			this.Label10.Size = size;
			this.Label10.TabIndex = 17;
			this.Label10.Text = "Activate Interval:";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 141);
			this.txtActivate.Location = point;
			this.txtActivate.Name = "txtActivate";
			size = new global::System.Drawing.Size(57, 20);
			this.txtActivate.Size = size;
			this.txtActivate.TabIndex = 5;
			this.txtActivate.Text = "1.0";
			this.txtActivate.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(9, 115);
			this.Label11.Location = point;
			this.Label11.Name = "Label11";
			size = new global::System.Drawing.Size(104, 20);
			this.Label11.Size = size;
			this.Label11.TabIndex = 15;
			this.Label11.Text = "Recharge Time:";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 115);
			this.txtRechargeTime.Location = point;
			this.txtRechargeTime.Name = "txtRechargeTime";
			size = new global::System.Drawing.Size(57, 20);
			this.txtRechargeTime.Size = size;
			this.txtRechargeTime.TabIndex = 4;
			this.txtRechargeTime.Text = "1.0";
			this.txtRechargeTime.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(9, 89);
			this.Label8.Location = point;
			this.Label8.Name = "Label8";
			size = new global::System.Drawing.Size(104, 20);
			this.Label8.Size = size;
			this.Label8.TabIndex = 13;
			this.Label8.Text = "Casting Time:";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 89);
			this.txtCastTime.Location = point;
			this.txtCastTime.Name = "txtCastTime";
			size = new global::System.Drawing.Size(57, 20);
			this.txtCastTime.Size = size;
			this.txtCastTime.TabIndex = 3;
			this.txtCastTime.Text = "1.0";
			this.txtCastTime.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(9, 63);
			this.Label9.Location = point;
			this.Label9.Name = "Label9";
			size = new global::System.Drawing.Size(104, 20);
			this.Label9.Size = size;
			this.Label9.TabIndex = 11;
			this.Label9.Text = "Interruptable Time:";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 63);
			this.txtInterrupt.Location = point;
			this.txtInterrupt.Name = "txtInterrupt";
			size = new global::System.Drawing.Size(57, 20);
			this.txtInterrupt.Size = size;
			this.txtInterrupt.TabIndex = 2;
			this.txtInterrupt.Text = "1.0";
			this.txtInterrupt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(9, 193);
			this.Label7.Location = point;
			this.Label7.Name = "Label7";
			size = new global::System.Drawing.Size(104, 20);
			this.Label7.Size = size;
			this.Label7.TabIndex = 9;
			this.Label7.Text = "Range:";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 193);
			this.txtRange.Location = point;
			this.txtRange.Name = "txtRange";
			size = new global::System.Drawing.Size(57, 20);
			this.txtRange.Size = size;
			this.txtRange.TabIndex = 7;
			this.txtRange.Text = "1.0";
			this.txtRange.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(9, 37);
			this.Label6.Location = point;
			this.Label6.Name = "Label6";
			size = new global::System.Drawing.Size(104, 20);
			this.Label6.Size = size;
			this.Label6.TabIndex = 7;
			this.Label6.Text = "Accuracy:";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(117, 37);
			this.txtAcc.Location = point;
			this.txtAcc.Name = "txtAcc";
			size = new global::System.Drawing.Size(57, 20);
			this.txtAcc.Size = size;
			this.txtAcc.TabIndex = 1;
			this.txtAcc.Text = "1.0";
			this.txtAcc.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.cbPowerType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cbPowerType.Items.AddRange(new object[]
			{
				"Click",
				"Passive",
				"Toggle"
			});
			point = new global::System.Drawing.Point(384, 11);
			this.cbPowerType.Location = point;
			this.cbPowerType.Name = "cbPowerType";
			size = new global::System.Drawing.Size(95, 22);
			this.cbPowerType.Size = size;
			this.cbPowerType.TabIndex = 12;
			point = new global::System.Drawing.Point(256, 11);
			this.Label5.Location = point;
			this.Label5.Name = "Label5";
			size = new global::System.Drawing.Size(122, 20);
			this.Label5.Size = size;
			this.Label5.TabIndex = 4;
			this.Label5.Text = "Power Type:";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(9, 11);
			this.Label4.Location = point;
			this.Label4.Name = "Label4";
			size = new global::System.Drawing.Size(104, 20);
			this.Label4.Size = size;
			this.Label4.TabIndex = 2;
			this.Label4.Text = "Level Available:";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.tpEffects.Controls.Add(this.lvFX);
			this.tpEffects.Controls.Add(this.pnlFX);
			point = new global::System.Drawing.Point(4, 23);
			this.tpEffects.Location = point;
			this.tpEffects.Name = "tpEffects";
			size = new global::System.Drawing.Size(832, 337);
			this.tpEffects.Size = size;
			this.tpEffects.TabIndex = 1;
			this.tpEffects.Text = "Effects";
			this.tpEffects.UseVisualStyleBackColor = true;
			this.tpEffects.Visible = false;
			this.lvFX.ItemHeight = 14;
			point = new global::System.Drawing.Point(8, 8);
			this.lvFX.Location = point;
			this.lvFX.Name = "lvFX";
			size = new global::System.Drawing.Size(744, 270);
			this.lvFX.Size = size;
			this.lvFX.TabIndex = 71;
			this.pnlFX.Controls.Add(this.btnSetDamage);
			this.pnlFX.Controls.Add(this.btnFXEdit);
			this.pnlFX.Controls.Add(this.btnFXDown);
			this.pnlFX.Controls.Add(this.btnFXUp);
			this.pnlFX.Controls.Add(this.btnFXRemove);
			this.pnlFX.Controls.Add(this.btnFXDuplicate);
			this.pnlFX.Controls.Add(this.btnFXAdd);
			point = new global::System.Drawing.Point(4, 4);
			this.pnlFX.Location = point;
			this.pnlFX.Name = "pnlFX";
			size = new global::System.Drawing.Size(824, 332);
			this.pnlFX.Size = size;
			this.pnlFX.TabIndex = 71;
			point = new global::System.Drawing.Point(312, 288);
			this.btnSetDamage.Location = point;
			this.btnSetDamage.Name = "btnSetDamage";
			size = new global::System.Drawing.Size(212, 24);
			this.btnSetDamage.Size = size;
			this.btnSetDamage.TabIndex = 78;
			this.btnSetDamage.Text = "Set damage types from effect list";
			point = new global::System.Drawing.Point(160, 288);
			this.btnFXEdit.Location = point;
			this.btnFXEdit.Name = "btnFXEdit";
			size = new global::System.Drawing.Size(64, 24);
			this.btnFXEdit.Size = size;
			this.btnFXEdit.TabIndex = 77;
			this.btnFXEdit.Text = "Edit...";
			point = new global::System.Drawing.Point(756, 40);
			this.btnFXDown.Location = point;
			this.btnFXDown.Name = "btnFXDown";
			size = new global::System.Drawing.Size(64, 24);
			this.btnFXDown.Size = size;
			this.btnFXDown.TabIndex = 11;
			this.btnFXDown.Text = "Down";
			point = new global::System.Drawing.Point(756, 8);
			this.btnFXUp.Location = point;
			this.btnFXUp.Name = "btnFXUp";
			size = new global::System.Drawing.Size(64, 24);
			this.btnFXUp.Size = size;
			this.btnFXUp.TabIndex = 12;
			this.btnFXUp.Text = "Up";
			point = new global::System.Drawing.Point(236, 288);
			this.btnFXRemove.Location = point;
			this.btnFXRemove.Name = "btnFXRemove";
			size = new global::System.Drawing.Size(64, 24);
			this.btnFXRemove.Size = size;
			this.btnFXRemove.TabIndex = 10;
			this.btnFXRemove.Text = "Remove";
			point = new global::System.Drawing.Point(84, 288);
			this.btnFXDuplicate.Location = point;
			this.btnFXDuplicate.Name = "btnFXDuplicate";
			size = new global::System.Drawing.Size(64, 24);
			this.btnFXDuplicate.Size = size;
			this.btnFXDuplicate.TabIndex = 69;
			this.btnFXDuplicate.Text = "Duplicate";
			point = new global::System.Drawing.Point(8, 288);
			this.btnFXAdd.Location = point;
			this.btnFXAdd.Name = "btnFXAdd";
			size = new global::System.Drawing.Size(64, 24);
			this.btnFXAdd.Size = size;
			this.btnFXAdd.TabIndex = 9;
			this.btnFXAdd.Text = "Add";
			this.tpEnh.Controls.Add(this.chkBoostUsePlayerLevel);
			this.tpEnh.Controls.Add(this.chkBoostBoostable);
			this.tpEnh.Controls.Add(this.Label23);
			this.tpEnh.Controls.Add(this.pbEnhancements);
			this.tpEnh.Controls.Add(this.chkPRFrontLoad);
			this.tpEnh.Controls.Add(this.pbEnhancementList);
			this.tpEnh.Controls.Add(this.lblEnhName);
			point = new global::System.Drawing.Point(4, 23);
			this.tpEnh.Location = point;
			this.tpEnh.Name = "tpEnh";
			size = new global::System.Drawing.Size(832, 337);
			this.tpEnh.Size = size;
			this.tpEnh.TabIndex = 9;
			this.tpEnh.Text = "Enhancements";
			this.tpEnh.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(357, 136);
			this.chkBoostUsePlayerLevel.Location = point;
			this.chkBoostUsePlayerLevel.Name = "chkBoostUsePlayerLevel";
			size = new global::System.Drawing.Size(324, 20);
			this.chkBoostUsePlayerLevel.Size = size;
			this.chkBoostUsePlayerLevel.TabIndex = 91;
			this.chkBoostUsePlayerLevel.Text = "Attuned Enhancement";
			point = new global::System.Drawing.Point(357, 110);
			this.chkBoostBoostable.Location = point;
			this.chkBoostBoostable.Name = "chkBoostBoostable";
			size = new global::System.Drawing.Size(324, 20);
			this.chkBoostBoostable.Size = size;
			this.chkBoostBoostable.TabIndex = 90;
			this.chkBoostBoostable.Text = "Allow Enhancement Boosters (Enhancement only)";
			point = new global::System.Drawing.Point(24, 12);
			this.Label23.Location = point;
			this.Label23.Name = "Label23";
			size = new global::System.Drawing.Size(300, 16);
			this.Label23.Size = size;
			this.Label23.TabIndex = 89;
			this.Label23.Text = "Enhancement Classes Accepted:";
			this.Label23.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.pbEnhancements.BackColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			point = new global::System.Drawing.Point(24, 28);
			this.pbEnhancements.Location = point;
			this.pbEnhancements.Name = "pbEnhancements";
			size = new global::System.Drawing.Size(416, 40);
			this.pbEnhancements.Size = size;
			this.pbEnhancements.TabIndex = 43;
			this.pbEnhancements.TabStop = false;
			point = new global::System.Drawing.Point(357, 84);
			this.chkPRFrontLoad.Location = point;
			this.chkPRFrontLoad.Name = "chkPRFrontLoad";
			size = new global::System.Drawing.Size(324, 20);
			this.chkPRFrontLoad.Size = size;
			this.chkPRFrontLoad.TabIndex = 88;
			this.chkPRFrontLoad.Text = "Allow front-loading of enhancement slots (for Kheld forms)";
			this.pbEnhancementList.BackColor = global::System.Drawing.Color.FromArgb(255, 192, 128);
			point = new global::System.Drawing.Point(24, 84);
			this.pbEnhancementList.Location = point;
			this.pbEnhancementList.Name = "pbEnhancementList";
			size = new global::System.Drawing.Size(316, 220);
			this.pbEnhancementList.Size = size;
			this.pbEnhancementList.TabIndex = 44;
			this.pbEnhancementList.TabStop = false;
			this.lblEnhName.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			point = new global::System.Drawing.Point(21, 68);
			this.lblEnhName.Location = point;
			this.lblEnhName.Name = "lblEnhName";
			size = new global::System.Drawing.Size(316, 16);
			this.lblEnhName.Size = size;
			this.lblEnhName.TabIndex = 46;
			this.tpSets.Controls.Add(this.Label24);
			this.tpSets.Controls.Add(this.lblInvSet);
			this.tpSets.Controls.Add(this.pbInvSetList);
			this.tpSets.Controls.Add(this.pbInvSetUsed);
			point = new global::System.Drawing.Point(4, 23);
			this.tpSets.Location = point;
			this.tpSets.Name = "tpSets";
			size = new global::System.Drawing.Size(832, 337);
			this.tpSets.Size = size;
			this.tpSets.TabIndex = 5;
			this.tpSets.Text = "Invention Set Types";
			this.tpSets.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(24, 12);
			this.Label24.Location = point;
			this.Label24.Name = "Label24";
			size = new global::System.Drawing.Size(300, 16);
			this.Label24.Size = size;
			this.Label24.TabIndex = 93;
			this.Label24.Text = "Invention Set Types Accepted:";
			this.Label24.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.lblInvSet.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			point = new global::System.Drawing.Point(24, 68);
			this.lblInvSet.Location = point;
			this.lblInvSet.Name = "lblInvSet";
			size = new global::System.Drawing.Size(316, 16);
			this.lblInvSet.Size = size;
			this.lblInvSet.TabIndex = 92;
			this.pbInvSetList.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
			point = new global::System.Drawing.Point(24, 84);
			this.pbInvSetList.Location = point;
			this.pbInvSetList.Name = "pbInvSetList";
			size = new global::System.Drawing.Size(316, 220);
			this.pbInvSetList.Size = size;
			this.pbInvSetList.TabIndex = 91;
			this.pbInvSetList.TabStop = false;
			this.pbInvSetUsed.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
			point = new global::System.Drawing.Point(24, 28);
			this.pbInvSetUsed.Location = point;
			this.pbInvSetUsed.Name = "pbInvSetUsed";
			size = new global::System.Drawing.Size(316, 40);
			this.pbInvSetUsed.Size = size;
			this.pbInvSetUsed.TabIndex = 90;
			this.pbInvSetUsed.TabStop = false;
			this.tpPreReq.Controls.Add(this.GroupBox11);
			this.tpPreReq.Controls.Add(this.GroupBox10);
			this.tpPreReq.Controls.Add(this.GroupBox8);
			point = new global::System.Drawing.Point(4, 23);
			this.tpPreReq.Location = point;
			this.tpPreReq.Name = "tpPreReq";
			size = new global::System.Drawing.Size(832, 337);
			this.tpPreReq.Size = size;
			this.tpPreReq.TabIndex = 4;
			this.tpPreReq.Text = "Requirements";
			this.tpPreReq.UseVisualStyleBackColor = true;
			this.tpPreReq.Visible = false;
			this.GroupBox11.Controls.Add(this.btnPrReset);
			this.GroupBox11.Controls.Add(this.btnPrSetNone);
			this.GroupBox11.Controls.Add(this.btnPrDown);
			this.GroupBox11.Controls.Add(this.btnPrUp);
			this.GroupBox11.Controls.Add(this.rbPrRemove);
			this.GroupBox11.Controls.Add(this.rbPrAdd);
			this.GroupBox11.Controls.Add(this.rbPrPowerB);
			this.GroupBox11.Controls.Add(this.rbPrPowerA);
			this.GroupBox11.Controls.Add(this.lvPrPower);
			this.GroupBox11.Controls.Add(this.lvPrSet);
			this.GroupBox11.Controls.Add(this.lvPrGroup);
			this.GroupBox11.Controls.Add(this.lvPrListing);
			point = new global::System.Drawing.Point(3, 14);
			this.GroupBox11.Location = point;
			this.GroupBox11.Name = "GroupBox11";
			size = new global::System.Drawing.Size(611, 320);
			this.GroupBox11.Size = size;
			this.GroupBox11.TabIndex = 97;
			this.GroupBox11.TabStop = false;
			this.GroupBox11.Text = "Required Powers";
			point = new global::System.Drawing.Point(432, 291);
			this.btnPrReset.Location = point;
			this.btnPrReset.Name = "btnPrReset";
			size = new global::System.Drawing.Size(156, 23);
			this.btnPrReset.Size = size;
			this.btnPrReset.TabIndex = 15;
			this.btnPrReset.Text = "Reset";
			this.btnPrReset.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(432, 153);
			this.btnPrSetNone.Location = point;
			this.btnPrSetNone.Name = "btnPrSetNone";
			size = new global::System.Drawing.Size(156, 23);
			this.btnPrSetNone.Size = size;
			this.btnPrSetNone.TabIndex = 14;
			this.btnPrSetNone.Text = "Set Power A to None";
			this.btnPrSetNone.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(513, 204);
			this.btnPrDown.Location = point;
			this.btnPrDown.Name = "btnPrDown";
			size = new global::System.Drawing.Size(75, 23);
			this.btnPrDown.Size = size;
			this.btnPrDown.TabIndex = 13;
			this.btnPrDown.Text = "Down";
			this.btnPrDown.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(432, 204);
			this.btnPrUp.Location = point;
			this.btnPrUp.Name = "btnPrUp";
			size = new global::System.Drawing.Size(75, 23);
			this.btnPrUp.Size = size;
			this.btnPrUp.TabIndex = 12;
			this.btnPrUp.Text = "Up";
			this.btnPrUp.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(432, 262);
			this.rbPrRemove.Location = point;
			this.rbPrRemove.Name = "rbPrRemove";
			size = new global::System.Drawing.Size(156, 23);
			this.rbPrRemove.Size = size;
			this.rbPrRemove.TabIndex = 11;
			this.rbPrRemove.Text = "Remove Selected";
			this.rbPrRemove.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(432, 233);
			this.rbPrAdd.Location = point;
			this.rbPrAdd.Name = "rbPrAdd";
			size = new global::System.Drawing.Size(156, 23);
			this.rbPrAdd.Size = size;
			this.rbPrAdd.TabIndex = 10;
			this.rbPrAdd.Text = "Add New";
			this.rbPrAdd.UseVisualStyleBackColor = true;
			this.rbPrPowerB.Appearance = global::System.Windows.Forms.Appearance.Button;
			point = new global::System.Drawing.Point(513, 124);
			this.rbPrPowerB.Location = point;
			this.rbPrPowerB.Name = "rbPrPowerB";
			size = new global::System.Drawing.Size(75, 23);
			this.rbPrPowerB.Size = size;
			this.rbPrPowerB.TabIndex = 9;
			this.rbPrPowerB.Text = "Power B";
			this.rbPrPowerB.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.rbPrPowerB.UseVisualStyleBackColor = true;
			this.rbPrPowerA.Appearance = global::System.Windows.Forms.Appearance.Button;
			this.rbPrPowerA.Checked = true;
			point = new global::System.Drawing.Point(432, 124);
			this.rbPrPowerA.Location = point;
			this.rbPrPowerA.Name = "rbPrPowerA";
			size = new global::System.Drawing.Size(75, 23);
			this.rbPrPowerA.Size = size;
			this.rbPrPowerA.TabIndex = 8;
			this.rbPrPowerA.TabStop = true;
			this.rbPrPowerA.Text = "Power A";
			this.rbPrPowerA.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.rbPrPowerA.UseVisualStyleBackColor = true;
			this.lvPrPower.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.ColumnHeader9
			});
			this.lvPrPower.FullRowSelect = true;
			this.lvPrPower.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
			this.lvPrPower.HideSelection = false;
			point = new global::System.Drawing.Point(290, 108);
			this.lvPrPower.Location = point;
			this.lvPrPower.MultiSelect = false;
			this.lvPrPower.Name = "lvPrPower";
			size = new global::System.Drawing.Size(136, 206);
			this.lvPrPower.Size = size;
			this.lvPrPower.TabIndex = 3;
			this.lvPrPower.UseCompatibleStateImageBehavior = false;
			this.lvPrPower.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader9.Text = "Power";
			this.ColumnHeader9.Width = 110;
			this.lvPrSet.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.ColumnHeader10
			});
			this.lvPrSet.FullRowSelect = true;
			this.lvPrSet.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
			this.lvPrSet.HideSelection = false;
			point = new global::System.Drawing.Point(148, 108);
			this.lvPrSet.Location = point;
			this.lvPrSet.MultiSelect = false;
			this.lvPrSet.Name = "lvPrSet";
			size = new global::System.Drawing.Size(136, 206);
			this.lvPrSet.Size = size;
			this.lvPrSet.TabIndex = 2;
			this.lvPrSet.UseCompatibleStateImageBehavior = false;
			this.lvPrSet.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader10.Text = "Set";
			this.ColumnHeader10.Width = 110;
			this.lvPrGroup.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.ColumnHeader11
			});
			this.lvPrGroup.FullRowSelect = true;
			this.lvPrGroup.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
			this.lvPrGroup.HideSelection = false;
			point = new global::System.Drawing.Point(6, 108);
			this.lvPrGroup.Location = point;
			this.lvPrGroup.MultiSelect = false;
			this.lvPrGroup.Name = "lvPrGroup";
			size = new global::System.Drawing.Size(136, 206);
			this.lvPrGroup.Size = size;
			this.lvPrGroup.TabIndex = 1;
			this.lvPrGroup.UseCompatibleStateImageBehavior = false;
			this.lvPrGroup.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader11.Text = "Group";
			this.ColumnHeader11.Width = 110;
			this.lvPrListing.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.ColumnHeader6,
				this.ColumnHeader7,
				this.ColumnHeader8
			});
			this.lvPrListing.FullRowSelect = true;
			this.lvPrListing.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
			this.lvPrListing.HideSelection = false;
			point = new global::System.Drawing.Point(6, 19);
			this.lvPrListing.Location = point;
			this.lvPrListing.MultiSelect = false;
			this.lvPrListing.Name = "lvPrListing";
			size = new global::System.Drawing.Size(599, 83);
			this.lvPrListing.Size = size;
			this.lvPrListing.TabIndex = 0;
			this.lvPrListing.UseCompatibleStateImageBehavior = false;
			this.lvPrListing.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader6.Text = "Power A";
			this.ColumnHeader6.Width = 265;
			this.ColumnHeader7.Text = "";
			this.ColumnHeader7.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ColumnHeader7.Width = 40;
			this.ColumnHeader8.Text = "Power B";
			this.ColumnHeader8.Width = 265;
			this.GroupBox10.Controls.Add(this.clbClassExclude);
			point = new global::System.Drawing.Point(620, 157);
			this.GroupBox10.Location = point;
			this.GroupBox10.Name = "GroupBox10";
			size = new global::System.Drawing.Size(207, 137);
			this.GroupBox10.Size = size;
			this.GroupBox10.TabIndex = 96;
			this.GroupBox10.TabStop = false;
			this.GroupBox10.Text = "Excluded Classes";
			this.clbClassExclude.FormattingEnabled = true;
			point = new global::System.Drawing.Point(6, 19);
			this.clbClassExclude.Location = point;
			this.clbClassExclude.Name = "clbClassExclude";
			size = new global::System.Drawing.Size(192, 109);
			this.clbClassExclude.Size = size;
			this.clbClassExclude.TabIndex = 0;
			this.GroupBox8.Controls.Add(this.clbClassReq);
			point = new global::System.Drawing.Point(620, 14);
			this.GroupBox8.Location = point;
			this.GroupBox8.Name = "GroupBox8";
			size = new global::System.Drawing.Size(207, 137);
			this.GroupBox8.Size = size;
			this.GroupBox8.TabIndex = 95;
			this.GroupBox8.TabStop = false;
			this.GroupBox8.Text = "Reqired Classes";
			this.clbClassReq.FormattingEnabled = true;
			point = new global::System.Drawing.Point(6, 19);
			this.clbClassReq.Location = point;
			this.clbClassReq.Name = "clbClassReq";
			size = new global::System.Drawing.Size(192, 109);
			this.clbClassReq.Size = size;
			this.clbClassReq.TabIndex = 0;
			this.tpSpecialEnh.Controls.Add(this.Label32);
			this.tpSpecialEnh.Controls.Add(this.Label30);
			this.tpSpecialEnh.Controls.Add(this.lvDisablePass4);
			this.tpSpecialEnh.Controls.Add(this.lvDisablePass1);
			point = new global::System.Drawing.Point(4, 23);
			this.tpSpecialEnh.Location = point;
			this.tpSpecialEnh.Name = "tpSpecialEnh";
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
			this.tpSpecialEnh.Padding = padding;
			size = new global::System.Drawing.Size(832, 337);
			this.tpSpecialEnh.Size = size;
			this.tpSpecialEnh.TabIndex = 7;
			this.tpSpecialEnh.Text = "Enhancement Disabling";
			this.tpSpecialEnh.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(246, 7);
			this.Label32.Location = point;
			this.Label32.Name = "Label32";
			size = new global::System.Drawing.Size(211, 34);
			this.Label32.Size = size;
			this.Label32.TabIndex = 113;
			this.Label32.Text = "Pass Four\r\n(Buffs applied after ED)";
			point = new global::System.Drawing.Point(7, 7);
			this.Label30.Location = point;
			this.Label30.Name = "Label30";
			size = new global::System.Drawing.Size(211, 34);
			this.Label30.Size = size;
			this.Label30.TabIndex = 112;
			this.Label30.Text = "Pass One\r\n(Enhancements before ED is applied)";
			this.lvDisablePass4.ItemHeight = 14;
			point = new global::System.Drawing.Point(245, 44);
			this.lvDisablePass4.Location = point;
			this.lvDisablePass4.Name = "lvDisablePass4";
			this.lvDisablePass4.SelectionMode = global::System.Windows.Forms.SelectionMode.MultiSimple;
			size = new global::System.Drawing.Size(212, 284);
			this.lvDisablePass4.Size = size;
			this.lvDisablePass4.TabIndex = 111;
			this.lvDisablePass1.ItemHeight = 14;
			point = new global::System.Drawing.Point(6, 44);
			this.lvDisablePass1.Location = point;
			this.lvDisablePass1.Name = "lvDisablePass1";
			this.lvDisablePass1.SelectionMode = global::System.Windows.Forms.SelectionMode.MultiSimple;
			size = new global::System.Drawing.Size(212, 284);
			this.lvDisablePass1.Size = size;
			this.lvDisablePass1.TabIndex = 110;
			this.tpMutex.Controls.Add(this.GroupBox2);
			this.tpMutex.Controls.Add(this.chkMutexAuto);
			this.tpMutex.Controls.Add(this.chkMutexSkip);
			point = new global::System.Drawing.Point(4, 23);
			this.tpMutex.Location = point;
			this.tpMutex.Name = "tpMutex";
			size = new global::System.Drawing.Size(832, 337);
			this.tpMutex.Size = size;
			this.tpMutex.TabIndex = 8;
			this.tpMutex.Text = "Mutal Exclusivity";
			this.tpMutex.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.btnMutexAdd);
			this.GroupBox2.Controls.Add(this.clbMutex);
			point = new global::System.Drawing.Point(9, 14);
			this.GroupBox2.Location = point;
			this.GroupBox2.Name = "GroupBox2";
			size = new global::System.Drawing.Size(325, 312);
			this.GroupBox2.Size = size;
			this.GroupBox2.TabIndex = 5;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Group Membership";
			point = new global::System.Drawing.Point(6, 283);
			this.btnMutexAdd.Location = point;
			this.btnMutexAdd.Name = "btnMutexAdd";
			size = new global::System.Drawing.Size(124, 23);
			this.btnMutexAdd.Size = size;
			this.btnMutexAdd.TabIndex = 1;
			this.btnMutexAdd.Text = "Add New Group...";
			this.btnMutexAdd.UseVisualStyleBackColor = true;
			this.clbMutex.FormattingEnabled = true;
			point = new global::System.Drawing.Point(6, 19);
			this.clbMutex.Location = point;
			this.clbMutex.Name = "clbMutex";
			size = new global::System.Drawing.Size(313, 259);
			this.clbMutex.Size = size;
			this.clbMutex.TabIndex = 0;
			point = new global::System.Drawing.Point(340, 57);
			this.chkMutexAuto.Location = point;
			this.chkMutexAuto.Name = "chkMutexAuto";
			size = new global::System.Drawing.Size(217, 18);
			this.chkMutexAuto.Size = size;
			this.chkMutexAuto.TabIndex = 4;
			this.chkMutexAuto.Text = "Auto-Detoggle other powers";
			this.chkMutexAuto.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(340, 33);
			this.chkMutexSkip.Location = point;
			this.chkMutexSkip.Name = "chkMutexSkip";
			size = new global::System.Drawing.Size(217, 18);
			this.chkMutexSkip.Size = size;
			this.chkMutexSkip.TabIndex = 3;
			this.chkMutexSkip.Text = "Skip Mutal Exclusivity for this power";
			this.chkMutexSkip.UseVisualStyleBackColor = true;
			this.tpSubPower.Controls.Add(this.btnSPAdd);
			this.tpSubPower.Controls.Add(this.btnSPRemove);
			this.tpSubPower.Controls.Add(this.lvSPSelected);
			this.tpSubPower.Controls.Add(this.lvSPPower);
			this.tpSubPower.Controls.Add(this.lvSPSet);
			this.tpSubPower.Controls.Add(this.lvSPGroup);
			point = new global::System.Drawing.Point(4, 23);
			this.tpSubPower.Location = point;
			this.tpSubPower.Name = "tpSubPower";
			size = new global::System.Drawing.Size(832, 337);
			this.tpSubPower.Size = size;
			this.tpSubPower.TabIndex = 10;
			this.tpSubPower.Text = "Sub-Powers";
			this.tpSubPower.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(437, 141);
			this.btnSPAdd.Location = point;
			this.btnSPAdd.Name = "btnSPAdd";
			size = new global::System.Drawing.Size(48, 23);
			this.btnSPAdd.Size = size;
			this.btnSPAdd.TabIndex = 13;
			this.btnSPAdd.Text = ">>";
			this.btnSPAdd.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(437, 170);
			this.btnSPRemove.Location = point;
			this.btnSPRemove.Name = "btnSPRemove";
			size = new global::System.Drawing.Size(48, 23);
			this.btnSPRemove.Size = size;
			this.btnSPRemove.TabIndex = 12;
			this.btnSPRemove.Text = "<<";
			this.btnSPRemove.UseVisualStyleBackColor = true;
			this.lvSPSelected.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.ColumnHeader4
			});
			this.lvSPSelected.FullRowSelect = true;
			this.lvSPSelected.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
			this.lvSPSelected.HideSelection = false;
			point = new global::System.Drawing.Point(491, 16);
			this.lvSPSelected.Location = point;
			this.lvSPSelected.MultiSelect = false;
			this.lvSPSelected.Name = "lvSPSelected";
			size = new global::System.Drawing.Size(324, 305);
			this.lvSPSelected.Size = size;
			this.lvSPSelected.TabIndex = 7;
			this.lvSPSelected.UseCompatibleStateImageBehavior = false;
			this.lvSPSelected.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader4.Text = "Power";
			this.ColumnHeader4.Width = 293;
			this.lvSPPower.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.ColumnHeader1
			});
			this.lvSPPower.FullRowSelect = true;
			this.lvSPPower.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
			this.lvSPPower.HideSelection = false;
			point = new global::System.Drawing.Point(295, 16);
			this.lvSPPower.Location = point;
			this.lvSPPower.MultiSelect = false;
			this.lvSPPower.Name = "lvSPPower";
			size = new global::System.Drawing.Size(136, 305);
			this.lvSPPower.Size = size;
			this.lvSPPower.TabIndex = 6;
			this.lvSPPower.UseCompatibleStateImageBehavior = false;
			this.lvSPPower.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader1.Text = "Power";
			this.ColumnHeader1.Width = 110;
			this.lvSPSet.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.ColumnHeader2
			});
			this.lvSPSet.FullRowSelect = true;
			this.lvSPSet.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
			this.lvSPSet.HideSelection = false;
			point = new global::System.Drawing.Point(153, 16);
			this.lvSPSet.Location = point;
			this.lvSPSet.MultiSelect = false;
			this.lvSPSet.Name = "lvSPSet";
			size = new global::System.Drawing.Size(136, 305);
			this.lvSPSet.Size = size;
			this.lvSPSet.TabIndex = 5;
			this.lvSPSet.UseCompatibleStateImageBehavior = false;
			this.lvSPSet.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader2.Text = "Set";
			this.ColumnHeader2.Width = 110;
			this.lvSPGroup.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.ColumnHeader3
			});
			this.lvSPGroup.FullRowSelect = true;
			this.lvSPGroup.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
			this.lvSPGroup.HideSelection = false;
			point = new global::System.Drawing.Point(11, 16);
			this.lvSPGroup.Location = point;
			this.lvSPGroup.MultiSelect = false;
			this.lvSPGroup.Name = "lvSPGroup";
			size = new global::System.Drawing.Size(136, 305);
			this.lvSPGroup.Size = size;
			this.lvSPGroup.TabIndex = 4;
			this.lvSPGroup.UseCompatibleStateImageBehavior = false;
			this.lvSPGroup.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader3.Text = "Group";
			this.ColumnHeader3.Width = 110;
			this.btnOK.DialogResult = global::System.Windows.Forms.DialogResult.OK;
			point = new global::System.Drawing.Point(740, 380);
			this.btnOK.Location = point;
			this.btnOK.Name = "btnOK";
			size = new global::System.Drawing.Size(104, 36);
			this.btnOK.Size = size;
			this.btnOK.TabIndex = 3;
			this.btnOK.Text = "OK";
			this.btnCancel.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			point = new global::System.Drawing.Point(632, 380);
			this.btnCancel.Location = point;
			this.btnCancel.Name = "btnCancel";
			size = new global::System.Drawing.Size(104, 36);
			this.btnCancel.Size = size;
			this.btnCancel.TabIndex = 4;
			this.btnCancel.Text = "Cancel";
			point = new global::System.Drawing.Point(434, 380);
			this.btnFullPaste.Location = point;
			this.btnFullPaste.Name = "btnFullPaste";
			size = new global::System.Drawing.Size(104, 36);
			this.btnFullPaste.Size = size;
			this.btnFullPaste.TabIndex = 5;
			this.btnFullPaste.Text = "Paste";
			this.btnFullPaste.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(324, 380);
			this.btnFullCopy.Location = point;
			this.btnFullCopy.Name = "btnFullCopy";
			size = new global::System.Drawing.Size(104, 36);
			this.btnFullCopy.Size = size;
			this.btnFullCopy.TabIndex = 6;
			this.btnFullCopy.Text = "Copy";
			this.btnFullCopy.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(8, 380);
			this.btnCSVImport.Location = point;
			this.btnCSVImport.Name = "btnCSVImport";
			size = new global::System.Drawing.Size(151, 36);
			this.btnCSVImport.Size = size;
			this.btnCSVImport.TabIndex = 7;
			this.btnCSVImport.Text = "Import CSV String";
			this.btnCSVImport.UseVisualStyleBackColor = true;
			base.AcceptButton = this.btnOK;
			size = new global::System.Drawing.Size(5, 13);
			this.AutoScaleBaseSize = size;
			base.CancelButton = this.btnCancel;
			size = new global::System.Drawing.Size(870, 428);
			base.ClientSize = size;
			base.Controls.Add(this.btnCSVImport);
			base.Controls.Add(this.btnFullCopy);
			base.Controls.Add(this.btnFullPaste);
			base.Controls.Add(this.btnCancel);
			base.Controls.Add(this.btnOK);
			base.Controls.Add(this.tcPower);
			this.Font = new global::System.Drawing.Font("Arial", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Pixel, 0);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "frmEditPower";
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Edit Power (Group_Name.Set_Name.Power_Name)";
			this.tcPower.ResumeLayout(false);
			this.tpText.ResumeLayout(false);
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			this.GroupBox7.ResumeLayout(false);
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.udScaleMax.EndInit();
			this.udScaleMin.EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.tpBasic.ResumeLayout(false);
			this.tpBasic.PerformLayout();
			this.GroupBox9.ResumeLayout(false);
			this.tpEffects.ResumeLayout(false);
			this.pnlFX.ResumeLayout(false);
			this.tpEnh.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.pbEnhancements).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbEnhancementList).EndInit();
			this.tpSets.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.pbInvSetList).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.pbInvSetUsed).EndInit();
			this.tpPreReq.ResumeLayout(false);
			this.GroupBox11.ResumeLayout(false);
			this.GroupBox10.ResumeLayout(false);
			this.GroupBox8.ResumeLayout(false);
			this.tpSpecialEnh.ResumeLayout(false);
			this.tpMutex.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.tpSubPower.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x04000344 RID: 836
		private global::System.ComponentModel.IContainer components;
	}
}
