namespace Hero_Designer
{
	// Token: 0x0200002F RID: 47
	public partial class frmEnhData : global::System.Windows.Forms.Form
	{
		// Token: 0x060008DC RID: 2268 RVA: 0x0005CD9C File Offset: 0x0005AF9C
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x060008E8 RID: 2280 RVA: 0x0005D934 File Offset: 0x0005BB34
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmEnhData));
			this.gbBasic = new global::System.Windows.Forms.GroupBox();
			this.txtInternal = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.udMinLevel = new global::System.Windows.Forms.NumericUpDown();
			this.udMaxLevel = new global::System.Windows.Forms.NumericUpDown();
			this.txtDesc = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.txtNameShort = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txtNameFull = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.btnImage = new global::System.Windows.Forms.Button();
			this.gbType = new global::System.Windows.Forms.GroupBox();
			this.cbSubType = new global::System.Windows.Forms.ComboBox();
			this.typeSet = new global::System.Windows.Forms.RadioButton();
			this.typeIO = new global::System.Windows.Forms.RadioButton();
			this.typeRegular = new global::System.Windows.Forms.RadioButton();
			this.typeHO = new global::System.Windows.Forms.RadioButton();
			this.cbSet = new global::System.Windows.Forms.ComboBox();
			this.gbSet = new global::System.Windows.Forms.GroupBox();
			this.chkSuperior = new global::System.Windows.Forms.CheckBox();
			this.pbSet = new global::System.Windows.Forms.PictureBox();
			this.chkUnique = new global::System.Windows.Forms.CheckBox();
			this.gbEffects = new global::System.Windows.Forms.GroupBox();
			this.btnDown = new global::System.Windows.Forms.Button();
			this.btnUp = new global::System.Windows.Forms.Button();
			this.rbBoth = new global::System.Windows.Forms.RadioButton();
			this.rbDebuff = new global::System.Windows.Forms.RadioButton();
			this.rbBuff = new global::System.Windows.Forms.RadioButton();
			this.btnAutoFill = new global::System.Windows.Forms.Button();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txtProb = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.btnEdit = new global::System.Windows.Forms.Button();
			this.btnAddFX = new global::System.Windows.Forms.Button();
			this.btnRemove = new global::System.Windows.Forms.Button();
			this.btnAdd = new global::System.Windows.Forms.Button();
			this.gbMod = new global::System.Windows.Forms.GroupBox();
			this.rbMod4 = new global::System.Windows.Forms.RadioButton();
			this.txtModOther = new global::System.Windows.Forms.TextBox();
			this.rbModOther = new global::System.Windows.Forms.RadioButton();
			this.rbMod3 = new global::System.Windows.Forms.RadioButton();
			this.rbMod2 = new global::System.Windows.Forms.RadioButton();
			this.rbMod1 = new global::System.Windows.Forms.RadioButton();
			this.lstSelected = new global::System.Windows.Forms.ListBox();
			this.lstAvailable = new global::System.Windows.Forms.ListBox();
			this.cbSched = new global::System.Windows.Forms.ComboBox();
			this.lblSched = new global::System.Windows.Forms.Label();
			this.btnOK = new global::System.Windows.Forms.Button();
			this.btnCancel = new global::System.Windows.Forms.Button();
			this.gbClass = new global::System.Windows.Forms.GroupBox();
			this.lblClass = new global::System.Windows.Forms.Label();
			this.pnlClassList = new global::System.Windows.Forms.Panel();
			this.pnlClass = new global::System.Windows.Forms.Panel();
			this.ImagePicker = new global::System.Windows.Forms.OpenFileDialog();
			this.btnNoImage = new global::System.Windows.Forms.Button();
			this.tTip = new global::System.Windows.Forms.ToolTip(this.components);
			this.cbMutEx = new global::System.Windows.Forms.ComboBox();
			this.cbRecipe = new global::System.Windows.Forms.ComboBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.btnEditPowerData = new global::System.Windows.Forms.Button();
			this.StaticIndex = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.gbBasic.SuspendLayout();
			this.udMinLevel.BeginInit();
			this.udMaxLevel.BeginInit();
			this.gbType.SuspendLayout();
			this.gbSet.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pbSet).BeginInit();
			this.gbEffects.SuspendLayout();
			this.gbMod.SuspendLayout();
			this.gbClass.SuspendLayout();
			base.SuspendLayout();
			this.gbBasic.Controls.Add(this.txtInternal);
			this.gbBasic.Controls.Add(this.Label9);
			this.gbBasic.Controls.Add(this.Label7);
			this.gbBasic.Controls.Add(this.Label6);
			this.gbBasic.Controls.Add(this.udMinLevel);
			this.gbBasic.Controls.Add(this.udMaxLevel);
			this.gbBasic.Controls.Add(this.txtDesc);
			this.gbBasic.Controls.Add(this.Label4);
			this.gbBasic.Controls.Add(this.txtNameShort);
			this.gbBasic.Controls.Add(this.Label3);
			this.gbBasic.Controls.Add(this.txtNameFull);
			this.gbBasic.Controls.Add(this.Label2);
			global::System.Drawing.Point point = new global::System.Drawing.Point(96, 8);
			this.gbBasic.Location = point;
			this.gbBasic.Name = "gbBasic";
			global::System.Drawing.Size size = new global::System.Drawing.Size(248, 169);
			this.gbBasic.Size = size;
			this.gbBasic.TabIndex = 11;
			this.gbBasic.TabStop = false;
			this.gbBasic.Text = "Basic:";
			point = new global::System.Drawing.Point(84, 68);
			this.txtInternal.Location = point;
			this.txtInternal.Name = "txtInternal";
			size = new global::System.Drawing.Size(156, 20);
			this.txtInternal.Size = size;
			this.txtInternal.TabIndex = 21;
			point = new global::System.Drawing.Point(8, 68);
			this.Label9.Location = point;
			this.Label9.Name = "Label9";
			size = new global::System.Drawing.Size(72, 20);
			this.Label9.Size = size;
			this.Label9.TabIndex = 20;
			this.Label9.Text = "Internal:";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(134, 140);
			this.Label7.Location = point;
			this.Label7.Name = "Label7";
			size = new global::System.Drawing.Size(56, 20);
			this.Label7.Size = size;
			this.Label7.TabIndex = 19;
			this.Label7.Text = "to";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			point = new global::System.Drawing.Point(6, 140);
			this.Label6.Location = point;
			this.Label6.Name = "Label6";
			size = new global::System.Drawing.Size(74, 20);
			this.Label6.Size = size;
			this.Label6.TabIndex = 18;
			this.Label6.Text = "Level range:";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(84, 140);
			this.udMinLevel.Location = point;
			int[] array = new int[4];
			array[0] = 53;
			decimal num = new decimal(array);
			this.udMinLevel.Maximum = num;
			array = new int[4];
			array[0] = 1;
			num = new decimal(array);
			this.udMinLevel.Minimum = num;
			this.udMinLevel.Name = "udMinLevel";
			size = new global::System.Drawing.Size(44, 20);
			this.udMinLevel.Size = size;
			this.udMinLevel.TabIndex = 17;
			array = new int[4];
			array[0] = 1;
			num = new decimal(array);
			this.udMinLevel.Value = num;
			point = new global::System.Drawing.Point(196, 140);
			this.udMaxLevel.Location = point;
			array = new int[4];
			array[0] = 53;
			num = new decimal(array);
			this.udMaxLevel.Maximum = num;
			array = new int[4];
			array[0] = 1;
			num = new decimal(array);
			this.udMaxLevel.Minimum = num;
			this.udMaxLevel.Name = "udMaxLevel";
			size = new global::System.Drawing.Size(44, 20);
			this.udMaxLevel.Size = size;
			this.udMaxLevel.TabIndex = 16;
			array = new int[4];
			array[0] = 53;
			num = new decimal(array);
			this.udMaxLevel.Value = num;
			point = new global::System.Drawing.Point(84, 94);
			this.txtDesc.Location = point;
			this.txtDesc.Multiline = true;
			this.txtDesc.Name = "txtDesc";
			size = new global::System.Drawing.Size(156, 40);
			this.txtDesc.Size = size;
			this.txtDesc.TabIndex = 15;
			point = new global::System.Drawing.Point(8, 98);
			this.Label4.Location = point;
			this.Label4.Name = "Label4";
			size = new global::System.Drawing.Size(72, 20);
			this.Label4.Size = size;
			this.Label4.TabIndex = 14;
			this.Label4.Text = "Description:";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(84, 42);
			this.txtNameShort.Location = point;
			this.txtNameShort.Name = "txtNameShort";
			size = new global::System.Drawing.Size(156, 20);
			this.txtNameShort.Size = size;
			this.txtNameShort.TabIndex = 13;
			point = new global::System.Drawing.Point(8, 42);
			this.Label3.Location = point;
			this.Label3.Name = "Label3";
			size = new global::System.Drawing.Size(72, 20);
			this.Label3.Size = size;
			this.Label3.TabIndex = 12;
			this.Label3.Text = "Short Name:";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(84, 16);
			this.txtNameFull.Location = point;
			this.txtNameFull.Name = "txtNameFull";
			size = new global::System.Drawing.Size(156, 20);
			this.txtNameFull.Size = size;
			this.txtNameFull.TabIndex = 11;
			point = new global::System.Drawing.Point(8, 16);
			this.Label2.Location = point;
			this.Label2.Name = "Label2";
			size = new global::System.Drawing.Size(72, 20);
			this.Label2.Size = size;
			this.Label2.TabIndex = 10;
			this.Label2.Text = "Full Name:";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.btnImage.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnImage.Image");
			this.btnImage.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			point = new global::System.Drawing.Point(8, 12);
			this.btnImage.Location = point;
			this.btnImage.Name = "btnImage";
			size = new global::System.Drawing.Size(80, 68);
			this.btnImage.Size = size;
			this.btnImage.TabIndex = 9;
			this.btnImage.Text = "ImageName";
			this.btnImage.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.gbType.Controls.Add(this.cbSubType);
			this.gbType.Controls.Add(this.typeSet);
			this.gbType.Controls.Add(this.typeIO);
			this.gbType.Controls.Add(this.typeRegular);
			this.gbType.Controls.Add(this.typeHO);
			point = new global::System.Drawing.Point(352, 8);
			this.gbType.Location = point;
			this.gbType.Name = "gbType";
			size = new global::System.Drawing.Size(140, 169);
			this.gbType.Size = size;
			this.gbType.TabIndex = 2;
			this.gbType.TabStop = false;
			this.gbType.Text = "Enhancement Type:";
			this.cbSubType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			point = new global::System.Drawing.Point(8, 138);
			this.cbSubType.Location = point;
			this.cbSubType.Name = "cbSubType";
			size = new global::System.Drawing.Size(124, 22);
			this.cbSubType.Size = size;
			this.cbSubType.TabIndex = 54;
			this.tTip.SetToolTip(this.cbSubType, "(Currently only apllicable to Stealth IOs");
			this.typeSet.Appearance = global::System.Windows.Forms.Appearance.Button;
			this.typeSet.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.typeSet.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("typeSet.Image");
			this.typeSet.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			point = new global::System.Drawing.Point(72, 76);
			this.typeSet.Location = point;
			this.typeSet.Name = "typeSet";
			size = new global::System.Drawing.Size(60, 56);
			this.typeSet.Size = size;
			this.typeSet.TabIndex = 53;
			this.typeSet.Text = "IO Set";
			this.typeSet.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.typeIO.Appearance = global::System.Windows.Forms.Appearance.Button;
			this.typeIO.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.typeIO.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("typeIO.Image");
			this.typeIO.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			point = new global::System.Drawing.Point(72, 16);
			this.typeIO.Location = point;
			this.typeIO.Name = "typeIO";
			size = new global::System.Drawing.Size(60, 56);
			this.typeIO.Size = size;
			this.typeIO.TabIndex = 52;
			this.typeIO.Text = "Invention";
			this.typeIO.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.typeRegular.Appearance = global::System.Windows.Forms.Appearance.Button;
			this.typeRegular.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.typeRegular.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("typeRegular.Image");
			this.typeRegular.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			point = new global::System.Drawing.Point(8, 16);
			this.typeRegular.Location = point;
			this.typeRegular.Name = "typeRegular";
			size = new global::System.Drawing.Size(60, 56);
			this.typeRegular.Size = size;
			this.typeRegular.TabIndex = 50;
			this.typeRegular.Text = "Regular";
			this.typeRegular.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.typeHO.Appearance = global::System.Windows.Forms.Appearance.Button;
			this.typeHO.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.typeHO.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("typeHO.Image");
			this.typeHO.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			point = new global::System.Drawing.Point(8, 76);
			this.typeHO.Location = point;
			this.typeHO.Name = "typeHO";
			size = new global::System.Drawing.Size(60, 56);
			this.typeHO.Size = size;
			this.typeHO.TabIndex = 51;
			this.typeHO.Text = "Special";
			this.typeHO.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.cbSet.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			point = new global::System.Drawing.Point(8, 20);
			this.cbSet.Location = point;
			this.cbSet.Name = "cbSet";
			size = new global::System.Drawing.Size(168, 22);
			this.cbSet.Size = size;
			this.cbSet.TabIndex = 13;
			this.gbSet.Controls.Add(this.chkSuperior);
			this.gbSet.Controls.Add(this.pbSet);
			this.gbSet.Controls.Add(this.cbSet);
			this.gbSet.Controls.Add(this.chkUnique);
			point = new global::System.Drawing.Point(496, 8);
			this.gbSet.Location = point;
			this.gbSet.Name = "gbSet";
			size = new global::System.Drawing.Size(184, 119);
			this.gbSet.Size = size;
			this.gbSet.TabIndex = 14;
			this.gbSet.TabStop = false;
			this.gbSet.Text = "Invention Origin Set:";
			point = new global::System.Drawing.Point(60, 94);
			this.chkSuperior.Location = point;
			this.chkSuperior.Name = "chkSuperior";
			size = new global::System.Drawing.Size(84, 16);
			this.chkSuperior.Size = size;
			this.chkSuperior.TabIndex = 21;
			this.chkSuperior.Text = "Superior";
			point = new global::System.Drawing.Point(12, 52);
			this.pbSet.Location = point;
			this.pbSet.Name = "pbSet";
			size = new global::System.Drawing.Size(30, 30);
			this.pbSet.Size = size;
			this.pbSet.TabIndex = 14;
			this.pbSet.TabStop = false;
			point = new global::System.Drawing.Point(60, 60);
			this.chkUnique.Location = point;
			this.chkUnique.Name = "chkUnique";
			size = new global::System.Drawing.Size(84, 16);
			this.chkUnique.Size = size;
			this.chkUnique.TabIndex = 20;
			this.chkUnique.Text = "Unique";
			this.gbEffects.Controls.Add(this.btnDown);
			this.gbEffects.Controls.Add(this.btnUp);
			this.gbEffects.Controls.Add(this.rbBoth);
			this.gbEffects.Controls.Add(this.rbDebuff);
			this.gbEffects.Controls.Add(this.rbBuff);
			this.gbEffects.Controls.Add(this.btnAutoFill);
			this.gbEffects.Controls.Add(this.Label5);
			this.gbEffects.Controls.Add(this.txtProb);
			this.gbEffects.Controls.Add(this.Label1);
			this.gbEffects.Controls.Add(this.btnEdit);
			this.gbEffects.Controls.Add(this.btnAddFX);
			this.gbEffects.Controls.Add(this.btnRemove);
			this.gbEffects.Controls.Add(this.btnAdd);
			this.gbEffects.Controls.Add(this.gbMod);
			this.gbEffects.Controls.Add(this.lstSelected);
			this.gbEffects.Controls.Add(this.lstAvailable);
			this.gbEffects.Controls.Add(this.cbSched);
			this.gbEffects.Controls.Add(this.lblSched);
			point = new global::System.Drawing.Point(4, 210);
			this.gbEffects.Location = point;
			this.gbEffects.Name = "gbEffects";
			size = new global::System.Drawing.Size(584, 284);
			this.gbEffects.Size = size;
			this.gbEffects.TabIndex = 15;
			this.gbEffects.TabStop = false;
			this.gbEffects.Text = "Effects:";
			point = new global::System.Drawing.Point(188, 172);
			this.btnDown.Location = point;
			this.btnDown.Name = "btnDown";
			size = new global::System.Drawing.Size(48, 20);
			this.btnDown.Size = size;
			this.btnDown.TabIndex = 32;
			this.btnDown.Text = "Down";
			point = new global::System.Drawing.Point(188, 148);
			this.btnUp.Location = point;
			this.btnUp.Name = "btnUp";
			size = new global::System.Drawing.Size(48, 20);
			this.btnUp.Size = size;
			this.btnUp.TabIndex = 31;
			this.btnUp.Text = "Up";
			this.rbBoth.Checked = true;
			point = new global::System.Drawing.Point(428, 228);
			this.rbBoth.Location = point;
			this.rbBoth.Name = "rbBoth";
			size = new global::System.Drawing.Size(148, 16);
			this.rbBoth.Size = size;
			this.rbBoth.TabIndex = 30;
			this.rbBoth.TabStop = true;
			this.rbBoth.Text = "Buff/Debuff Effects";
			this.tTip.SetToolTip(this.rbBoth, "Apply to effects regardles of whether the Mag is positive or negative");
			point = new global::System.Drawing.Point(428, 212);
			this.rbDebuff.Location = point;
			this.rbDebuff.Name = "rbDebuff";
			size = new global::System.Drawing.Size(148, 16);
			this.rbDebuff.Size = size;
			this.rbDebuff.TabIndex = 29;
			this.rbDebuff.Text = "Debuff Effects";
			this.tTip.SetToolTip(this.rbDebuff, "Apply only to effects with a negative Mag");
			point = new global::System.Drawing.Point(428, 196);
			this.rbBuff.Location = point;
			this.rbBuff.Name = "rbBuff";
			size = new global::System.Drawing.Size(148, 16);
			this.rbBuff.Size = size;
			this.rbBuff.TabIndex = 28;
			this.rbBuff.Text = "Buff Effects";
			this.tTip.SetToolTip(this.rbBuff, "Apply only to effects with a positive Mag");
			point = new global::System.Drawing.Point(128, 24);
			this.btnAutoFill.Location = point;
			this.btnAutoFill.Name = "btnAutoFill";
			size = new global::System.Drawing.Size(108, 32);
			this.btnAutoFill.Size = size;
			this.btnAutoFill.TabIndex = 27;
			this.btnAutoFill.Text = "AutoFill Names";
			point = new global::System.Drawing.Point(196, 244);
			this.Label5.Location = point;
			this.Label5.Name = "Label5";
			size = new global::System.Drawing.Size(28, 20);
			this.Label5.Size = size;
			this.Label5.TabIndex = 26;
			this.Label5.Text = "(0-1)";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			point = new global::System.Drawing.Point(156, 244);
			this.txtProb.Location = point;
			this.txtProb.Name = "txtProb";
			size = new global::System.Drawing.Size(36, 20);
			this.txtProb.Size = size;
			this.txtProb.TabIndex = 25;
			this.txtProb.Text = "1";
			point = new global::System.Drawing.Point(8, 244);
			this.Label1.Location = point;
			this.Label1.Name = "Label1";
			size = new global::System.Drawing.Size(148, 20);
			this.Label1.Size = size;
			this.Label1.TabIndex = 24;
			this.Label1.Text = "Special Effect Probability:";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.btnEdit.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			point = new global::System.Drawing.Point(424, 248);
			this.btnEdit.Location = point;
			this.btnEdit.Name = "btnEdit";
			size = new global::System.Drawing.Size(152, 28);
			this.btnEdit.Size = size;
			this.btnEdit.TabIndex = 23;
			this.btnEdit.Text = "Edit Selected...";
			this.btnAddFX.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			point = new global::System.Drawing.Point(8, 208);
			this.btnAddFX.Location = point;
			this.btnAddFX.Name = "btnAddFX";
			size = new global::System.Drawing.Size(228, 28);
			this.btnAddFX.Size = size;
			this.btnAddFX.TabIndex = 22;
			this.btnAddFX.Text = "Add Special Effect... ->";
			this.btnRemove.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			point = new global::System.Drawing.Point(240, 248);
			this.btnRemove.Location = point;
			this.btnRemove.Name = "btnRemove";
			size = new global::System.Drawing.Size(176, 28);
			this.btnRemove.Size = size;
			this.btnRemove.TabIndex = 21;
			this.btnRemove.Text = "Remove Selected";
			this.btnAdd.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			point = new global::System.Drawing.Point(128, 100);
			this.btnAdd.Location = point;
			this.btnAdd.Name = "btnAdd";
			size = new global::System.Drawing.Size(108, 28);
			this.btnAdd.Size = size;
			this.btnAdd.TabIndex = 20;
			this.btnAdd.Text = "Add ->";
			this.gbMod.Controls.Add(this.rbMod4);
			this.gbMod.Controls.Add(this.txtModOther);
			this.gbMod.Controls.Add(this.rbModOther);
			this.gbMod.Controls.Add(this.rbMod3);
			this.gbMod.Controls.Add(this.rbMod2);
			this.gbMod.Controls.Add(this.rbMod1);
			point = new global::System.Drawing.Point(424, 44);
			this.gbMod.Location = point;
			this.gbMod.Name = "gbMod";
			size = new global::System.Drawing.Size(152, 148);
			this.gbMod.Size = size;
			this.gbMod.TabIndex = 19;
			this.gbMod.TabStop = false;
			this.gbMod.Text = "Effect Modifier:";
			point = new global::System.Drawing.Point(12, 80);
			this.rbMod4.Location = point;
			this.rbMod4.Name = "rbMod4";
			size = new global::System.Drawing.Size(128, 20);
			this.rbMod4.Size = size;
			this.rbMod4.TabIndex = 5;
			this.rbMod4.Text = "0.4375 (4-Effect IO)";
			this.txtModOther.Enabled = false;
			point = new global::System.Drawing.Point(28, 120);
			this.txtModOther.Location = point;
			this.txtModOther.Name = "txtModOther";
			size = new global::System.Drawing.Size(112, 20);
			this.txtModOther.Size = size;
			this.txtModOther.TabIndex = 4;
			point = new global::System.Drawing.Point(12, 100);
			this.rbModOther.Location = point;
			this.rbModOther.Name = "rbModOther";
			size = new global::System.Drawing.Size(128, 20);
			this.rbModOther.Size = size;
			this.rbModOther.TabIndex = 3;
			this.rbModOther.Text = "Other";
			point = new global::System.Drawing.Point(12, 60);
			this.rbMod3.Location = point;
			this.rbMod3.Name = "rbMod3";
			size = new global::System.Drawing.Size(128, 20);
			this.rbMod3.Size = size;
			this.rbMod3.TabIndex = 2;
			this.rbMod3.Text = "0.5 (3-Effect IO)";
			point = new global::System.Drawing.Point(12, 40);
			this.rbMod2.Location = point;
			this.rbMod2.Name = "rbMod2";
			size = new global::System.Drawing.Size(128, 20);
			this.rbMod2.Size = size;
			this.rbMod2.TabIndex = 1;
			this.rbMod2.Text = "0.625 (2-Effect IO)";
			this.rbMod1.Checked = true;
			point = new global::System.Drawing.Point(12, 20);
			this.rbMod1.Location = point;
			this.rbMod1.Name = "rbMod1";
			size = new global::System.Drawing.Size(128, 20);
			this.rbMod1.Size = size;
			this.rbMod1.TabIndex = 0;
			this.rbMod1.TabStop = true;
			this.rbMod1.Text = "1.0 (No modifier)";
			this.lstSelected.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lstSelected.ItemHeight = 14;
			point = new global::System.Drawing.Point(240, 20);
			this.lstSelected.Location = point;
			this.lstSelected.Name = "lstSelected";
			size = new global::System.Drawing.Size(176, 214);
			this.lstSelected.Size = size;
			this.lstSelected.TabIndex = 16;
			this.lstAvailable.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lstAvailable.ItemHeight = 14;
			point = new global::System.Drawing.Point(8, 20);
			this.lstAvailable.Location = point;
			this.lstAvailable.Name = "lstAvailable";
			size = new global::System.Drawing.Size(116, 172);
			this.lstAvailable.Size = size;
			this.lstAvailable.TabIndex = 15;
			this.cbSched.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			point = new global::System.Drawing.Point(488, 20);
			this.cbSched.Location = point;
			this.cbSched.Name = "cbSched";
			size = new global::System.Drawing.Size(88, 22);
			this.cbSched.Size = size;
			this.cbSched.TabIndex = 14;
			point = new global::System.Drawing.Point(424, 20);
			this.lblSched.Location = point;
			this.lblSched.Name = "lblSched";
			size = new global::System.Drawing.Size(64, 20);
			this.lblSched.Size = size;
			this.lblSched.TabIndex = 3;
			this.lblSched.Text = "Schedule:";
			this.lblSched.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.btnOK.DialogResult = global::System.Windows.Forms.DialogResult.OK;
			point = new global::System.Drawing.Point(596, 434);
			this.btnOK.Location = point;
			this.btnOK.Name = "btnOK";
			size = new global::System.Drawing.Size(84, 28);
			this.btnOK.Size = size;
			this.btnOK.TabIndex = 16;
			this.btnOK.Text = "OK";
			this.btnCancel.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			point = new global::System.Drawing.Point(596, 466);
			this.btnCancel.Location = point;
			this.btnCancel.Name = "btnCancel";
			size = new global::System.Drawing.Size(84, 28);
			this.btnCancel.Size = size;
			this.btnCancel.TabIndex = 17;
			this.btnCancel.Text = "Cancel";
			this.gbClass.Controls.Add(this.lblClass);
			this.gbClass.Controls.Add(this.pnlClassList);
			this.gbClass.Controls.Add(this.pnlClass);
			point = new global::System.Drawing.Point(596, 178);
			this.gbClass.Location = point;
			this.gbClass.Name = "gbClass";
			size = new global::System.Drawing.Size(84, 252);
			this.gbClass.Size = size;
			this.gbClass.TabIndex = 18;
			this.gbClass.TabStop = false;
			this.gbClass.Text = "Class(es):";
			point = new global::System.Drawing.Point(8, 232);
			this.lblClass.Location = point;
			this.lblClass.Name = "lblClass";
			size = new global::System.Drawing.Size(68, 16);
			this.lblClass.Size = size;
			this.lblClass.TabIndex = 2;
			this.pnlClassList.BackColor = global::System.Drawing.Color.Black;
			point = new global::System.Drawing.Point(84, 16);
			this.pnlClassList.Location = point;
			this.pnlClassList.Name = "pnlClassList";
			size = new global::System.Drawing.Size(180, 212);
			this.pnlClassList.Size = size;
			this.pnlClassList.TabIndex = 1;
			this.pnlClass.BackColor = global::System.Drawing.Color.Black;
			point = new global::System.Drawing.Point(8, 16);
			this.pnlClass.Location = point;
			this.pnlClass.Name = "pnlClass";
			size = new global::System.Drawing.Size(68, 212);
			this.pnlClass.Size = size;
			this.pnlClass.TabIndex = 0;
			this.ImagePicker.Filter = "PNG Images|*.png";
			this.ImagePicker.Title = "Select Image File";
			point = new global::System.Drawing.Point(8, 84);
			this.btnNoImage.Location = point;
			this.btnNoImage.Name = "btnNoImage";
			size = new global::System.Drawing.Size(80, 20);
			this.btnNoImage.Size = size;
			this.btnNoImage.TabIndex = 19;
			this.btnNoImage.Text = "Clear Image";
			this.tTip.AutoPopDelay = 10000;
			this.tTip.InitialDelay = 250;
			this.tTip.ReshowDelay = 100;
			this.cbMutEx.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			point = new global::System.Drawing.Point(504, 146);
			this.cbMutEx.Location = point;
			this.cbMutEx.Name = "cbMutEx";
			size = new global::System.Drawing.Size(168, 22);
			this.cbMutEx.Size = size;
			this.cbMutEx.TabIndex = 21;
			this.tTip.SetToolTip(this.cbMutEx, "(Currently only apllicable to Stealth IOs");
			this.cbRecipe.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			point = new global::System.Drawing.Point(96, 183);
			this.cbRecipe.Location = point;
			this.cbRecipe.Name = "cbRecipe";
			size = new global::System.Drawing.Size(248, 22);
			this.cbRecipe.Size = size;
			this.cbRecipe.TabIndex = 23;
			this.tTip.SetToolTip(this.cbRecipe, "(Currently only apllicable to Stealth IOs");
			point = new global::System.Drawing.Point(496, 130);
			this.Label8.Location = point;
			this.Label8.Name = "Label8";
			size = new global::System.Drawing.Size(80, 16);
			this.Label8.Size = size;
			this.Label8.TabIndex = 22;
			this.Label8.Text = "MutEx Group:";
			point = new global::System.Drawing.Point(10, 183);
			this.Label10.Location = point;
			this.Label10.Name = "Label10";
			size = new global::System.Drawing.Size(80, 22);
			this.Label10.Size = size;
			this.Label10.TabIndex = 24;
			this.Label10.Text = "Recipe:";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(352, 183);
			this.btnEditPowerData.Location = point;
			this.btnEditPowerData.Name = "btnEditPowerData";
			size = new global::System.Drawing.Size(236, 22);
			this.btnEditPowerData.Size = size;
			this.btnEditPowerData.TabIndex = 25;
			this.btnEditPowerData.Text = "Edit Power_Mode Data";
			this.btnEditPowerData.UseVisualStyleBackColor = true;
			point = new global::System.Drawing.Point(8, 146);
			this.StaticIndex.Location = point;
			this.StaticIndex.Name = "StaticIndex";
			size = new global::System.Drawing.Size(82, 20);
			this.StaticIndex.Size = size;
			this.StaticIndex.TabIndex = 26;
			this.Label11.AutoSize = true;
			point = new global::System.Drawing.Point(8, 126);
			this.Label11.Location = point;
			this.Label11.Name = "Label11";
			size = new global::System.Drawing.Size(63, 14);
			this.Label11.Size = size;
			this.Label11.TabIndex = 27;
			this.Label11.Text = "Static Index";
			base.AcceptButton = this.btnOK;
			size = new global::System.Drawing.Size(5, 13);
			this.AutoScaleBaseSize = size;
			base.CancelButton = this.btnCancel;
			size = new global::System.Drawing.Size(686, 501);
			base.ClientSize = size;
			base.Controls.Add(this.Label11);
			base.Controls.Add(this.StaticIndex);
			base.Controls.Add(this.btnEditPowerData);
			base.Controls.Add(this.Label10);
			base.Controls.Add(this.cbRecipe);
			base.Controls.Add(this.Label8);
			base.Controls.Add(this.btnNoImage);
			base.Controls.Add(this.gbClass);
			base.Controls.Add(this.btnCancel);
			base.Controls.Add(this.btnOK);
			base.Controls.Add(this.gbEffects);
			base.Controls.Add(this.gbSet);
			base.Controls.Add(this.gbBasic);
			base.Controls.Add(this.gbType);
			base.Controls.Add(this.btnImage);
			base.Controls.Add(this.cbMutEx);
			this.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "frmEnhData";
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Edit [EnhancementName]";
			this.gbBasic.ResumeLayout(false);
			this.gbBasic.PerformLayout();
			this.udMinLevel.EndInit();
			this.udMaxLevel.EndInit();
			this.gbType.ResumeLayout(false);
			this.gbSet.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.pbSet).EndInit();
			this.gbEffects.ResumeLayout(false);
			this.gbEffects.PerformLayout();
			this.gbMod.ResumeLayout(false);
			this.gbMod.PerformLayout();
			this.gbClass.ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040003BD RID: 957
		private global::System.ComponentModel.IContainer components;
	}
}
