namespace Hero_Designer
{

	public partial class frmEditArchetype : global::System.Windows.Forms.Form
	{

		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}


		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmEditArchetype));
			this.txtName = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.txtHP = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txtResCap = new global::System.Windows.Forms.TextBox();
			this.clbOrigin = new global::System.Windows.Forms.CheckedListBox();
			this.btnOK = new global::System.Windows.Forms.Button();
			this.btnCancel = new global::System.Windows.Forms.Button();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.txtHPCap = new global::System.Windows.Forms.TextBox();
			this.cbClassType = new global::System.Windows.Forms.ComboBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txtClassName = new global::System.Windows.Forms.TextBox();
			this.udColumn = new global::System.Windows.Forms.NumericUpDown();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.udThreat = new global::System.Windows.Forms.NumericUpDown();
			this.chkPlayable = new global::System.Windows.Forms.CheckBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.txtRecCap = new global::System.Windows.Forms.TextBox();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.txtRegCap = new global::System.Windows.Forms.TextBox();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.txtPerceptionCap = new global::System.Windows.Forms.TextBox();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.txtBaseRegen = new global::System.Windows.Forms.TextBox();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.txtBaseRec = new global::System.Windows.Forms.TextBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.txtRechargeCap = new global::System.Windows.Forms.TextBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.txtDamCap = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.txtDescLong = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.txtDescShort = new global::System.Windows.Forms.TextBox();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.cbSecGroup = new global::System.Windows.Forms.ComboBox();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.cbPriGroup = new global::System.Windows.Forms.ComboBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.udColumn.BeginInit();
			this.GroupBox1.SuspendLayout();
			this.udThreat.BeginInit();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			base.SuspendLayout();
			global::System.Drawing.Point point = new global::System.Drawing.Point(123, 16);
			this.txtName.Location = point;
			this.txtName.Name = "txtName";
			global::System.Drawing.Size size = new global::System.Drawing.Size(118, 20);
			this.txtName.Size = size;
			this.txtName.TabIndex = 0;
			point = new global::System.Drawing.Point(30, 16);
			this.Label1.Location = point;
			this.Label1.Name = "Label1";
			size = new global::System.Drawing.Size(87, 20);
			this.Label1.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "Display Name:";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(6, 19);
			this.Label2.Location = point;
			this.Label2.Name = "Label2";
			size = new global::System.Drawing.Size(121, 20);
			this.Label2.Size = size;
			this.Label2.TabIndex = 5;
			this.Label2.Text = "Hit Points:";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(133, 19);
			this.txtHP.Location = point;
			this.txtHP.Name = "txtHP";
			size = new global::System.Drawing.Size(108, 20);
			this.txtHP.Size = size;
			this.txtHP.TabIndex = 4;
			point = new global::System.Drawing.Point(6, 123);
			this.Label3.Location = point;
			this.Label3.Name = "Label3";
			size = new global::System.Drawing.Size(121, 20);
			this.Label3.Size = size;
			this.Label3.TabIndex = 7;
			this.Label3.Text = "Resistance Cap:";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(133, 123);
			this.txtResCap.Location = point;
			this.txtResCap.Name = "txtResCap";
			size = new global::System.Drawing.Size(90, 20);
			this.txtResCap.Size = size;
			this.txtResCap.TabIndex = 6;
			this.txtResCap.Text = "80";
			this.txtResCap.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(6, 16);
			this.clbOrigin.Location = point;
			this.clbOrigin.Name = "clbOrigin";
			size = new global::System.Drawing.Size(235, 244);
			this.clbOrigin.Size = size;
			this.clbOrigin.TabIndex = 8;
			point = new global::System.Drawing.Point(437, 585);
			this.btnOK.Location = point;
			this.btnOK.Name = "btnOK";
			size = new global::System.Drawing.Size(75, 23);
			this.btnOK.Size = size;
			this.btnOK.TabIndex = 10;
			this.btnOK.Text = "OK";
			this.btnCancel.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			point = new global::System.Drawing.Point(353, 585);
			this.btnCancel.Location = point;
			this.btnCancel.Name = "btnCancel";
			size = new global::System.Drawing.Size(75, 23);
			this.btnCancel.Size = size;
			this.btnCancel.TabIndex = 11;
			this.btnCancel.Text = "Cancel";
			point = new global::System.Drawing.Point(6, 45);
			this.Label6.Location = point;
			this.Label6.Name = "Label6";
			size = new global::System.Drawing.Size(121, 20);
			this.Label6.Size = size;
			this.Label6.TabIndex = 16;
			this.Label6.Text = "Hit Point Cap:";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(133, 45);
			this.txtHPCap.Location = point;
			this.txtHPCap.Name = "txtHPCap";
			size = new global::System.Drawing.Size(108, 20);
			this.txtHPCap.Size = size;
			this.txtHPCap.TabIndex = 15;
			this.cbClassType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cbClassType.FormattingEnabled = true;
			point = new global::System.Drawing.Point(123, 68);
			this.cbClassType.Location = point;
			this.cbClassType.Name = "cbClassType";
			size = new global::System.Drawing.Size(118, 21);
			this.cbClassType.Size = size;
			this.cbClassType.TabIndex = 17;
			point = new global::System.Drawing.Point(30, 68);
			this.Label7.Location = point;
			this.Label7.Name = "Label7";
			size = new global::System.Drawing.Size(87, 21);
			this.Label7.Size = size;
			this.Label7.TabIndex = 18;
			this.Label7.Text = "Class Type:";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(30, 42);
			this.Label5.Location = point;
			this.Label5.Name = "Label5";
			size = new global::System.Drawing.Size(87, 20);
			this.Label5.Size = size;
			this.Label5.TabIndex = 20;
			this.Label5.Text = "Class Name:";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(123, 42);
			this.txtClassName.Location = point;
			this.txtClassName.Name = "txtClassName";
			size = new global::System.Drawing.Size(118, 20);
			this.txtClassName.Size = size;
			this.txtClassName.TabIndex = 19;
			point = new global::System.Drawing.Point(121, 95);
			this.udColumn.Location = point;
			this.udColumn.Name = "udColumn";
			size = new global::System.Drawing.Size(120, 20);
			this.udColumn.Size = size;
			this.udColumn.TabIndex = 21;
			this.udColumn.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			int[] array = new int[4];
			array[0] = 2;
			decimal num = new decimal(array);
			this.udColumn.Value = num;
			point = new global::System.Drawing.Point(30, 95);
			this.Label8.Location = point;
			this.Label8.Name = "Label8";
			size = new global::System.Drawing.Size(87, 20);
			this.Label8.Size = size;
			this.Label8.TabIndex = 22;
			this.Label8.Text = "Modifier Column:";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.GroupBox1.Controls.Add(this.Label18);
			this.GroupBox1.Controls.Add(this.udThreat);
			this.GroupBox1.Controls.Add(this.chkPlayable);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.Label8);
			this.GroupBox1.Controls.Add(this.txtName);
			this.GroupBox1.Controls.Add(this.udColumn);
			this.GroupBox1.Controls.Add(this.cbClassType);
			this.GroupBox1.Controls.Add(this.Label5);
			this.GroupBox1.Controls.Add(this.Label7);
			this.GroupBox1.Controls.Add(this.txtClassName);
			point = new global::System.Drawing.Point(12, 8);
			this.GroupBox1.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			size = new global::System.Drawing.Size(247, 151);
			this.GroupBox1.Size = size;
			this.GroupBox1.TabIndex = 23;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Basic";
			point = new global::System.Drawing.Point(121, 122);
			this.Label18.Location = point;
			this.Label18.Name = "Label18";
			size = new global::System.Drawing.Size(62, 19);
			this.Label18.Size = size;
			this.Label18.TabIndex = 25;
			this.Label18.Text = "Threat:";
			this.Label18.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(189, 121);
			this.udThreat.Location = point;
			array = new int[4];
			array[0] = 10;
			num = new decimal(array);
			this.udThreat.Maximum = num;
			this.udThreat.Name = "udThreat";
			size = new global::System.Drawing.Size(52, 20);
			this.udThreat.Size = size;
			this.udThreat.TabIndex = 24;
			this.udThreat.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			array = new int[4];
			array[0] = 2;
			num = new decimal(array);
			this.udThreat.Value = num;
			this.chkPlayable.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(13, 121);
			this.chkPlayable.Location = point;
			this.chkPlayable.Name = "chkPlayable";
			size = new global::System.Drawing.Size(85, 24);
			this.chkPlayable.Size = size;
			this.chkPlayable.TabIndex = 23;
			this.chkPlayable.Text = "Playable:";
			this.chkPlayable.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.chkPlayable.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.txtRecCap);
			this.GroupBox2.Controls.Add(this.Label21);
			this.GroupBox2.Controls.Add(this.Label22);
			this.GroupBox2.Controls.Add(this.txtRegCap);
			this.GroupBox2.Controls.Add(this.Label23);
			this.GroupBox2.Controls.Add(this.Label24);
			this.GroupBox2.Controls.Add(this.txtPerceptionCap);
			this.GroupBox2.Controls.Add(this.Label20);
			this.GroupBox2.Controls.Add(this.txtBaseRegen);
			this.GroupBox2.Controls.Add(this.Label19);
			this.GroupBox2.Controls.Add(this.txtBaseRec);
			this.GroupBox2.Controls.Add(this.Label17);
			this.GroupBox2.Controls.Add(this.txtRechargeCap);
			this.GroupBox2.Controls.Add(this.Label12);
			this.GroupBox2.Controls.Add(this.Label13);
			this.GroupBox2.Controls.Add(this.txtDamCap);
			this.GroupBox2.Controls.Add(this.Label9);
			this.GroupBox2.Controls.Add(this.txtResCap);
			this.GroupBox2.Controls.Add(this.txtHP);
			this.GroupBox2.Controls.Add(this.Label6);
			this.GroupBox2.Controls.Add(this.Label2);
			this.GroupBox2.Controls.Add(this.txtHPCap);
			this.GroupBox2.Controls.Add(this.Label3);
			this.GroupBox2.Controls.Add(this.Label10);
			this.GroupBox2.Controls.Add(this.Label11);
			point = new global::System.Drawing.Point(265, 8);
			this.GroupBox2.Location = point;
			this.GroupBox2.Name = "GroupBox2";
			size = new global::System.Drawing.Size(247, 352);
			this.GroupBox2.Size = size;
			this.GroupBox2.TabIndex = 24;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "HP && Caps";
			point = new global::System.Drawing.Point(133, 148);
			this.txtRecCap.Location = point;
			this.txtRecCap.Name = "txtRecCap";
			size = new global::System.Drawing.Size(90, 20);
			this.txtRecCap.Size = size;
			this.txtRecCap.TabIndex = 34;
			this.txtRecCap.Text = "500";
			this.txtRecCap.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(6, 148);
			this.Label21.Location = point;
			this.Label21.Name = "Label21";
			size = new global::System.Drawing.Size(121, 20);
			this.Label21.Size = size;
			this.Label21.TabIndex = 35;
			this.Label21.Text = "Recovery Cap:";
			this.Label21.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(221, 148);
			this.Label22.Location = point;
			this.Label22.Name = "Label22";
			size = new global::System.Drawing.Size(20, 20);
			this.Label22.Size = size;
			this.Label22.TabIndex = 36;
			this.Label22.Text = "%";
			this.Label22.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			point = new global::System.Drawing.Point(133, 174);
			this.txtRegCap.Location = point;
			this.txtRegCap.Name = "txtRegCap";
			size = new global::System.Drawing.Size(90, 20);
			this.txtRegCap.Size = size;
			this.txtRegCap.TabIndex = 31;
			this.txtRegCap.Text = "2000";
			this.txtRegCap.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(6, 174);
			this.Label23.Location = point;
			this.Label23.Name = "Label23";
			size = new global::System.Drawing.Size(121, 20);
			this.Label23.Size = size;
			this.Label23.TabIndex = 32;
			this.Label23.Text = "Regeneration Cap:";
			this.Label23.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(221, 174);
			this.Label24.Location = point;
			this.Label24.Name = "Label24";
			size = new global::System.Drawing.Size(20, 20);
			this.Label24.Size = size;
			this.Label24.TabIndex = 33;
			this.Label24.Text = "%";
			this.Label24.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			point = new global::System.Drawing.Point(133, 252);
			this.txtPerceptionCap.Location = point;
			this.txtPerceptionCap.Name = "txtPerceptionCap";
			size = new global::System.Drawing.Size(90, 20);
			this.txtPerceptionCap.Size = size;
			this.txtPerceptionCap.TabIndex = 29;
			this.txtPerceptionCap.Text = "100";
			this.txtPerceptionCap.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(6, 252);
			this.Label20.Location = point;
			this.Label20.Name = "Label20";
			size = new global::System.Drawing.Size(121, 20);
			this.Label20.Size = size;
			this.Label20.TabIndex = 30;
			this.Label20.Text = "Perception Cap";
			this.Label20.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(133, 224);
			this.txtBaseRegen.Location = point;
			this.txtBaseRegen.Name = "txtBaseRegen";
			size = new global::System.Drawing.Size(90, 20);
			this.txtBaseRegen.Size = size;
			this.txtBaseRegen.TabIndex = 27;
			this.txtBaseRegen.Text = "100";
			this.txtBaseRegen.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(6, 224);
			this.Label19.Location = point;
			this.Label19.Name = "Label19";
			size = new global::System.Drawing.Size(121, 20);
			this.Label19.Size = size;
			this.Label19.TabIndex = 28;
			this.Label19.Text = "Base Regeneration:";
			this.Label19.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(133, 198);
			this.txtBaseRec.Location = point;
			this.txtBaseRec.Name = "txtBaseRec";
			size = new global::System.Drawing.Size(90, 20);
			this.txtBaseRec.Size = size;
			this.txtBaseRec.TabIndex = 24;
			this.txtBaseRec.Text = "1.67";
			this.txtBaseRec.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(6, 198);
			this.Label17.Location = point;
			this.Label17.Name = "Label17";
			size = new global::System.Drawing.Size(121, 20);
			this.Label17.Size = size;
			this.Label17.TabIndex = 25;
			this.Label17.Text = "Base Recovery:";
			this.Label17.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(133, 97);
			this.txtRechargeCap.Location = point;
			this.txtRechargeCap.Name = "txtRechargeCap";
			size = new global::System.Drawing.Size(90, 20);
			this.txtRechargeCap.Size = size;
			this.txtRechargeCap.TabIndex = 21;
			this.txtRechargeCap.Text = "600";
			this.txtRechargeCap.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(6, 97);
			this.Label12.Location = point;
			this.Label12.Name = "Label12";
			size = new global::System.Drawing.Size(121, 20);
			this.Label12.Size = size;
			this.Label12.TabIndex = 22;
			this.Label12.Text = "Recharge Cap:";
			this.Label12.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(221, 97);
			this.Label13.Location = point;
			this.Label13.Name = "Label13";
			size = new global::System.Drawing.Size(20, 20);
			this.Label13.Size = size;
			this.Label13.TabIndex = 23;
			this.Label13.Text = "%";
			this.Label13.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			point = new global::System.Drawing.Point(133, 71);
			this.txtDamCap.Location = point;
			this.txtDamCap.Name = "txtDamCap";
			size = new global::System.Drawing.Size(90, 20);
			this.txtDamCap.Size = size;
			this.txtDamCap.TabIndex = 17;
			this.txtDamCap.Text = "400";
			this.txtDamCap.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			point = new global::System.Drawing.Point(6, 71);
			this.Label9.Location = point;
			this.Label9.Name = "Label9";
			size = new global::System.Drawing.Size(121, 20);
			this.Label9.Size = size;
			this.Label9.TabIndex = 18;
			this.Label9.Text = "Damage Cap:";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(221, 123);
			this.Label10.Location = point;
			this.Label10.Name = "Label10";
			size = new global::System.Drawing.Size(20, 20);
			this.Label10.Size = size;
			this.Label10.TabIndex = 19;
			this.Label10.Text = "%";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			point = new global::System.Drawing.Point(221, 71);
			this.Label11.Location = point;
			this.Label11.Name = "Label11";
			size = new global::System.Drawing.Size(20, 20);
			this.Label11.Size = size;
			this.Label11.TabIndex = 20;
			this.Label11.Text = "%";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.GroupBox3.Controls.Add(this.clbOrigin);
			point = new global::System.Drawing.Point(12, 165);
			this.GroupBox3.Location = point;
			this.GroupBox3.Name = "GroupBox3";
			size = new global::System.Drawing.Size(247, 276);
			this.GroupBox3.Size = size;
			this.GroupBox3.TabIndex = 25;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Origins";
			this.GroupBox4.Controls.Add(this.Label14);
			this.GroupBox4.Controls.Add(this.txtDescLong);
			this.GroupBox4.Controls.Add(this.Label4);
			this.GroupBox4.Controls.Add(this.txtDescShort);
			point = new global::System.Drawing.Point(12, 447);
			this.GroupBox4.Location = point;
			this.GroupBox4.Name = "GroupBox4";
			size = new global::System.Drawing.Size(500, 132);
			this.GroupBox4.Size = size;
			this.GroupBox4.TabIndex = 26;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "Descriptions";
			point = new global::System.Drawing.Point(12, 45);
			this.Label14.Location = point;
			this.Label14.Name = "Label14";
			size = new global::System.Drawing.Size(58, 20);
			this.Label14.Size = size;
			this.Label14.TabIndex = 5;
			this.Label14.Text = "Long:";
			this.Label14.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(76, 45);
			this.txtDescLong.Location = point;
			this.txtDescLong.Multiline = true;
			this.txtDescLong.Name = "txtDescLong";
			this.txtDescLong.ScrollBars = global::System.Windows.Forms.ScrollBars.Vertical;
			size = new global::System.Drawing.Size(418, 81);
			this.txtDescLong.Size = size;
			this.txtDescLong.TabIndex = 4;
			point = new global::System.Drawing.Point(12, 19);
			this.Label4.Location = point;
			this.Label4.Name = "Label4";
			size = new global::System.Drawing.Size(58, 20);
			this.Label4.Size = size;
			this.Label4.TabIndex = 3;
			this.Label4.Text = "Short:";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			point = new global::System.Drawing.Point(76, 19);
			this.txtDescShort.Location = point;
			this.txtDescShort.Name = "txtDescShort";
			size = new global::System.Drawing.Size(418, 20);
			this.txtDescShort.Size = size;
			this.txtDescShort.TabIndex = 2;
			this.GroupBox5.Controls.Add(this.cbSecGroup);
			this.GroupBox5.Controls.Add(this.Label16);
			this.GroupBox5.Controls.Add(this.cbPriGroup);
			this.GroupBox5.Controls.Add(this.Label15);
			point = new global::System.Drawing.Point(265, 366);
			this.GroupBox5.Location = point;
			this.GroupBox5.Name = "GroupBox5";
			size = new global::System.Drawing.Size(247, 75);
			this.GroupBox5.Size = size;
			this.GroupBox5.TabIndex = 27;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Power Set Groups";
			this.cbSecGroup.FormattingEnabled = true;
			point = new global::System.Drawing.Point(121, 46);
			this.cbSecGroup.Location = point;
			this.cbSecGroup.Name = "cbSecGroup";
			size = new global::System.Drawing.Size(118, 21);
			this.cbSecGroup.Size = size;
			this.cbSecGroup.TabIndex = 21;
			point = new global::System.Drawing.Point(5, 46);
			this.Label16.Location = point;
			this.Label16.Name = "Label16";
			size = new global::System.Drawing.Size(110, 21);
			this.Label16.Size = size;
			this.Label16.TabIndex = 22;
			this.Label16.Text = "Secondary Group:";
			this.Label16.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.cbPriGroup.FormattingEnabled = true;
			point = new global::System.Drawing.Point(121, 19);
			this.cbPriGroup.Location = point;
			this.cbPriGroup.Name = "cbPriGroup";
			size = new global::System.Drawing.Size(118, 21);
			this.cbPriGroup.Size = size;
			this.cbPriGroup.TabIndex = 19;
			point = new global::System.Drawing.Point(5, 19);
			this.Label15.Location = point;
			this.Label15.Name = "Label15";
			size = new global::System.Drawing.Size(110, 21);
			this.Label15.Size = size;
			this.Label15.TabIndex = 20;
			this.Label15.Text = "Primary Group:";
			this.Label15.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			base.AcceptButton = this.btnOK;
			size = new global::System.Drawing.Size(5, 13);
			this.AutoScaleBaseSize = size;
			this.BackColor = global::System.Drawing.SystemColors.Control;
			base.CancelButton = this.btnCancel;
			size = new global::System.Drawing.Size(522, 614);
			base.ClientSize = size;
			base.Controls.Add(this.GroupBox5);
			base.Controls.Add(this.GroupBox4);
			base.Controls.Add(this.GroupBox3);
			base.Controls.Add(this.GroupBox2);
			base.Controls.Add(this.GroupBox1);
			base.Controls.Add(this.btnCancel);
			base.Controls.Add(this.btnOK);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "frmEditArchetype";
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Edit Class (Class_Blaster - Blaster)";
			this.udColumn.EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.udThreat.EndInit();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			base.ResumeLayout(false);
		}


		private global::System.ComponentModel.IContainer components;
	}
}
