namespace Hero_Designer
{

    public partial class frmForum : global::System.Windows.Forms.Form
    {

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }


        [global::System.Diagnostics.DebuggerStepThrough]
        private void InitializeComponent()
        {
            this.components = new global::System.ComponentModel.Container();
            global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmForum));
            this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
            this.Label4 = new global::System.Windows.Forms.Label();
            this.csSlots = new global::System.Windows.Forms.Label();
            this.csLevel = new global::System.Windows.Forms.Label();
            this.csHeading = new global::System.Windows.Forms.Label();
            this.csTitle = new global::System.Windows.Forms.Label();
            this.Label21 = new global::System.Windows.Forms.Label();
            this.Label22 = new global::System.Windows.Forms.Label();
            this.Label20 = new global::System.Windows.Forms.Label();
            this.Label19 = new global::System.Windows.Forms.Label();
            this.csList = new global::System.Windows.Forms.ListBox();
            this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
            this.Label1 = new global::System.Windows.Forms.Label();
            this.lstCodes = new global::System.Windows.Forms.ListBox();
            this.lblCodeInf = new global::System.Windows.Forms.Label();
            this.chkDataChunk = new global::System.Windows.Forms.CheckBox();
            this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
            this.chkNoSetName = new global::System.Windows.Forms.CheckBox();
            this.chkNoIOLevel = new global::System.Windows.Forms.CheckBox();
            this.chkNoEnh = new global::System.Windows.Forms.CheckBox();
            this.chkBonusList = new global::System.Windows.Forms.CheckBox();
            this.chkBreakdown = new global::System.Windows.Forms.CheckBox();
            this.chkChunkOnly = new global::System.Windows.Forms.CheckBox();
            this.chkAlwaysDataChunk = new global::System.Windows.Forms.CheckBox();
            this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
            this.Label3 = new global::System.Windows.Forms.Label();
            this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
            this.Label2 = new global::System.Windows.Forms.Label();
            this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
            this.pbTitle = new global::System.Windows.Forms.PictureBox();
            this.ibCancel = new global::midsControls.ImageButton();
            this.ibExport = new global::midsControls.ImageButton();
            this.lblRecess = new global::System.Windows.Forms.Label();
            this.GroupBox1.SuspendLayout();
            this.GroupBox2.SuspendLayout();
            this.GroupBox3.SuspendLayout();
            this.GroupBox4.SuspendLayout();
            this.GroupBox5.SuspendLayout();
            ((global::System.ComponentModel.ISupportInitialize)this.pbTitle).BeginInit();
            base.SuspendLayout();
            this.GroupBox1.BackColor = global::System.Drawing.Color.Black;
            this.GroupBox1.Controls.Add(this.Label4);
            this.GroupBox1.Controls.Add(this.csSlots);
            this.GroupBox1.Controls.Add(this.csLevel);
            this.GroupBox1.Controls.Add(this.csHeading);
            this.GroupBox1.Controls.Add(this.csTitle);
            this.GroupBox1.Controls.Add(this.Label21);
            this.GroupBox1.Controls.Add(this.Label22);
            this.GroupBox1.Controls.Add(this.Label20);
            this.GroupBox1.Controls.Add(this.Label19);
            this.GroupBox1.Controls.Add(this.csList);
            this.GroupBox1.ForeColor = global::System.Drawing.Color.White;
            global::System.Drawing.Point point = new global::System.Drawing.Point(19, 34);
            this.GroupBox1.Location = point;
            this.GroupBox1.Name = "GroupBox1";
            global::System.Drawing.Size size = new global::System.Drawing.Size(328, 222);
            this.GroupBox1.Size = size;
            this.GroupBox1.TabIndex = 0;
            this.GroupBox1.TabStop = false;
            this.GroupBox1.Text = "Colour Scheme:";
            point = new global::System.Drawing.Point(165, 105);
            this.Label4.Location = point;
            this.Label4.Name = "Label4";
            size = new global::System.Drawing.Size(157, 89);
            this.Label4.Size = size;
            this.Label4.TabIndex = 19;
            this.Label4.Text = "Colour schemes marked '(US)' are intended for display on a dark bacground, and are suitable for the USA CoX forums.";
            this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.csSlots.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csSlots.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(260, 80);
            this.csSlots.Location = point;
            this.csSlots.Name = "csSlots";
            size = new global::System.Drawing.Size(52, 16);
            this.csSlots.Size = size;
            this.csSlots.TabIndex = 18;
            this.csLevel.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csLevel.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(260, 60);
            this.csLevel.Location = point;
            this.csLevel.Name = "csLevel";
            size = new global::System.Drawing.Size(52, 16);
            this.csLevel.Size = size;
            this.csLevel.TabIndex = 17;
            this.csHeading.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csHeading.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(260, 40);
            this.csHeading.Location = point;
            this.csHeading.Name = "csHeading";
            size = new global::System.Drawing.Size(52, 16);
            this.csHeading.Size = size;
            this.csHeading.TabIndex = 16;
            this.csTitle.BackColor = global::System.Drawing.Color.FromArgb(128, 128, 255);
            this.csTitle.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
            point = new global::System.Drawing.Point(260, 20);
            this.csTitle.Location = point;
            this.csTitle.Name = "csTitle";
            size = new global::System.Drawing.Size(52, 16);
            this.csTitle.Size = size;
            this.csTitle.TabIndex = 15;
            point = new global::System.Drawing.Point(168, 80);
            this.Label21.Location = point;
            this.Label21.Name = "Label21";
            size = new global::System.Drawing.Size(88, 16);
            this.Label21.Size = size;
            this.Label21.TabIndex = 14;
            this.Label21.Text = "Slots:";
            this.Label21.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(168, 60);
            this.Label22.Location = point;
            this.Label22.Name = "Label22";
            size = new global::System.Drawing.Size(88, 16);
            this.Label22.Size = size;
            this.Label22.TabIndex = 13;
            this.Label22.Text = "Levels:";
            this.Label22.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(168, 40);
            this.Label20.Location = point;
            this.Label20.Name = "Label20";
            size = new global::System.Drawing.Size(88, 16);
            this.Label20.Size = size;
            this.Label20.TabIndex = 12;
            this.Label20.Text = "Subheadings:";
            this.Label20.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(168, 20);
            this.Label19.Location = point;
            this.Label19.Name = "Label19";
            size = new global::System.Drawing.Size(88, 16);
            this.Label19.Size = size;
            this.Label19.TabIndex = 11;
            this.Label19.Text = "Title Text:";
            this.Label19.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.csList.ItemHeight = 14;
            point = new global::System.Drawing.Point(8, 20);
            this.csList.Location = point;
            this.csList.Name = "csList";
            size = new global::System.Drawing.Size(151, 186);
            this.csList.Size = size;
            this.csList.TabIndex = 10;
            this.GroupBox2.BackColor = global::System.Drawing.Color.Black;
            this.GroupBox2.Controls.Add(this.Label1);
            this.GroupBox2.Controls.Add(this.lstCodes);
            this.GroupBox2.Controls.Add(this.lblCodeInf);
            this.GroupBox2.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(353, 34);
            this.GroupBox2.Location = point;
            this.GroupBox2.Name = "GroupBox2";
            size = new global::System.Drawing.Size(268, 222);
            this.GroupBox2.Size = size;
            this.GroupBox2.TabIndex = 1;
            this.GroupBox2.TabStop = false;
            this.GroupBox2.Text = "Formatting Code Type:";
            point = new global::System.Drawing.Point(8, 16);
            this.Label1.Location = point;
            this.Label1.Name = "Label1";
            size = new global::System.Drawing.Size(256, 56);
            this.Label1.Size = size;
            this.Label1.TabIndex = 5;
            this.Label1.Text = "Different forums use different tags to change font style. Pick the forum type you need form this list. You can add more forum code sets in the program options window.";
            this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.lstCodes.ItemHeight = 14;
            point = new global::System.Drawing.Point(8, 76);
            this.lstCodes.Location = point;
            this.lstCodes.Name = "lstCodes";
            size = new global::System.Drawing.Size(252, 102);
            this.lstCodes.Size = size;
            this.lstCodes.TabIndex = 0;
            this.lblCodeInf.BackColor = global::System.Drawing.Color.Black;
            this.lblCodeInf.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(6, 187);
            this.lblCodeInf.Location = point;
            this.lblCodeInf.Name = "lblCodeInf";
            size = new global::System.Drawing.Size(256, 32);
            this.lblCodeInf.Size = size;
            this.lblCodeInf.TabIndex = 4;
            this.chkDataChunk.Checked = true;
            this.chkDataChunk.CheckState = global::System.Windows.Forms.CheckState.Checked;
            this.chkDataChunk.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(11, 76);
            this.chkDataChunk.Location = point;
            this.chkDataChunk.Name = "chkDataChunk";
            size = new global::System.Drawing.Size(371, 20);
            this.chkDataChunk.Size = size;
            this.chkDataChunk.TabIndex = 3;
            this.chkDataChunk.Text = "Export Data Chunk if creating a DataLink isn't possible";
            this.ToolTip1.SetToolTip(this.chkDataChunk, "Enable this to include a data chunk which can be copied by other forum users and imported into the Hero Designer");
            this.chkNoSetName.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(12, 52);
            this.chkNoSetName.Location = point;
            this.chkNoSetName.Name = "chkNoSetName";
            size = new global::System.Drawing.Size(180, 20);
            this.chkNoSetName.Size = size;
            this.chkNoSetName.TabIndex = 7;
            this.chkNoSetName.Text = "Don't Export IO Set Names";
            this.ToolTip1.SetToolTip(this.chkNoSetName, "Invention enhancements will not show which set they're from.");
            this.chkNoIOLevel.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(12, 76);
            this.chkNoIOLevel.Location = point;
            this.chkNoIOLevel.Name = "chkNoIOLevel";
            size = new global::System.Drawing.Size(180, 20);
            this.chkNoIOLevel.Size = size;
            this.chkNoIOLevel.TabIndex = 8;
            this.chkNoIOLevel.Text = "Don't Export Invention Levels";
            this.ToolTip1.SetToolTip(this.chkNoIOLevel, "Hides the level of Invention origin enhancements.");
            this.chkNoEnh.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(12, 100);
            this.chkNoEnh.Location = point;
            this.chkNoEnh.Name = "chkNoEnh";
            size = new global::System.Drawing.Size(180, 20);
            this.chkNoEnh.Size = size;
            this.chkNoEnh.TabIndex = 9;
            this.chkNoEnh.Text = "Don't Export Enhancements";
            this.ToolTip1.SetToolTip(this.chkNoEnh, "Exported builds won't show which enhancements are slotted into powers.");
            this.chkBonusList.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(12, 19);
            this.chkBonusList.Location = point;
            this.chkBonusList.Name = "chkBonusList";
            size = new global::System.Drawing.Size(143, 20);
            this.chkBonusList.Size = size;
            this.chkBonusList.TabIndex = 8;
            this.chkBonusList.Text = "Export Bonus Totals";
            this.ToolTip1.SetToolTip(this.chkBonusList, "The total effects of your set bonuses will be added to the end of the export");
            this.chkBreakdown.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(12, 43);
            this.chkBreakdown.Location = point;
            this.chkBreakdown.Name = "chkBreakdown";
            size = new global::System.Drawing.Size(143, 20);
            this.chkBreakdown.Size = size;
            this.chkBreakdown.TabIndex = 9;
            this.chkBreakdown.Text = "Export Set Breakdown";
            this.ToolTip1.SetToolTip(this.chkBreakdown, "A detailed breakdown of your set bonuses, including which power\r\nthey're coming from, will be appended to the export.");
            this.chkChunkOnly.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(32, 100);
            this.chkChunkOnly.Location = point;
            this.chkChunkOnly.Name = "chkChunkOnly";
            size = new global::System.Drawing.Size(168, 20);
            this.chkChunkOnly.Size = size;
            this.chkChunkOnly.TabIndex = 9;
            this.chkChunkOnly.Text = "Only export Data Chunk";
            this.ToolTip1.SetToolTip(this.chkChunkOnly, "Exports the Data Chunk by itself.\r\nDoesn't export any human-readable build information.");
            this.chkAlwaysDataChunk.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(8, 126);
            this.chkAlwaysDataChunk.Location = point;
            this.chkAlwaysDataChunk.Name = "chkAlwaysDataChunk";
            size = new global::System.Drawing.Size(371, 20);
            this.chkAlwaysDataChunk.Size = size;
            this.chkAlwaysDataChunk.TabIndex = 10;
            this.chkAlwaysDataChunk.Text = "Export Data Chunk as well as a DataLink";
            this.ToolTip1.SetToolTip(this.chkAlwaysDataChunk, "Enable this to include a data chunk which can be copied by other forum users and imported into the Hero Designer");
            this.GroupBox3.BackColor = global::System.Drawing.Color.Black;
            this.GroupBox3.Controls.Add(this.Label3);
            this.GroupBox3.Controls.Add(this.chkNoIOLevel);
            this.GroupBox3.Controls.Add(this.chkNoSetName);
            this.GroupBox3.Controls.Add(this.chkNoEnh);
            this.GroupBox3.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(413, 262);
            this.GroupBox3.Location = point;
            this.GroupBox3.Name = "GroupBox3";
            size = new global::System.Drawing.Size(208, 124);
            this.GroupBox3.Size = size;
            this.GroupBox3.TabIndex = 10;
            this.GroupBox3.TabStop = false;
            this.GroupBox3.Text = "Enhancements:";
            point = new global::System.Drawing.Point(12, 20);
            this.Label3.Location = point;
            this.Label3.Name = "Label3";
            size = new global::System.Drawing.Size(192, 28);
            this.Label3.Size = size;
            this.Label3.TabIndex = 10;
            this.Label3.Text = "These affect the build profile only, the data chunk is unaffected.";
            this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.GroupBox4.BackColor = global::System.Drawing.Color.Black;
            this.GroupBox4.Controls.Add(this.chkAlwaysDataChunk);
            this.GroupBox4.Controls.Add(this.chkChunkOnly);
            this.GroupBox4.Controls.Add(this.Label2);
            this.GroupBox4.Controls.Add(this.chkDataChunk);
            this.GroupBox4.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(19, 262);
            this.GroupBox4.Location = point;
            this.GroupBox4.Name = "GroupBox4";
            size = new global::System.Drawing.Size(388, 152);
            this.GroupBox4.Size = size;
            this.GroupBox4.TabIndex = 11;
            this.GroupBox4.TabStop = false;
            this.GroupBox4.Text = "Data Chunk:";
            point = new global::System.Drawing.Point(8, 16);
            this.Label2.Location = point;
            this.Label2.Name = "Label2";
            size = new global::System.Drawing.Size(374, 56);
            this.Label2.Size = size;
            this.Label2.TabIndex = 7;
            this.Label2.Text = "If a build is too complex to be exported in a DataLink, export can fall back to exporting a Data Chunk at the end of a build. Users can import the data chunk to view the build.";
            this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
            this.GroupBox5.BackColor = global::System.Drawing.Color.Black;
            this.GroupBox5.Controls.Add(this.chkBreakdown);
            this.GroupBox5.Controls.Add(this.chkBonusList);
            this.GroupBox5.ForeColor = global::System.Drawing.Color.White;
            point = new global::System.Drawing.Point(413, 392);
            this.GroupBox5.Location = point;
            this.GroupBox5.Name = "GroupBox5";
            size = new global::System.Drawing.Size(208, 72);
            this.GroupBox5.Size = size;
            this.GroupBox5.TabIndex = 12;
            this.GroupBox5.TabStop = false;
            this.GroupBox5.Text = "Set Bonuses:";
            this.pbTitle.BackColor = global::System.Drawing.Color.Transparent;
            this.pbTitle.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("pbTitle.Image");
            point = new global::System.Drawing.Point(180, 6);
            this.pbTitle.Location = point;
            this.pbTitle.Name = "pbTitle";
            size = new global::System.Drawing.Size(263, 24);
            this.pbTitle.Size = size;
            this.pbTitle.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pbTitle.TabIndex = 15;
            this.pbTitle.TabStop = false;
            this.ibCancel.Checked = false;
            this.ibCancel.Font = new global::System.Drawing.Font("Arial", 11f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Pixel, 0);
            point = new global::System.Drawing.Point(0, 0);
            this.ibCancel.KnockoutLocationPoint = point;
            point = new global::System.Drawing.Point(52, 431);
            this.ibCancel.Location = point;
            this.ibCancel.Name = "ibCancel";
            size = new global::System.Drawing.Size(105, 22);
            this.ibCancel.Size = size;
            this.ibCancel.TabIndex = 14;
            this.ibCancel.TextOff = "Cancel";
            this.ibCancel.TextOn = "Alt Text";
            this.ibCancel.Toggle = false;
            this.ibExport.Checked = false;
            this.ibExport.Font = new global::System.Drawing.Font("Arial", 11f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Pixel, 0);
            point = new global::System.Drawing.Point(0, 0);
            this.ibExport.KnockoutLocationPoint = point;
            point = new global::System.Drawing.Point(246, 431);
            this.ibExport.Location = point;
            this.ibExport.Name = "ibExport";
            size = new global::System.Drawing.Size(105, 22);
            this.ibExport.Size = size;
            this.ibExport.TabIndex = 13;
            this.ibExport.TextOff = "Export Now";
            this.ibExport.TextOn = "Alt Text";
            this.ibExport.Toggle = false;
            this.lblRecess.BackColor = global::System.Drawing.Color.Black;
            this.lblRecess.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
            point = new global::System.Drawing.Point(12, 31);
            this.lblRecess.Location = point;
            this.lblRecess.Name = "lblRecess";
            size = new global::System.Drawing.Size(616, 439);
            this.lblRecess.Size = size;
            this.lblRecess.TabIndex = 16;
            base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = global::System.Drawing.Color.FromArgb(0, 0, 32);
            this.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
            size = new global::System.Drawing.Size(640, 480);
            base.ClientSize = size;
            base.Controls.Add(this.pbTitle);
            base.Controls.Add(this.ibCancel);
            base.Controls.Add(this.ibExport);
            base.Controls.Add(this.GroupBox5);
            base.Controls.Add(this.GroupBox4);
            base.Controls.Add(this.GroupBox3);
            base.Controls.Add(this.GroupBox2);
            base.Controls.Add(this.GroupBox1);
            base.Controls.Add(this.lblRecess);
            this.Font = new global::System.Drawing.Font("Arial", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Pixel, 0);
            this.ForeColor = global::System.Drawing.Color.White;
            base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
            base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmForum";
            base.ShowInTaskbar = false;
            base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Forum Export";
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox3.ResumeLayout(false);
            this.GroupBox4.ResumeLayout(false);
            this.GroupBox5.ResumeLayout(false);
            ((global::System.ComponentModel.ISupportInitialize)this.pbTitle).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        private global::System.ComponentModel.IContainer components;
    }
}
