namespace Hero_Designer
{

    public partial class frmSetEdit : global::System.Windows.Forms.Form
    {

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }
        [global::System.Diagnostics.DebuggerStepThrough]
        void InitializeComponent()
        {
            this.components = new global::System.ComponentModel.Container();
            global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hero_Designer.frmSetEdit));
            this.btnNoImage = new global::System.Windows.Forms.Button();
            this.gbBasic = new global::System.Windows.Forms.GroupBox();
            this.txtInternal = new global::System.Windows.Forms.TextBox();
            this.Label5 = new global::System.Windows.Forms.Label();
            this.cbSetType = new global::System.Windows.Forms.ComboBox();
            this.Label1 = new global::System.Windows.Forms.Label();
            this.Label7 = new global::System.Windows.Forms.Label();
            this.Label6 = new global::System.Windows.Forms.Label();
            this.udMinLevel = new global::System.Windows.Forms.NumericUpDown();
            this.udMaxLevel = new global::System.Windows.Forms.NumericUpDown();
            this.txtDesc = new global::System.Windows.Forms.TextBox();
            this.Label4 = new global::System.Windows.Forms.Label();
            this.txtNameShort = new global::System.Windows.Forms.TextBox();
            this.Label3 = new global::System.Windows.Forms.Label();
            this.txtNameFull = new global::System.Windows.Forms.TextBox();
            this.Label2 = new global::System.Windows.Forms.Label();
            this.btnImage = new global::System.Windows.Forms.Button();
            this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
            this.lvEnh = new global::System.Windows.Forms.ListView();
            this.ColumnHeader1 = new global::System.Windows.Forms.ColumnHeader();
            this.ColumnHeader2 = new global::System.Windows.Forms.ColumnHeader();
            this.ilEnh = new global::System.Windows.Forms.ImageList(this.components);
            this.btnCancel = new global::System.Windows.Forms.Button();
            this.btnOK = new global::System.Windows.Forms.Button();
            this.ImagePicker = new global::System.Windows.Forms.OpenFileDialog();
            this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
            this.btnPaste = new global::System.Windows.Forms.Button();
            this.txtAlternate = new global::System.Windows.Forms.TextBox();
            this.lvBonusList = new global::System.Windows.Forms.ListView();
            this.ColumnHeader3 = new global::System.Windows.Forms.ColumnHeader();
            this.ColumnHeader4 = new global::System.Windows.Forms.ColumnHeader();
            this.lstBonus = new global::System.Windows.Forms.ListBox();
            this.Label16 = new global::System.Windows.Forms.Label();
            this.cbSlotCount = new global::System.Windows.Forms.ComboBox();
            this.rtbBonus = new global::System.Windows.Forms.RichTextBox();
            this.Label27 = new global::System.Windows.Forms.Label();
            this.rbIfPlayer = new global::System.Windows.Forms.RadioButton();
            this.rbIfCritter = new global::System.Windows.Forms.RadioButton();
            this.rbIfAny = new global::System.Windows.Forms.RadioButton();
            this.gbBasic.SuspendLayout();
            this.udMinLevel.BeginInit();
            this.udMaxLevel.BeginInit();
            this.GroupBox2.SuspendLayout();
            this.GroupBox3.SuspendLayout();
            base.SuspendLayout();
            global::System.Drawing.Point point = new global::System.Drawing.Point(8, 84);
            this.btnNoImage.Location = point;
            this.btnNoImage.Name = "btnNoImage";
            global::System.Drawing.Size size = new global::System.Drawing.Size(80, 20);
            this.btnNoImage.Size = size;
            this.btnNoImage.TabIndex = 2;
            this.btnNoImage.Text = "Clear Image";
            this.gbBasic.Controls.Add(this.txtInternal);
            this.gbBasic.Controls.Add(this.Label5);
            this.gbBasic.Controls.Add(this.cbSetType);
            this.gbBasic.Controls.Add(this.Label1);
            this.gbBasic.Controls.Add(this.Label7);
            this.gbBasic.Controls.Add(this.Label6);
            this.gbBasic.Controls.Add(this.udMinLevel);
            this.gbBasic.Controls.Add(this.udMaxLevel);
            this.gbBasic.Controls.Add(this.txtDesc);
            this.gbBasic.Controls.Add(this.Label4);
            this.gbBasic.Controls.Add(this.txtNameShort);
            this.gbBasic.Controls.Add(this.Label3);
            this.gbBasic.Controls.Add(this.txtNameFull);
            this.gbBasic.Controls.Add(this.Label2);
            point = new global::System.Drawing.Point(96, 8);
            this.gbBasic.Location = point;
            this.gbBasic.Name = "gbBasic";
            size = new global::System.Drawing.Size(248, 202);
            this.gbBasic.Size = size;
            this.gbBasic.TabIndex = 0;
            this.gbBasic.TabStop = false;
            this.gbBasic.Text = "Basic:";
            point = new global::System.Drawing.Point(84, 66);
            this.txtInternal.Location = point;
            this.txtInternal.Name = "txtInternal";
            size = new global::System.Drawing.Size(156, 20);
            this.txtInternal.Size = size;
            this.txtInternal.TabIndex = 21;
            point = new global::System.Drawing.Point(8, 66);
            this.Label5.Location = point;
            this.Label5.Name = "Label5";
            size = new global::System.Drawing.Size(72, 20);
            this.Label5.Size = size;
            this.Label5.TabIndex = 22;
            this.Label5.Text = "Internal:";
            this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.cbSetType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            point = new global::System.Drawing.Point(84, 174);
            this.cbSetType.Location = point;
            this.cbSetType.Name = "cbSetType";
            size = new global::System.Drawing.Size(156, 22);
            this.cbSetType.Size = size;
            this.cbSetType.TabIndex = 3;
            point = new global::System.Drawing.Point(8, 174);
            this.Label1.Location = point;
            this.Label1.Name = "Label1";
            size = new global::System.Drawing.Size(72, 20);
            this.Label1.Size = size;
            this.Label1.TabIndex = 20;
            this.Label1.Text = "SetType:";
            this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(8, 150);
            this.Label7.Location = point;
            this.Label7.Name = "Label7";
            size = new global::System.Drawing.Size(52, 20);
            this.Label7.Size = size;
            this.Label7.TabIndex = 19;
            this.Label7.Text = "MaxLev:";
            this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(8, 126);
            this.Label6.Location = point;
            this.Label6.Name = "Label6";
            size = new global::System.Drawing.Size(52, 20);
            this.Label6.Size = size;
            this.Label6.TabIndex = 18;
            this.Label6.Text = "MinLev:";
            this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(64, 126);
            this.udMinLevel.Location = point;
            int[] array = new int[4];
            array[0] = 53;
            decimal num = new decimal(array);
            this.udMinLevel.Maximum = num;
            array = new int[4];
            array[0] = 1;
            num = new decimal(array);
            this.udMinLevel.Minimum = num;
            this.udMinLevel.Name = "udMinLevel";
            size = new global::System.Drawing.Size(36, 20);
            this.udMinLevel.Size = size;
            this.udMinLevel.TabIndex = 4;
            array = new int[4];
            array[0] = 1;
            num = new decimal(array);
            this.udMinLevel.Value = num;
            point = new global::System.Drawing.Point(64, 150);
            this.udMaxLevel.Location = point;
            array = new int[4];
            array[0] = 53;
            num = new decimal(array);
            this.udMaxLevel.Maximum = num;
            array = new int[4];
            array[0] = 1;
            num = new decimal(array);
            this.udMaxLevel.Minimum = num;
            this.udMaxLevel.Name = "udMaxLevel";
            size = new global::System.Drawing.Size(36, 20);
            this.udMaxLevel.Size = size;
            this.udMaxLevel.TabIndex = 5;
            array = new int[4];
            array[0] = 53;
            num = new decimal(array);
            this.udMaxLevel.Value = num;
            point = new global::System.Drawing.Point(100, 102);
            this.txtDesc.Location = point;
            this.txtDesc.Multiline = true;
            this.txtDesc.Name = "txtDesc";
            size = new global::System.Drawing.Size(140, 68);
            this.txtDesc.Size = size;
            this.txtDesc.TabIndex = 2;
            point = new global::System.Drawing.Point(8, 102);
            this.Label4.Location = point;
            this.Label4.Name = "Label4";
            size = new global::System.Drawing.Size(88, 20);
            this.Label4.Size = size;
            this.Label4.TabIndex = 14;
            this.Label4.Text = "Description:";
            this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(84, 40);
            this.txtNameShort.Location = point;
            this.txtNameShort.Name = "txtNameShort";
            size = new global::System.Drawing.Size(156, 20);
            this.txtNameShort.Size = size;
            this.txtNameShort.TabIndex = 1;
            point = new global::System.Drawing.Point(8, 40);
            this.Label3.Location = point;
            this.Label3.Name = "Label3";
            size = new global::System.Drawing.Size(72, 20);
            this.Label3.Size = size;
            this.Label3.TabIndex = 12;
            this.Label3.Text = "Short Name:";
            this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(84, 16);
            this.txtNameFull.Location = point;
            this.txtNameFull.Name = "txtNameFull";
            size = new global::System.Drawing.Size(156, 20);
            this.txtNameFull.Size = size;
            this.txtNameFull.TabIndex = 0;
            point = new global::System.Drawing.Point(8, 16);
            this.Label2.Location = point;
            this.Label2.Name = "Label2";
            size = new global::System.Drawing.Size(72, 20);
            this.Label2.Size = size;
            this.Label2.TabIndex = 10;
            this.Label2.Text = "Full Name:";
            this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.btnImage.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnImage.Image");
            this.btnImage.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
            point = new global::System.Drawing.Point(8, 12);
            this.btnImage.Location = point;
            this.btnImage.Name = "btnImage";
            size = new global::System.Drawing.Size(80, 68);
            this.btnImage.Size = size;
            this.btnImage.TabIndex = 1;
            this.btnImage.Text = "ImageName";
            this.btnImage.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
            this.GroupBox2.Controls.Add(this.lvEnh);
            point = new global::System.Drawing.Point(6, 216);
            this.GroupBox2.Location = point;
            this.GroupBox2.Name = "GroupBox2";
            size = new global::System.Drawing.Size(336, 224);
            this.GroupBox2.Size = size;
            this.GroupBox2.TabIndex = 24;
            this.GroupBox2.TabStop = false;
            this.GroupBox2.Text = "Enhancements belonging to this set:";
            this.lvEnh.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
            {
                this.ColumnHeader1,
                this.ColumnHeader2
            });
            this.lvEnh.FullRowSelect = true;
            this.lvEnh.LargeImageList = this.ilEnh;
            point = new global::System.Drawing.Point(8, 20);
            this.lvEnh.Location = point;
            this.lvEnh.Name = "lvEnh";
            size = new global::System.Drawing.Size(320, 196);
            this.lvEnh.Size = size;
            this.lvEnh.SmallImageList = this.ilEnh;
            this.lvEnh.TabIndex = 0;
            this.lvEnh.UseCompatibleStateImageBehavior = false;
            this.lvEnh.View = global::System.Windows.Forms.View.Details;
            this.ColumnHeader1.Text = "Name";
            this.ColumnHeader1.Width = 203;
            this.ColumnHeader2.Text = "Classes";
            this.ColumnHeader2.Width = 91;
            this.ilEnh.ColorDepth = global::System.Windows.Forms.ColorDepth.Depth32Bit;
            size = new global::System.Drawing.Size(30, 30);
            this.ilEnh.ImageSize = size;
            this.ilEnh.TransparentColor = global::System.Drawing.Color.Transparent;
            this.btnCancel.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
            point = new global::System.Drawing.Point(160, 446);
            this.btnCancel.Location = point;
            this.btnCancel.Name = "btnCancel";
            size = new global::System.Drawing.Size(84, 28);
            this.btnCancel.Size = size;
            this.btnCancel.TabIndex = 5;
            this.btnCancel.Text = "Cancel";
            this.btnOK.DialogResult = global::System.Windows.Forms.DialogResult.OK;
            point = new global::System.Drawing.Point(252, 446);
            this.btnOK.Location = point;
            this.btnOK.Name = "btnOK";
            size = new global::System.Drawing.Size(84, 28);
            this.btnOK.Size = size;
            this.btnOK.TabIndex = 4;
            this.btnOK.Text = "OK";
            this.ImagePicker.Filter = "PNG Images|*.png";
            this.ImagePicker.Title = "Select Image File";
            this.GroupBox3.Controls.Add(this.btnPaste);
            this.GroupBox3.Controls.Add(this.txtAlternate);
            this.GroupBox3.Controls.Add(this.lvBonusList);
            this.GroupBox3.Controls.Add(this.lstBonus);
            this.GroupBox3.Controls.Add(this.Label16);
            this.GroupBox3.Controls.Add(this.cbSlotCount);
            this.GroupBox3.Controls.Add(this.rtbBonus);
            point = new global::System.Drawing.Point(348, 8);
            this.GroupBox3.Location = point;
            this.GroupBox3.Name = "GroupBox3";
            size = new global::System.Drawing.Size(629, 432);
            this.GroupBox3.Size = size;
            this.GroupBox3.TabIndex = 25;
            this.GroupBox3.TabStop = false;
            this.GroupBox3.Text = "Set Bonuses:";
            point = new global::System.Drawing.Point(8, 280);
            this.btnPaste.Location = point;
            this.btnPaste.Name = "btnPaste";
            size = new global::System.Drawing.Size(96, 23);
            this.btnPaste.Size = size;
            this.btnPaste.TabIndex = 19;
            this.btnPaste.Text = "Fill by Paste";
            this.btnPaste.Visible = false;
            point = new global::System.Drawing.Point(8, 406);
            this.txtAlternate.Location = point;
            this.txtAlternate.Name = "txtAlternate";
            size = new global::System.Drawing.Size(270, 20);
            this.txtAlternate.Size = size;
            this.txtAlternate.TabIndex = 18;
            this.lvBonusList.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
            {
                this.ColumnHeader3,
                this.ColumnHeader4
            });
            this.lvBonusList.FullRowSelect = true;
            this.lvBonusList.HeaderStyle = global::System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
            this.lvBonusList.HideSelection = false;
            point = new global::System.Drawing.Point(284, 19);
            this.lvBonusList.Location = point;
            this.lvBonusList.MultiSelect = false;
            this.lvBonusList.Name = "lvBonusList";
            size = new global::System.Drawing.Size(339, 407);
            this.lvBonusList.Size = size;
            this.lvBonusList.TabIndex = 17;
            this.lvBonusList.UseCompatibleStateImageBehavior = false;
            this.lvBonusList.View = global::System.Windows.Forms.View.Details;
            this.ColumnHeader3.Text = "Bonus";
            this.ColumnHeader3.Width = 185;
            this.ColumnHeader4.Text = "Effect";
            this.ColumnHeader4.Width = 110;
            this.lstBonus.ItemHeight = 14;
            point = new global::System.Drawing.Point(8, 309);
            this.lstBonus.Location = point;
            this.lstBonus.Name = "lstBonus";
            size = new global::System.Drawing.Size(271, 88);
            this.lstBonus.Size = size;
            this.lstBonus.TabIndex = 16;
            point = new global::System.Drawing.Point(8, 281);
            this.Label16.Location = point;
            this.Label16.Name = "Label16";
            size = new global::System.Drawing.Size(96, 20);
            this.Label16.Size = size;
            this.Label16.TabIndex = 15;
            this.Label16.Text = "Bonus for slotting:";
            this.Label16.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            this.cbSlotCount.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbSlotCount.Items.AddRange(new object[]
            {
                "2",
                "3",
                "4",
                "5",
                "6"
            });
            point = new global::System.Drawing.Point(110, 281);
            this.cbSlotCount.Location = point;
            this.cbSlotCount.Name = "cbSlotCount";
            size = new global::System.Drawing.Size(170, 22);
            this.cbSlotCount.Size = size;
            this.cbSlotCount.TabIndex = 3;
            this.rtbBonus.BackColor = global::System.Drawing.Color.White;
            this.rtbBonus.ForeColor = global::System.Drawing.Color.Black;
            point = new global::System.Drawing.Point(6, 19);
            this.rtbBonus.Location = point;
            this.rtbBonus.Name = "rtbBonus";
            this.rtbBonus.ReadOnly = true;
            this.rtbBonus.ScrollBars = global::System.Windows.Forms.RichTextBoxScrollBars.Vertical;
            size = new global::System.Drawing.Size(272, 256);
            this.rtbBonus.Size = size;
            this.rtbBonus.TabIndex = 1;
            this.rtbBonus.Text = "";
            point = new global::System.Drawing.Point(351, 450);
            this.Label27.Location = point;
            this.Label27.Name = "Label27";
            size = new global::System.Drawing.Size(76, 20);
            this.Label27.Size = size;
            this.Label27.TabIndex = 106;
            this.Label27.Text = "If Target =";
            this.Label27.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
            point = new global::System.Drawing.Point(563, 451);
            this.rbIfPlayer.Location = point;
            this.rbIfPlayer.Name = "rbIfPlayer";
            size = new global::System.Drawing.Size(76, 20);
            this.rbIfPlayer.Size = size;
            this.rbIfPlayer.TabIndex = 105;
            this.rbIfPlayer.Text = "Players";
            point = new global::System.Drawing.Point(486, 451);
            this.rbIfCritter.Location = point;
            this.rbIfCritter.Name = "rbIfCritter";
            size = new global::System.Drawing.Size(71, 20);
            this.rbIfCritter.Size = size;
            this.rbIfCritter.TabIndex = 104;
            this.rbIfCritter.Text = "Critters";
            this.rbIfAny.Checked = true;
            point = new global::System.Drawing.Point(433, 451);
            this.rbIfAny.Location = point;
            this.rbIfAny.Name = "rbIfAny";
            size = new global::System.Drawing.Size(57, 20);
            this.rbIfAny.Size = size;
            this.rbIfAny.TabIndex = 103;
            this.rbIfAny.TabStop = true;
            this.rbIfAny.Text = "Any";
            base.AcceptButton = this.btnOK;
            size = new global::System.Drawing.Size(5, 13);
            this.AutoScaleBaseSize = size;
            base.CancelButton = this.btnCancel;
            size = new global::System.Drawing.Size(989, 482);
            base.ClientSize = size;
            base.Controls.Add(this.Label27);
            base.Controls.Add(this.rbIfPlayer);
            base.Controls.Add(this.rbIfCritter);
            base.Controls.Add(this.rbIfAny);
            base.Controls.Add(this.GroupBox3);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.GroupBox2);
            base.Controls.Add(this.btnNoImage);
            base.Controls.Add(this.gbBasic);
            base.Controls.Add(this.btnImage);
            this.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
            base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmSetEdit";
            base.ShowInTaskbar = false;
            base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Invention Set Editor";
            this.gbBasic.ResumeLayout(false);
            this.gbBasic.PerformLayout();
            this.udMinLevel.EndInit();
            this.udMaxLevel.EndInit();
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox3.ResumeLayout(false);
            this.GroupBox3.PerformLayout();
            base.ResumeLayout(false);
        }
        global::System.ComponentModel.IContainer components;
    }
}
